mirage/irmin

opam

Stringext.cut introduced in 1.1.0

---

CHANGES.md
lib/http/irmin_http.ml
lib/ir_bc.ml
lib/ir_bc.mli
lib/ir_task.ml
lib/ir_task.mli
lib/ir_view.ml
lib/ir_view.mli
lib/irmin.ml
lib/irmin.mli
lib_test/test_store.ml

As discussed on the mailing list.

Add View.make_head

---

examples/custom_merge.ml
opam

Cut a minor release (with some know bugs, but stable enough to be used for demo)

Prepare the release

---

lib/git/irmin_git.ml
lib/git/irmin_git.mli

This provides the Irmin Contents/Node/Commit APIs on top of a Git-type store. This is useful for backends that want to store data using the Git object format, to be able to sync with Git, but without using Git's filesystem layout and locking.
The [irmin-indexeddb git-format branch](https://github.com/talex5/irmin-indexeddb/tree/git-format) uses this to store data in Git format.
However, I'm not sure if this is the right way to expose the API. Comments?

[RFC] Expose Irmin_value_store functor

---

lib/http/irmin_http.ml
lib/http/irmin_http_server.ml
lib/ir_bc.ml
lib/ir_bc.mli
lib/ir_s.ml
lib/ir_s.mli
lib/irmin.mli

Add /view/iter to iterate over the view's contents

---

lib/http/irmin_http_server.ml

The exposed API is terrible (complete lack of consistency) but at least there is now a hook for watches.
/cc @MagnusS

Implement a /watch handler for the HTTP server

---

.merlin
lib/git/irmin_git.ml
lib/git/irmin_git.mli
lib/http/irmin_http.ml
lib/http/irmin_http_server.ml
lib/ir_bc.ml
lib/ir_commit.ml
lib/ir_commit.mli
lib/ir_contents.ml
lib/ir_contents.mli
lib/ir_node.ml
lib/ir_node.mli
lib/ir_s.mli
lib/ir_view.ml
lib/irmin.ml
lib/irmin.mli
lib_test/test_store.ml

The patch looks rather large but it's just shuffling code around to fit the new API, so @talex5 if you want to review, you can just have a look at `irmin.mli` and `irmin_git.mli`. Hopefully this will expose enough things for your use-case.

Refactore Node.STORE and Commit.STORE

---

lib/ir_commit.ml

`update_ancestors_marks` should stop exploring when it doesn't change a node's mark.
I think this logic is correct, but please check.
This reduced the time to search for an LCA between 6fbc206 in the Docker repository and a disconnected commit to 2s (previously it took so long I aborted it).

Fix performance problem in lcas

---

lib/git/irmin_git.ml
lib_test/test_git.ml

For Git we need to sort as if each directory had a '/' on the end.
Fixes #352
(some more optimisations are possible here, but the code is already too complicated)

Fix sort order for Git trees

---

lib_test/test_common.ml
lib_test/test_http.ml
pkg/pkg.ml

The server and client metadata needs to be the same.

Fix Git over HTTP tests

---

appveyor.yml
irmin-unix.opam

Installing `irmin-unix` should install `irmin-watcher`.

Fix irmin-unix.opam

---

src-git/irmin_git.ml
src-git/irmin_git.mli
src-mirage/irmin_mirage.ml
src-mirage/irmin_mirage.mli
src-unix/irmin_unix.ml
src-unix/irmin_unix.mli

Allow to set-up a custom `.git` path when loading an Irmin store

---

bin/ir_cli.ml

Add irminconfig man page

---

src/ir_sync_ext.ml

The syntax is: "example.com#master" to fetch the `master` branch.

allow to specify branches in urls for fetch

---

irmin-git.opam
src-git/irmin_git.ml
src/ir_s.mli
src/ir_store.mli
src/irmin.mli

Add an S.repo type

---

src/ir_contents.ml

Pretty-print the raw contents, not the hexdump

Fix Irmin.Contents.Cstruct

---

src/irmin-git/irmin_git.ml

Fix regression in watches

---

pkg/META
pkg/META.git
pkg/META.http
pkg/META.mirage
pkg/META.unix

these are autogenerated since #444 and the port to jbuilder

remove unused META files

---

README.md
src/irmin/irmin.mli

Thanks to @talex5 for noticing.
/cc @dudelson who is also looking at improving the docs.

Fix code snippets in README and irmin.mli

---

README.md

Fix a thinko in the first substantive usage example; it's not clear what `prog` refers to, and the code doesn't compile.

fix example code such that it actually compiles and makes sense

---

src/irmin/hash.ml

This should fix the error seen in https://github.com/mirage/ocaml-uri/pull/109#issuecomment-341926848
Signed-off-by: David Scott <dave@recoil.org>

Fix build with OCaml 4.06 (and -safe-string)

---

README.md
examples/custom_merge.ml
examples/jbuild
examples/sync.ml
examples/trees.ml
src/irmin/tree.ml

Some minor fixes for the examples.

Examples update

---

.travis.yml
appveyor.yml
src/irmin-git/irmin_git.ml
src/irmin-git/irmin_git.mli
src/irmin-mirage/irmin_mirage.ml
src/irmin-mirage/irmin_mirage.mli
src/irmin-unix/bin/ir_resolver.ml
src/irmin-unix/irmin_unix.ml
src/irmin-unix/irmin_unix.mli
test/common/test_store.ml
test/irmin-git/test_git.ml
test/irmin-unix/test_unix.ml

Seems to compile fine but it exposes a few issue with the new API.

Use the new ocaml-git in irmin-git

---

src/irmin/irmin.mli

reference `Irmin.Type` instead of `mirage-tc` and restore example to running condition

update mergable log example in docs

---

src/irmin-unix/bin/ir_cli.ml

The merge command allows you to merge between branches from the command line. 
While adding this I also noticed that the fetch command was not added to the command list.

Merge command

---

src/irmin/irmin.mli

This pull request updates some out of date documentation found in the `Contents` module.

Update overview of Contents module

---

src/irmin-unix/ir_resolver.ml
src/irmin-unix/ir_unix.ml
src/irmin-unix/ir_unix.mli
src/irmin-unix/irmin_unix.mli
test/irmin-unix/test_unix.ml

I did my best to match the current stable version, let me know if you see any discrepancies or other issues.

Update Irmin_unix.Git match existing API

---

examples/jbuild
src/irmin-git/jbuild
src/irmin-unix/bin/jbuild
src/irmin-unix/jbuild
test/irmin-git/jbuild
test/irmin-http/jbuild
test/irmin-unix/jbuild

I'm not sure if this is totally right, but I needed to add this to get Irmin to build after upgrading some opam packages.

Link to checkseum.c where needed

---

src/irmin/hash.ml
src/irmin/object_graph.ml
src/irmin/type.ml

Fix graphviz output

---

src/irmin-test/common.ml
src/irmin-test/irmin_test.ml
src/irmin-test/irmin_test.mli
src/irmin-test/link.ml
src/irmin-test/store.ml
test/irmin-chunk/test.ml
test/irmin-chunk/test_chunk.ml
test/irmin-fs/test.ml
test/irmin-fs/test_fs.ml
test/irmin-git/test.ml
test/irmin-git/test_git.ml
test/irmin-http/test.ml
test/irmin-http/test_http.ml
test/irmin-mem/test.ml
test/irmin-mem/test_mem.ml
test/irmin-unix/test.ml
test/irmin-unix/test_unix.ml

/cc @g2p and @zshipko as it will have an impact on the tests for the backend that you wrote.

irmin-test: remove the unecessary `Irmin_` prefix

---

examples/dune
examples/push.ml

/cc @hannesm 
Also, we should probably add a first-class support to parse GH token in the Irmin CLI.

Add a Git push example

---

src/irmin-unix/cli.ml

I had forgotten to add `graphql` to the list of commands printed when running `irmin` with no command provided.

Add graphql to list of commands printed by default

---

examples/custom_merge.ml
examples/deploy.ml
examples/irmin_git_store.ml
examples/process.ml
examples/push.ml
examples/sync.ml
examples/trees.ml
src/irmin-graphql/irmin_graphql.ml
src/irmin-test/store.ml
src/irmin-unix/cli.ml
src/irmin/contents.ml
src/irmin/irmin.ml
src/irmin/irmin.mli
src/irmin/s.ml
src/irmin/store.ml
src/irmin/store.mli
test/irmin-git/test_git.ml
test/irmin-unix/test_unix.ml

The function now return a result type, but also add _exn variants which
raise an exception.

irmin: separate set/test_and_set/merge functions to update the store

---

src/irmin-graphql/irmin_graphql.ml

This PR adds a new query named `branches`, which returns a list of available branches.

Add branches field

---

src/irmin-graphql/irmin_graphql.ml

The current GraphQL `set_tree` implementation is confusing because it does something different than `Store.set_tree` in OCaml.
In this PR I've renamed the GraphQL `set_tree` method to `update_tree` and added `set_tree`, which acts as expected for people familiar with the OCaml API.
This means that `set_tree` is now used to replace an entire tree and `update_tree` is used to modify an existing tree.

Add update_tree to GraphQL API

---

src/irmin/type.ml

Fix out of bounds index in Irmin.Type.Decode_json.char

---

src/irmin-chunk/irmin_chunk.ml

Fix build of irmin-chunk

---

src/irmin/type.ml
test/irmin/test.ml

Irmin.Type: fix size_of

---

test/irmin-http/test_http.ml

Seems that things have changed recently if you call dune in dune.

Fix test binary reexec

---

src/irmin/node.ml

Not sure why I thought that using a mutable cell was a good idea...

Fix broken implementation of V1 node serialization

---

src/irmin-git/irmin_git.ml

Remove Ephemerons from memory-based backends

---

src/irmin-chunk/irmin_chunk.ml
src/irmin-git/irmin_git.ml
src/irmin/commit.ml
src/irmin/hash.ml
src/irmin/irmin.mli
src/irmin/node.ml
src/irmin/type.ml
src/irmin/type.mli
test/irmin/test.ml

First patch extracted frim #649

Irmin.Type: encode_bin now takes an (extensible) buffer

---

test/irmin/test.ml

 Irmin.Test: add some tests for the ?headers option

---

src/irmin-chunk/irmin_chunk.ml
src/irmin-git/irmin_git.ml
src/irmin/commit.ml
src/irmin/contents.ml
src/irmin/hash.ml
src/irmin/irmin.mli
src/irmin/merge.ml
src/irmin/node.ml
src/irmin/tree.ml
src/irmin/type.ml
src/irmin/type.mli
test/irmin/test.ml

Also rename Irmin.Type.list_map to Irmin.Type.map
This is extracted (and improved) from #649

Irmin.Type: add the support for custom types (with Irmin.Type.v)

---

src/irmin-test/store.ml
src/irmin/bheap.ml
src/irmin/bheap.mli
src/irmin/irmin.mli
src/irmin/s.ml
src/irmin/store.ml

Should fix #575 by adding 
```val last_modified: ?depth:int -> ?number:int -> t -> key -> commit list Lwt.t```

Add S.last_modified

---

src/irmin-git/irmin_git.ml
src/irmin/irmin.mli

Some typo fixes I've had kicking around on my fork for a while :smiley:

Minor documentation fixes

---

src/irmin-graphql/server.ml

This PR contains a number of changes related to the schema in `irmin-graphql`. It could be split up in multiple PRs, but because the changes are dependent on each other (need to be applied in sequence), I've opted for a single, bigger PR. Hopefully reviewing the commits one by one can help make it more manageable. The commits should work independently if we want to omit one or more of them.
#663 introduced a bug (52f81f723635f5437167f148940952bda1e258ab):
> The source type of Node does not change (`tree * key`), but the semantics change: the tree is now fully resolved to the actual subtree, and the key is only part of the source type to support the `key` field.
Unfortunately the code mixed up relative and absolute keys: Keys used as arguments are relative to the current tree, but keys …

More GraphQL schema refactorings

---

src/irmin/commit.ml
src/irmin/commit.mli
src/irmin/irmin.mli
src/irmin/node.ml
src/irmin/node.mli

/cc @zshipko I think it would be great to include this in the 2.0 release to ease the manipulation of V1 values.

Add V1.{export,import} functions

---

irmin-graphql.opam

Waiting for https://github.com/ocaml/opam-repository/pull/13773 to be merged...

irmin-graphql: Bump graphql-cohttp to 0.12.1

---

src/irmin-test/store.ml
src/irmin/tree.ml

This needs a test exercising the broken path before merging.

Fix Tree.remove

---

CHANGES.md

I'm sure there are certain things I've missed - let me know if you notice anything and I'm happy to make an update!

CHANGES.md for 2.0 release

---

.travis.yml
appveyor.yml
src/irmin-git/irmin_git.ml

See https://github.com/mirage/irmin/issues/658#issuecomment-483468670

Use the development version of ocaml-git

---

src/irmin-mirage/git/irmin_mirage_git.ml

Use Store.last_modified in irmin-mirage-git

---

.travis.yml
appveyor.yml
irmin-git.opam

And simplify the PINS variable in the CI scripts.

irmin-git: add pin-depends

---

src/irmin-unix/resolver.ml
src/irmin/contents.ml
src/irmin/contents.mli
src/irmin/irmin.mli

It is not a good idea to put mutable contents in Irmin.

Remove Irmin.Contents.Bytes

---

src/irmin/tree.ml

And add @tailcall annotations everywhere to avoid this to happen again.

Make all functions in Irmin.Tree tail-rec

---

src/irmin/tree.ml

This was a bad idea, and would cause some objects to not be exported properly.

Irmin.Tree: do not use a global weak table

---

src/irmin/tree.ml

Hi!
In a couple places, `Hashtbl.find` is used only to check for presence.
It is replaced by `mem`, which saves horizontal space and returning the result.
Thanks!

Replace Hashtbl.find (discarding result) by mem

---

src/irmin-pack/bench/dune
src/irmin-pack/bench/pack_bench.ml

/cc @emillon @pascutto 
Ideally this would be a command-line option too, but an env variable will do for now.

irmin-pack: show debug messages when BENCH_VERBOSE is set

---

src/irmin-pack/irmin_pack.ml

A small refactor of the LRU : 
- Functions were wrapped in a `M` module, I don't think it's necessary anymore, plus `find` did a lot of unnecessary exception/option back and forth.
-  `iter` was only used to filter, so I replaced it with a `filter` function.

Pack LRU simplification

---

src/irmin-chunk/irmin_chunk.ml
src/irmin-git/irmin_git.ml
src/irmin-http/irmin_http.ml
src/irmin-pack/irmin_pack.ml
src/irmin/commit.ml
src/irmin/contents.ml
src/irmin/hash.ml
src/irmin/hash.mli
src/irmin/irmin.ml
src/irmin/irmin.mli
src/irmin/node.ml
src/irmin/s.ml
src/irmin/store.ml
src/irmin/type.ml
src/irmin/type.mli
test/irmin-chunk/test.ml
test/irmin-chunk/test_chunk.ml
test/irmin-git/test_git.ml
test/irmin-pack/test_pack.ml
test/irmin/test.ml

irmin.hash: use incremental hashing

---

test/irmin-http/test_http.ml

irmin-unix: really (?) fix the 'call dune-in-dune' issue in tests

---

src/irmin-test/irmin_bench.ml
test/irmin-pack/bench.ml

- Add an init step
- Add a --gc option
- Fix size reporting for irmin-pack benchmarks

Improve benchmarks

---

src/irmin/tree.ml

Use a specialised hashtable and cleanup all the intermediate nodes too.

irmin.tree: improve Tree.export

---

src/irmin-test/store.ml

Aslo add more tests about caching and internal operations.

irmin-tree: separate tests for tree caches in a separate topelvel test

---

src/irmin-pack/irmin_pack.ml

When reading some bits in a file, it's actually fine to read the end of that
file. In that case, simply return the current offset.
/cc @CraigFe 
I am still unsure why the previous bug caused an Out_of_memory -- but in some case, we really want to allow reads to success when done at the end of a file so I believe the previous behaviour to actually be correct.

Partially revert 5269d0364d5a0f404f101f28bfdc3c6c934e8a12

---

src/irmin/tree.ml

Use a simple marking scheme to find all the live elements whitout having
to scan elements mulitple times. That also help to detect which "contents"
leaves are still alive.

irmin.tree: improve Cache.clear when ~depth is set

---

irmin-pack.opam
src/irmin-pack/dune
src/irmin-pack/irmin_pack.ml
src/irmin-pack/irmin_pack.mli
test/irmin-pack/test_pack.ml

Located at https://github.com/mirage/index.

Use the separate index library

---

src/irmin-pack/irmin_pack.ml
src/irmin-pack/irmin_pack.mli
src/irmin-test/store.ml
test/irmin-pack/test_pack.ml

irmin-pack: add a read-only flag

---

src/irmin-pack/irmin_pack.ml

This exposes an IO read and decode function within Pack that bypasses the caching layers imposed by the `unsafe_find` function (and, by extension, the `find` function in the interface).
It might be necessary to expose even deeper than this: the `decode_bin` functions passed to the `Pack` functor throw away the `magic` character without checking that it's consistent. Interested in your opinions on this @samoht  and @pascutto.

irmin-pack: expose low level read function

---

src/irmin-graphql/server.ml
src/irmin/type.ml
src/irmin/watch.ml

@andreas just one question here about the seemingly redundant Lazy force

4.08.0 compat

---

src/irmin/irmin.mli

Fixes a stub heading in the top-level docs and improves the ordering somewhat.

irmin: fix structure of top level documentation

---

src/irmin-pack/inode.ml
src/irmin-pack/inode.mli
src/irmin-pack/irmin_pack.ml
src/irmin-pack/irmin_pack.mli
src/irmin-pack/pack.ml
src/irmin-pack/pack.mli
src/irmin-pack/pack_index.ml
src/irmin-pack/pack_index.mli

This is currently based on #786.

irmin-pack: expose an integrity_check function

---

src/irmin-pack/IO.ml
src/irmin-pack/IO.mli
src/irmin-pack/dict.ml
src/irmin-pack/dict.mli
src/irmin-pack/inode.ml
src/irmin-pack/inode.mli
src/irmin-pack/irmin_pack.ml
src/irmin-pack/lru.ml
src/irmin-pack/lru.mli
src/irmin-pack/pack.ml
src/irmin-pack/pack.mli
src/irmin-pack/pack_dict.ml
src/irmin-pack/pack_index.ml
src/irmin-pack/pack_index.mli
test/irmin-pack/test_pack.ml

Close the content store of a pack.

Close a pack

---

Makefile
test/irmin-http/test_http.ml
test/irmin-http/test_http.mli

irmin-http: make the concurrent tests work a bit more reliably

---

src/irmin-pack/IO.ml

Similar to https://github.com/mirage/index/pull/62

irmin-pack: open files in O_CLOSEXEC mode

---

src/irmin-pack/irmin_pack.mli
test/irmin-pack/test_pack.ml

Expose close in atomic store for testing

---

irmin-chunk.opam
irmin-fs.opam
irmin-git.opam
irmin-graphql.opam
irmin-http.opam
irmin-mem.opam
irmin-mirage-git.opam
irmin-mirage-graphql.opam
irmin-mirage.opam
irmin-pack.opam
irmin-test.opam
irmin-unix.opam
irmin.opam

this allow `opam install .` to work

add 'dev' version in opam files

---

irmin-pack.opam

irmin-pack: remove unused bloomf dependency from opam file

---

test/irmin-pack/common.ml
test/irmin-pack/common.mli
test/irmin-pack/dune
test/irmin-pack/test_pack.ml

This will also allow for a better integration of the concurrent tests in PR #858.

Refactor tests

---

CHANGES.md

This keeps a focus on changes to the API, and ignores quite a few performance improvements / changes under the hood. Perhaps you want to add some references to performance @samoht?
There is also no mention of `irmin-pack` yet.

Update CHANGELOG in preparation for Irmin 2.0

---

appveyor.yml
irmin-git.opam
irmin-graphql.opam
irmin-mirage-git.opam
irmin-mirage-graphql.opam
src/irmin-git/irmin_git.ml

Fixes #816  as soon as https://github.com/mirage/ocaml-git/pull/370 is merged and released.

Add git pp for fetch and push

---

src/irmin/tree.ml

There were some leftover from the removal of ephemerons

Irmin.Tree: more cleanups

---

src/irmin-test/store.ml

In response to https://github.com/mirage/irmin/issues/891

Close repo in all tests

---

irmin-chunk.opam
irmin-fs.opam
irmin-git.opam
irmin-graphql.opam
irmin-http.opam
irmin-mem.opam
irmin-mirage-git.opam
irmin-mirage-graphql.opam
irmin-mirage.opam
irmin-pack.opam
irmin-test.opam
irmin-unix.opam
irmin.opam

See https://github.com/samoht/dune-release/issues/189 for a rational

Remove custom version fields in opam files

---

src/irmin-pack/dict.ml
src/irmin-pack/irmin_pack.ml
src/irmin-pack/pack.ml

Similar to https://github.com/mirage/index/pull/104.

irmin-pack: Rename `counter` to `open_instances`

---

.gitignore

As in https://github.com/mirage/index/pull/149

Ignore macos generated files

---

.ocamlformat
examples/custom_graphql.ml
src/irmin-chunk/irmin_chunk.ml
src/irmin-git/irmin_git.ml
src/irmin-http/irmin_http_common.ml
src/irmin-pack/inode.ml
src/irmin-test/irmin_bench.ml
src/irmin-test/store.ml
src/irmin-unix/resolver.ml
src/irmin/commit.ml

I propose we use this option as I find it leads to clearer code than the current default for the conventional profile.

Use OCamlformat option: break-infix = fit-or-vertical

---

CHANGES.md
src/irmin/irmin.mli
src/irmin/node.ml
src/irmin/object_graph.ml
src/irmin/object_graph.mli
src/irmin/s.ml

To apply the changes suggested in https://github.com/mirage/irmin/pull/912

Refactor iter

---

src/irmin-test/store.ml
src/irmin/object_graph.ml

A small fix forgotten in https://github.com/mirage/irmin/pull/920

Small fix in closure

---

src/irmin-test/store.ml

This a test on merging commits that should fail, as the merge should not remove the `/u/x/y` path. I'm marking this as WIP until I propose a fix for it.

Merge commits test

---

.travis.yml
irmin-unix.opam
ppx_irmin.opam

Also, Irmin is under ISC licence, maybe that should also be unified?

Fix ppx_irmin opam file

---

README.md
examples/readme.ml

See https://github.com/mirage/irmin/issues/985#issuecomment-612837444. A better long-term solution is tracked by https://github.com/mirage/irmin/issues/986.

Update the README to use set_exn rather than set

---

src/irmin/node.ml
src/irmin/s.ml

Supercedes https://github.com/mirage/irmin/pull/1007.
Depends on https://github.com/mirage/irmin/pull/1022 (unmerged).

Generalise Graph.iter to also iterate over contents

---

Makefile
bench/irmin/dune
bench/irmin/main.ml
bench/irmin/main.mli
irmin-bench.opam
test/irmin-mem/dune
test/irmin-pack/dune

This is a rebased/updated variant of https://github.com/mirage/irmin/pull/728, with a new `opam` file to ensure that these compile in CI.
I think these can now be considered for merge, and we can improve on them in future iterations.

Benchmarks for Irmin.Type

---

CHANGES.md
src/irmin-pack/lru.ml

5dccbabd1dd7527e59447991ec28abb3992f057b introduced a feature to select the LRU size. However it also introduced a major regression as it becames impossible to add any entry to the LRU...

irmin-pack: Fix Lru.add

---

src/irmin-pack/closeable.ml
src/irmin-pack/lru.ml
src/irmin-pack/lru.mli
src/irmin-pack/pack.ml
src/irmin-pack/pack.mli
test/irmin-pack/common.ml
test/irmin-pack/common.mli
test/irmin-pack/test.ml
test/irmin-pack/test_pack.ml
test/irmin-pack/test_pack.mli

This seems to expose an underlying bug (or an issue with the tests)

pack: clear the LRU cache

---

test/irmin-http/test_http.ml

irmin-http: Ensure PID files are created atomically in the tests

---

.travis.yml
Makefile
bench/irmin/dune
bench/irmin/main.ml
bench/irmin/output.ml
bench/irmin/output.mli
bench/irmin/process/main.py
irmin-bench.opam

... dropping the dependency on Notty in favour of something more panda-friendly.

irmin-bench: use a JSON output format

---

bench/irmin/dune
bench/irmin/main.ml
irmin-bench.opam

Some small changes added to the `Type` benchmarks while collecting latest [graphs](https://github.com/CraigFe/irmin-notebooks/blob/main/Types.ipynb).

Additional benchmarks for Irmin.Type

---

irmin-pack.opam
src/irmin-pack/pack_index.ml

Small change to fix compilation with index master.

Irmin pack compiles with index

---

src/irmin-layers/layered_store.ml
src/irmin-pack/IO.ml
src/irmin-pack/irmin_pack_layers.ml
src/irmin-pack/layered_store.ml
src/irmin-pack/pack.ml
src/irmin-pack/store.ml
src/irmin/commit.ml
src/irmin/node.ml
src/irmin/object_graph.ml
src/irmin/store.ml

Trying to turn a few verbose lines into something a bit more compact.

Improve log outputs

---

src/irmin-pack/IO.ml
src/irmin-pack/IO.mli
src/irmin-pack/checks.ml
src/irmin-pack/irmin_pack.ml
src/irmin-pack/irmin_pack.mli
src/irmin-pack/irmin_pack_layers.ml
src/irmin-pack/layout.ml
src/irmin-pack/layout.mli
src/irmin-pack/pack.ml
src/irmin-pack/pack_dict.ml
src/irmin-pack/store.ml
test/irmin-pack/bench.ml
test/irmin-pack/bench_layers.ml

More basic refactoring, towards a somewhat cleaner implementation of the Irmin CLI.

irmin-pack: define store names in a central Layout module

---

src/irmin-pack/checks.ml
src/irmin-pack/checks_intf.ml
test/irmin-pack/cli/irmin-fsck-help.txt

Based on https://github.com/mirage/irmin/pull/1139 for convenience.

irmin-pack/checks: expose Cmdliner terms for each of the operations

---

src/irmin-layers/irmin_layers.ml
src/irmin-layers/irmin_layers_intf.ml
src/irmin-pack/irmin_pack_layers.ml
src/irmin-test/layered_store.ml
test/irmin-pack/layered.ml

The PR is not passing tests right now:
```
[FAIL]        LAYERED_PACK            20   Keep max and heads after max.
```

irmin-pack: remove unused heads argument

---

examples/custom_graphql.ml

the year was saved as a "license"

use year instead of license per year

---

src/irmin-test/store.ml

Probably not worth merging right now, I'll add a few more tests first.

irmin-tests: test hashing for nodes and trees

---

src/irmin-pack/inode_layers_intf.ml
src/irmin-pack/irmin_pack_layers.ml
src/irmin-pack/layered_store.ml
src/irmin-pack/pack_intf.ml

irmin-pack: remove global state

---

test/irmin-mem/test.ml
test/irmin-mem/test_mem.ml
test/irmin/test_tree.ml

See https://github.com/mirage/irmin/pull/1171#issuecomment-740198682

move Tree.clear tests at the right place

---

CHANGES.md
src/irmin/tree.ml

Spotted by @Ngoguey42
It would be good to add a test-case for this, I'll add an issue to track this.

Fix Tree.fold

---

src/irmin-test/common.ml
src/irmin-test/dune
src/irmin-test/store.ml
src/irmin-test/store.mli
src/irmin-test/store_graph.ml
src/irmin-test/store_graph.mli
src/irmin-test/store_watch.ml
src/irmin-test/store_watch.mli

This file is getting unweildy, especially with upcoming changes like https://github.com/mirage/irmin/pull/1122.

irmin-test: extract graph and watch tests to separate files

---

src/irmin-pack/pack.ml
src/irmin-pack/pack_intf.ml
src/irmin-pack/store.ml

This doesn't seem to be necessary.

irmin-pack: remove pack locks

---

src/irmin-pack/irmin_pack_layers.ml

The result is:
```
time dune exec -- ./bench/irmin-pack/layers.exe -n 1000 -v                     thomas@Koob
Running benchmarks in bench/irmin-pack/layers.ml:
{ ncommits = 1000;
ncycles = 10;
depth = 10;
root = "test-bench";
clear = false;
no_freeze = false;
show_stats = false;
freeze_throttle = Block_writes }
+1607623151us [INFO] application exec: rm -rf test-bench
+1607623151us [INFO] index [upper1] v fresh=true readonly=false log_size=2000000
+1607623151us [INFO] index [upper0] v fresh=true readonly=false log_size=2000000
+1607623154us [INFO] irmin-pack freeze started { id=1; max=512464f1ffadf77d8b8e86b48a9001d06726e00e; min_upper=2a6c50e554a5b4da64af00fc1f32f7ca07ab5a4e; }
+1607623162us [INFO] irmin-pack freeze { id=1; waiting=35.463us; duration=7.678s }
+1607623162us [INFO] …
```

irmin-pack: better freeze info messages

---

src/irmin-test/store_graph.ml

Tests written by @icristescu, extracted from #1122

tests: add more graphs to test iter

---

bench/irmin-pack/dune
irmin-chunk.opam
irmin-fs.opam
irmin-git.opam
irmin-graphql.opam
irmin-http.opam
irmin-layers.opam
irmin-mem.opam
irmin-mirage-git.opam
irmin-mirage-graphql.opam
irmin-pack.opam
irmin-test.opam
irmin-unix.opam

Found by https://github.com/ocurrent/opam-dune-lint

Add missing direct dependencies

---

src/irmin-pack/layered_store.ml

Similar to #1155 but for banches.

irmin-pack: remove global state for branch newies and implement removal

---

irmin-pack.opam
src/irmin-pack/closeable.ml
src/irmin-pack/inode.ml
src/irmin-pack/inode_layers.ml
src/irmin-pack/layered_store.ml
src/irmin-pack/pack.ml
src/irmin-pack/pack_index.ml
src/irmin-pack/pack_index.mli
src/irmin-pack/pack_intf.ml
test/irmin-pack/test_pack.ml

Depends on https://github.com/mirage/index/pull/253

Use force merge at the end of freeze

---

bench/irmin-pack/layers.ml
src/irmin-pack/config.ml
src/irmin-pack/config.mli
src/irmin-pack/ext.ml
src/irmin-pack/irmin_pack.ml
src/irmin-pack/irmin_pack.mli
src/irmin-pack/irmin_pack_layers.ml

Fix #1172
On top of #1190 
The result:
```
» time dune exec -- ./bench/irmin-pack/layers.exe -n 1000 -v --freeze-throttle=cancel-existing
Running benchmarks in bench/irmin-pack/layers.ml:
{ ncommits = 1000;
ncycles = 10;
depth = 10;
root = "test-bench";
clear = false;
no_freeze = false;
show_stats = false;
freeze_throttle = Cancel_existing }
+1607624817us [INFO] application exec: rm -rf test-bench
+1607624817us [INFO] index [upper1] v fresh=true readonly=false log_size=2000000
+1607624817us [INFO] index [upper0] v fresh=true readonly=false log_size=2000000
+1607624821us [INFO] irmin-pack freeze started { id=1; max=d6e260afc48483aaa50547b09ac2071704931568; min_upper=27e86e2486477fd8f2e06765224351a7e1da9f80; }
+1607624822us [INFO] irmin-pack cancelled freeze { id=1; waiting=34.452us; …
```

irmin-pack; add an option to cancel existing freeze instead of blocking

---

src/irmin-layers/irmin_layers_intf.ml

A docstring for `freeze`! 
It took me quite a while to fully infer the behaviour so it might be helpful to someone else. Please tell me if I understood something wrong.
I've made some assumptions that might be specific to `irmin-pack`, i.e. `copy_in_upper` defaults to the repo's config, there is a concept of `freeze_throttle`...
Don't hesitate to nitpick on my code.

Freeze documentation

---

src/irmin-pack/inode.ml

This could be a big optimisation. 
I don't know how to plot fancy benchmark png yet. I will try to include those in the comments below.
Make sure you tick the `Hide whitespace changes` when viewing the diff.

Less calls to find_value in inode

---

src/irmin-pack/inode.ml
src/irmin-pack/inode_intf.ml
src/irmin-pack/irmin_pack.ml
src/irmin-pack/irmin_pack.mli
test/irmin-pack/common.ml
test/irmin-pack/common.mli
test/irmin-pack/dune
test/irmin-pack/test_inode.ml
test/irmin-pack/test_inode.mli
test/irmin-pack/test_pack.ml

Rebased over https://github.com/mirage/irmin/pull/1232.

Some tests for inodes

---

src/irmin-test/common.ml

irmin-test: re-raise exceptions with correct backtraces

---

src/irmin-pack/layered/irmin_pack_layered.ml

Since `copy_newies` supports `cancel` but the parameter is never passed it, I guess it's an oversight.

Pass cancel to copy_newies_to_next_upper

---

src/irmin-pack/layered/irmin_pack_layered.ml

Make freeze's `.ml` documentation more verbose

Edit freeze comments

---

src/irmin-pack/inode.ml
src/irmin-pack/inode_intf.ml
src/irmin-pack/layered/inode_layers.ml
test/irmin-pack/test_inode.ml

This is a simplification for `inode_intf`.
To be used as a basis for #1249 and #1251

3rd inode refactor

---

src/irmin-pack/inode.ml
test/irmin-pack/test_inode.ml

The goal of this PR is to reflect in the types the inode structure in order to remove the `assert false` statements, to save memory and to make the code more explicit on edge cases.
I did not re-implement the runtime types in `Val_impl`. I felt it was very redundant with the ones in `Bin.t`.

Inode type adapts to the situation

---

.ocamlformat
examples/process.ml
src/irmin/object_graph.ml

This is a preview of the not-yet-released ocamlformat.0.17.0, please wait until the package is published in opam to merge this PR.

Preview: upgrade to ocamlformat.0.17.0

---

src/irmin/tree.ml

irmin: Normalise and improve the Dangling_hash handling in tree

---

CHANGES.md
src/irmin-http/closeable.ml
src/irmin-http/closeable.mli
src/irmin-http/irmin_http.ml
src/irmin-http/s.ml
src/irmin/atomic_write_intf.ml
src/irmin/content_addressable_intf.ml
src/irmin/irmin.ml
src/irmin/irmin.mli
src/irmin/read_only.ml
src/irmin/read_only.mli
src/irmin/read_only_intf.ml

Also fix store names in irmin-http's clients.
On top of #1342

irmin: add signatures for read-only stores and use this in irmin-http

---

CHANGES.md
src/irmin-git/content_addressable.ml
src/irmin-git/irmin_git.ml
src/irmin-http/irmin_http.ml
src/irmin-http/s.ml
src/irmin-layers/irmin_layers.ml
src/irmin-layers/layered_store.ml
src/irmin-layers/layered_store.mli
src/irmin-pack/inode_intf.ml
src/irmin-pack/pack_intf.ml
src/irmin/append_only_intf.ml
src/irmin/atomic_write_intf.ml
src/irmin/commit.ml
src/irmin/content_addressable_intf.ml
src/irmin/contents.ml
src/irmin/node.ml
src/irmin/read_only_intf.ml
test/irmin-chunk/test_chunk.ml

irmin: extend backend stores with close and batch

---

dune

Cherry-picked from https://github.com/mirage/irmin/pull/1364.

Register vendors/ dir with Dune

---

src/irmin-pack/checks.ml
src/irmin-pack/ext.ml
src/irmin-pack/layered/checks.ml
src/irmin-pack/layered/conf.ml
src/irmin-pack/layered/conf.mli
src/irmin-pack/layered/ext_layered.ml
src/irmin-pack/layered/ext_layered.mli
src/irmin-pack/layered/irmin_pack_layered.ml
src/irmin-pack/layered/layered_store.ml

Less opens

---

src/irmin-pack/ext.ml
src/irmin-pack/irmin_pack.ml
src/irmin-pack/irmin_pack.mli
src/irmin-pack/layered/ext_layered.ml
src/irmin-pack/migrate.ml
src/irmin-pack/migrate.mli
src/irmin-pack/store.ml
src/irmin-pack/store_intf.ml

irmin-pack: move migration code to its own file

---

CHANGES.md
bench/irmin-pack/dune
bench/irmin-pack/trace_common.ml
bench/irmin-pack/trace_definitions.ml
bench/irmin-pack/tree.ml

on top of #1357, extracted from #1332

irmin-bench: Factorised replayable trace

---

CHANGES.md
bench/irmin-pack/dune
bench/irmin-pack/trace_collection.ml
bench/irmin-pack/trace_common.ml
bench/irmin-pack/trace_definitions.ml
bench/irmin-pack/tree.ml
irmin-bench.opam

extracted from #1332 
The summary and pretty printing are gone for now. They will come back, I promise.

irmin-bench: Factorised stat trace

---

CHANGES.md
bench/irmin-pack/bench_common.ml
bench/irmin-pack/bench_common.mli
bench/irmin-pack/dune
bench/irmin-pack/trace_definitions.ml
bench/irmin-pack/tree.ml

extracted from #1332 
Series of small normalisations on the CLI arguments, before bringing back the summary 🥳

irmin-bench: improve CLI

---

CHANGES.md
bench/irmin-pack/dune
bench/irmin-pack/trace_collection.ml
bench/irmin-pack/trace_common.ml
bench/irmin-pack/trace_definitions.ml
bench/irmin-pack/tree.ml

irmin-bench: Small improvements in tree.exe

---

irmin-pack.opam

index master might contain a fix (https://github.com/mirage/index/commit/bdf766f1145b9aaf16679cb87035e91bd3013ca0) for https://github.com/mirage/irmin/issues/1245.

Update pin on index

---

CHANGES.md
irmin-git.opam
src/irmin-git/irmin_git.ml
src/irmin-pack/inode.ml
src/irmin-pack/inode_intf.ml
src/irmin/node.ml
src/irmin/node_intf.ml
src/irmin/tree.ml
test/irmin-pack/test_inode.ml

Prepare 2.5.4

---

CHANGES.md
irmin-git.opam
irmin-http.opam
irmin-mirage-git.opam
irmin-mirage-graphql.opam
irmin-unix.opam
src/irmin-chunk/irmin_chunk.ml
src/irmin-git/irmin_git.ml
src/irmin-mirage/git/dune
src/irmin-mirage/git/irmin_mirage_git.ml
src/irmin-pack/inode.ml
src/irmin-test/irmin_test.mli
src/irmin-test/store.ml
src/irmin-test/store.mli
src/irmin/import.ml
src/irmin/tree.ml
src/irmin/tree_intf.ml
test/irmin-chunk/test.ml
test/irmin-fs/test.ml
test/irmin-git/test.ml
test/irmin-http/test.ml
test/irmin-mem/test.ml
test/irmin-unix/test.ml
test/irmin/test_tree.ml

2.6.0 contains the bugfixes currently in `master` + the upgrade to Git.3.4.0.

Prepare 2.6.0 release

---

CHANGES.md
src/irmin-graphql/server.ml
test/irmin-graphql/test.ml

Adds last_modified field to graphql api

---

RELEASE.md

Proposed workflow for manual benchmarking of releases

Update RELEASE.md about manual benchmarking

---

src/irmin-pack/content_addressable.ml
src/irmin-pack/ext.ml
src/irmin-pack/inode.ml
src/irmin-pack/inode_intf.ml
src/irmin-pack/layered/inode_layers.ml
src/irmin-pack/pack_value.ml
src/irmin-pack/pack_value_intf.ml
src/irmin-pack/reconstruct_index.ml
test/irmin-pack/common.ml

More refactoring from https://github.com/mirage/irmin/pull/1436.
Depends on https://github.com/mirage/irmin/pull/1455.

irmin-pack: extract index reconstruction logic

---

src/irmin-pack/s.ml

Replace anonymous modules with named ones

---

CHANGES.md
Makefile
bench/irmin-pack/dune
bench/irmin-pack/layers.ml
bench/irmin-pack/trace_stat_summary.ml
bench/irmin-pack/trace_stat_summary_cb.ml
bench/irmin-pack/trace_stat_summary_pp.ml
bench/irmin-pack/trace_stat_summary_utils.ml
bench/irmin-pack/trace_stat_summary_utils.mli
bench/irmin-pack/trace_stats.ml
bench/irmin-pack/tree.ml
irmin-bench.opam

irmin-bench: Trace replay summary in CB

---

irmin-pack.opam
irmin.opam
src/irmin-chunk/dune
src/irmin-chunk/irmin_chunk.ml
src/irmin-git/content_addressable.ml
src/irmin-pack/atomic_write.ml
src/irmin-pack/dict.ml
src/irmin-pack/inode.ml
src/irmin-pack/pack_index.ml
src/irmin/commit.ml
src/irmin/hash.ml
src/irmin/info.ml
src/irmin/tree.ml

This PR demonstrates the feature proposed in https://github.com/mirage/repr/pull/64.

Use `ppx_repr` generic expansion feature

---

README.md

Update ReadMe: Formatting & Syntax

---

CHANGES.md

as suggested by https://github.com/mirage/irmin/pull/1490#issuecomment-890489443.

Update changelog with latest release

---

src/irmin-pack/IO.ml
src/irmin-pack/inode.ml
src/irmin/tree.ml

Similar to https://github.com/mirage/index/pull/336.

Avoid flaky usage of [@tailcall]

---

src/irmin-test/common.ml
src/irmin-test/irmin_bench.ml
src/irmin-test/irmin_test.mli
test/irmin-chunk/test_chunk.ml
test/irmin-fs/test_fs.ml
test/irmin-git/test_git.ml
test/irmin-git/test_git.mli
test/irmin-http/test_http.ml
test/irmin-http/test_http.mli
test/irmin-mem/test_mem.ml
test/irmin-pack/test_pack.ml
test/irmin-pack/test_pack.mli
test/irmin-unix/test_unix.ml
test/irmin-unix/test_unix.mli

... and avoid unnecessarily exposing the `Common` unit.

irmin-test: make the core suite type abstract

---

CHANGES.md
src/irmin/tree.ml

Do not build intermediate lists as we just want to iterate over them.

irmin: better clear

---

src/irmin/tree.ml

While I was reading the code of `tree.ml`, I saw that we define a function, `ok` equivalent to ` Lwt.return_ok`, at the beginning of the file but, then we use three different syntaxes: `Lwt.return_ok`, `ok` and, `Lwt.return Ok`.
This small PR is just here to replace all the occurrences with the `ok` syntax :smile:

Standardize tree.ml calls to ok

---

bench/irmin-pack/bench_common.ml
bench/irmin-pack/dune
src/irmin-unix/dune
src/irmin-unix/resolver.ml
test/irmin-bench/replay.ml
test/irmin-pack/common.ml
test/irmin-pack/dune
test/irmin-pack/layered.ml
test/irmin-pack/multiple_instances.ml

Fix https://github.com/mirage/irmin/issues/1584.

irmin-pack: avoid unnecessary duplication of the Tezos config

---

src/irmin-pack/IO.ml

irmin-pack: more descriptive failure when reading an incorrect IO offset

---

bench/irmin-pack/bench_common.ml
bench/irmin-pack/bench_common.mli
bench/irmin-pack/layers.ml
bench/irmin-pack/trace_collection.ml
bench/irmin-pack/trace_replay.ml
bench/irmin-pack/trace_replay_intf.ml
bench/irmin-pack/tree.ml

irmin-pack: support generic-keyed stores in replay

---

test/irmin-pack/test_inode.ml

These tests currently use a pair of unreachable contents values to form leaves of test inodes. This works fine while keys are hashes, but will break when #1534 introduces a structured key type to `irmin-pack`. It's more correct to add the contents values to the store and reference them by key.

irmin-pack: refactor inode tests to not use unfindable contents keys

---

CHANGES.md
src/irmin-test/store.ml
src/irmin/tree.ml
src/irmin/tree_intf.ml

irmin: better signature for Tree.length

---

irmin-unix.opam
src/irmin-unix/resolver.ml

Same as #1678 but for the main branch

Add tezos store type to resolver.ml

---

CHANGES.md
src/irmin-git/irmin_git.ml
src/irmin-pack/inode.ml
src/irmin/node.ml
src/irmin/node_intf.ml
src/irmin/proof.ml
src/irmin/tree.ml
src/irmin/tree_intf.ml
test/irmin/test_tree.ml

[2.10] irmin: simplify the API of proof streams

---

src/irmin-git/atomic_write.ml

This avoids a warning when running the Irmin CLI example in the README:
```diff
$ echo "root: ." > irmin.yml
$ irmin init
$ irmin set foo/bar "testing 123"
-irmin: [ERROR] Reference refs/heads/main not found.
$ irmin get foo/bar
testing 123
```

irmin-git: fix spurious warning when writing to a new branch

---

src/irmin-pack/irmin_pack_intf.ml
test/irmin-pack/common.ml
test/irmin-pack/common.mli
test/irmin-pack/dune
test/irmin-pack/test_existing_stores.ml
test/irmin-pack/test_pack.ml
test/irmin-pack/test_pack_version_bump.ml
test/irmin-pack/test_pack_version_bump.mli

This for Irmin issue #1658 
Resolves #1658.

Tests for issue #1658 "test migration of pack stores from V1 to V2"

---

irmin-http.opam

Fixes issues uncovered by #1637 and https://github.com/ocaml/opam-repository/pull/20402

opam fixes

---

CHANGES.md
src/irmin-pack/ext.ml
src/irmin-pack/inode.ml
src/irmin-pack/inode_intf.ml
src/irmin/store_intf.ml

irmin-pack: More security on inode depth

---

CHANGES.md
src/irmin-git/node.ml
src/irmin-pack/ext.ml
src/irmin-pack/inode.ml
src/irmin-pack/inode_intf.ml
src/irmin/node.ml
src/irmin/node_intf.ml
src/irmin/store_intf.ml

Forward port of 2.10. Extracted from #1692 and #1670

Recursive nodes

---

CHANGES.md
src/irmin-git/node.ml
src/irmin-pack/inode.ml
src/irmin-pack/inode_intf.ml
src/irmin/node.ml
src/irmin/node_intf.ml

Forward port from #1583 .
Inspired from #1606 .

Proof in nodes

---

test/irmin-pack/test_pack.ml

Changes the `irmin-pack` test suite instantiation to test multiple choices for the following configuration options:
- ``indexing_strategy = always | minimal`` (as before)
- ``entries = 2 | 32``
- ``stable_hash = 3 | 256``
- ``contents_length_header = None | Some `Varint``
- ``inode_child_order = `Hash_bits | `Seeded``
This should provide better coverage overall.

irmin-pack: improve test suite coverage of Conf values

---

src/irmin-pack/inode.ml

- rename the cases of `Compress.address` to avoid ambiguity about what a "direct" address is (`Direct` is now `Hash`, and `Indirect` is now `Offset`).
- document `Compress.value_t` and manually format it to highlight the symmetries between different cases.

irmin-pack: refactor Inode.Compress types for clarity

---

CHANGES.md
src/irmin/tree.ml
src/irmin/tree_intf.ml

Type changes forward ported from #1583

irmin: Improve error handling in Tree

---

src/irmin/tree.ml

based on #1744
Fixes a series of small problems in tree that were not released yet.

irmin: Improve cache usage in Tree

---

CHANGES.md
src/irmin-git/node.ml
src/irmin-pack/inode.ml
src/irmin-pack/inode_intf.ml
src/irmin/node.ml
src/irmin/node_intf.ml
src/irmin/tree.ml
test/irmin-pack/test_inode.ml

Forward ports from #1741
2 commits on top of #1747

New hash_exn function

---

CHANGES.md
examples/custom_graphql.ml
src/irmin-graphql/server.ml
src/irmin-graphql/server.mli
src/irmin-unix/cli.ml
src/irmin-unix/graphql.ml
src/irmin-unix/graphql.mli
test/irmin-graphql/common.ml
test/irmin-graphql/common.mli
test/irmin-graphql/test.ml

Since irmin-graphql isn’t very well tested, it would probably be worthwhile to include some additional tests before considering this PR ready.

Support Irmin.Generic_key.S in irmin-graphql

---

CHANGES.md

Corresponding `opam-repository` PR: https://github.com/ocaml/opam-repository/pull/20628.
Closes #1731.

Release 2.10.2

---

src/irmin/tree.ml

Shipping that feature alone without the rest of the proofs simplifies a lot my git life :-)
It contains half of the modifications on tree.ml caused by the proofs (the other half is the portable tag). 
When an irmin function has trees in both negative and positive position, the positive one(s) should inherit the env of the negative one.
I suspect that the sharing is not perfect at the moment (maybe even bugged), I will investigate and improve this is a later PR, this one strictly a forward port from #1625.

irmin: Trees carry a placeholder proof env

---

src/irmin-test/store.ml
src/irmin/node.ml
src/irmin/node_intf.ml
src/irmin/tree.ml
src/irmin/tree_intf.ml
test/irmin/test_tree.ml

irmin: Portable in tree

---

CHANGES.md
src/irmin/store.ml
src/irmin/store_intf.ml

Forward-ported from #1625 
Merge when green

irmin: Add the `Store.Tree.kinded_hash` function

---

CHANGES.md
src/irmin-unix/cli.ml
src/irmin-unix/resolver.ml
src/irmin-unix/resolver.mli
test/irmin-unix/test_command_line.t

irmin-unix: Fix issues with commands that use the remote term

---

CHANGES.md
irmin-bench.opam
irmin-git.opam
libirmin.opam

Corresponding opam PR https://github.com/ocaml/opam-repository/pull/21038

Release 3.2.0

---

CHANGES.md
bench/irmin-pack/trace_collection.ml
src/irmin-pack/stats.ml
src/irmin-pack/stats.mli
src/irmin-pack/unix/import.ml
src/irmin-pack/unix/irmin_pack_unix.ml
src/irmin-pack/unix/pack_store.ml
src/irmin-pack/unix/stats.ml
src/irmin-pack/unix/stats.mli
src/irmin/irmin.ml
src/irmin/irmin.mli
src/irmin/metrics.ml
src/irmin/metrics.mli
test/irmin-bench/replay.ml

* This introduces a new module `Metrics` to describe metrics
* It updates the old `stat.ml` interface to support this new style.

Introduce the new stats interface

---

CHANGES.md

Corresponding opam PR https://github.com/ocaml/opam-repository/pull/21377

Release 3.2.2

---

src/irmin-test/store.ml
src/irmin/tree.ml
src/irmin/tree_intf.ml

Revert "Add `Tree.is_val` and `Tree.Contents.is_val` functions"

---

src/irmin-pack/unix/append_only_file.ml
src/irmin-pack/unix/ext.ml
src/irmin-pack/unix/file_manager.ml
src/irmin-pack/unix/file_manager_intf.ml
src/irmin-pack/unix/io.ml
src/irmin-pack/unix/io_intf.ml

This PR targets the GC branch.
This addresses @tomjridge comments left in the code

GC: Diffs on io

---

src/irmin-pack/unix/dict.ml
src/irmin-pack/unix/file_manager.ml
src/irmin-pack/unix/file_manager_intf.ml
src/irmin-pack/unix/pack_store.ml

Add callbacks in file manager

---

src/irmin-pack/unix/ext.ml
src/irmin-pack/unix/pack_store.ml

~This doesn't seem to fix any UT~ It fixes some UTs

Add back close checks

---

CHANGES.md
src/irmin-git/backend.ml
src/irmin-git/irmin_git.ml
src/irmin-http/irmin_http.ml
src/irmin-pack/mem/irmin_pack_mem.ml
src/irmin-pack/unix/ext.ml
src/irmin/backend.ml
src/irmin/irmin.ml
src/irmin/store.ml
src/irmin/store_intf.ml

- Exposes `Repo.config` to access the `Conf.t` that was passed to `Repo.v`

Add Repo.config

---

src/irmin/store_intf.ml

docs: fix typos

---

src/irmin-pack/unix/pack_index_intf.ml

required here https://gitlab.com/tezos/tezos/-/blob/master/src/lib_context/disk/context.ml#L280

Expose Index.Checks

---

CHANGES.md
src/irmin-pack/conf.ml

this is for all changes in https://github.com/mirage/irmin/pull/1865 but without https://github.com/mirage/irmin/pull/1885

WIP: Update changelog

---

src/irmin/tree.ml
src/irmin/tree_intf.ml

docs: add documentation for `Tree.inspect`

---

test/irmin-pack/dune
test/irmin-pack/test_gc.ml
test/irmin-pack/test_gc.mli
test/irmin-pack/test_pack.ml

Adding back the tests written for the layered store.
Based on #1885

Add tests for blocking gc

---

src/irmin-pack/indexing_strategy.ml
src/irmin-pack/inode.ml
src/irmin-pack/pack_value.ml
src/irmin-pack/pack_value_intf.ml
src/irmin-pack/unix/checks.ml
src/irmin-pack/unix/gc.ml
src/irmin-pack/unix/pack_store.ml
src/irmin-pack/unix/snapshot.ml
src/irmin-pack/unix/traverse_pack_file.ml
test/irmin-pack/test_gc.ml

based on https://github.com/mirage/irmin/pull/1905

Dangling parent of commits on which gc is called

---

src/irmin-pack/unix/io.ml

Context: https://github.com/mirage/irmin/pull/1932#discussion_r905411127

irmin-pack: document `IO.Unix.close` implementation

---

src/irmin-pack/unix/file_manager.ml
src/irmin-pack/unix/stats.ml
src/irmin-pack/unix/stats.mli

Replaces #1912 
Rebased on main

Add new file_manager stats

---

bench/irmin-pack/trace_replay.ml
bench/irmin-pack/trace_replay_intf.ml
bench/irmin-pack/tree.ml
src/irmin-pack/layout.ml
src/irmin-pack/mem/irmin_pack_mem.ml
src/irmin-pack/s.ml
src/irmin-pack/unix/errors.ml
src/irmin-pack/unix/errors_base.ml
src/irmin-pack/unix/ext.ml
src/irmin-pack/unix/file_manager.ml
src/irmin-pack/unix/file_manager_intf.ml
src/irmin-pack/unix/gc.ml
test/irmin-bench/replay.ml
test/irmin-pack/test_gc.ml
test/irmin-pack/test_snapshot.ml
test/irmin-pack/test_upgrade.ml

Once https://github.com/mirage/irmin/pull/1908 is merged, I'll rebase this over it and create a new branch. 
I'm not sure about the hooks - in index we use them (with semaphores) to pause the merge thread and simulate interleaving between threads (for instance in https://github.com/mirage/index/blob/main/test/unix/force_merge.ml#L355). I'm not sure how we will do this with processes.

Non blocking dummy gc

---

test/irmin-pack/test_gc.ml

Add tests for non blocking gc

---

src/irmin-pack/unix/file_manager.ml

irmin-pack: Fix assert failure in file_manager (callback called before initialization complete)

---

bench/irmin-pack/tree.ml
src/irmin-pack/mem/irmin_pack_mem.ml
src/irmin-pack/s.ml
src/irmin-pack/unix/ext.ml
test/irmin-bench/replay.ml
test/irmin-pack/test_gc.ml
test/irmin-pack/test_gc.mli
test/irmin-pack/test_pack.ml
test/irmin-pack/test_snapshot.ml
test/irmin-pack/test_upgrade.ml

Closes https://github.com/mirage/irmin/issues/1978

irmin-pack: remove throttle option from gc start

---

bench/irmin-pack/bench_common.ml
src/irmin-pack/unix/ext.ml
src/irmin-pack/unix/file_manager.ml

Initial patch from @icristescu

irmin-pack: add debug logs and timestamps for GC & batches

---

examples/dune
examples/gc.ml
src/irmin-pack/conf.mli
src/irmin-pack/irmin_pack_intf.ml

This PR adds configuration documentation and an example for the new GC feature in `irmin-pack` for issue #1960.

irmin-pack: configuration docs + example for gc

---

examples/gc.ml
src/irmin-pack/mem/irmin_pack_mem.ml
src/irmin-pack/s.ml
src/irmin-pack/unix/ext.ml

This PR closes #2023. I also did some clean up while in this area of the code.

irmin-pack: add finalisation_duration gc stat

---

bench/irmin-pack/trace_replay.ml
bench/irmin-pack/trace_replay_intf.ml
bench/irmin-pack/tree.ml
test/irmin-bench/replay.ml

This PR updates benchmarks to use the high-level gc api.

bench: use high-level gc api for replays

---

src/irmin-pack/inode.ml

Memtrace seems to show that lazy values are putting a lot of pressure
on the GC. Let's try to see if this is better with a few changes.

irmin-pack: remove allocations from lazy values

---

src/irmin-graphql/server.ml

Fix schema for GraphiQL interface

---

src/irmin-pack/atomic_write.ml
src/irmin-pack/indexable.ml
src/irmin-pack/indexable_intf.ml
src/irmin-pack/unix/pack_store.ml
src/irmin/atomic_write.ml
src/irmin/atomic_write_intf.ml
src/irmin/indexable.ml
src/irmin/indexable_intf.ml

- Address a couple of `FIXME` comments by removing code duplication in `irmin-pack`
- Update code for consistency after refactor

irmin-pack: remove code duplication in Indexable and Atomic_write

---

CHANGES.md

I'm not sure what all should (or should not) be included for such a large feature introduction but started this as a point of discussion for feedback.

Add irmin-pack GC to changelog

---

CHANGES.md

Add irmin-pack GC API to changelog

---

src/irmin-pack/unix/append_only_file_intf.ml
src/irmin-pack/unix/async.ml
src/irmin-pack/unix/control_file_intf.ml
src/irmin-pack/unix/dispatcher.ml
src/irmin-pack/unix/file_manager.ml
src/irmin-pack/unix/file_manager_intf.ml
src/irmin-pack/unix/mapping_file.ml
src/irmin-pack/unix/mapping_file_intf.ml

irmin-pack: Cleanups in the file stack

---

src/irmin-graphql/server.mli
src/irmin-graphql/unix/irmin_graphql_unix.mli

Improve constraints for GraphQL IO module

---

CHANGES.md

Forgot to add this before merging :see_no_evil:

Update changelog for #2084

---

test/irmin-pack/dune
test/irmin-pack/test_dispatcher.ml
test/irmin-pack/test_dispatcher.mli
test/irmin-pack/test_gc.ml
test/irmin-pack/test_pack.ml

See https://github.com/mirage/irmin/issues/2092

Some initial tests for dispatcher

---

CHANGES.md
src/irmin-pack/unix/dispatcher.ml
src/irmin-pack/unix/dispatcher_intf.ml
src/irmin-pack/unix/gc.ml
test/irmin-pack/test_gc.ml

I added a test to expose the bug... however the test does not pass even with the fix. I will investigate tomorrow.

Fix gc bugs when commits share the same tree 

---

src/irmin-pack/layout.ml
src/irmin-pack/unix/ext.ml
src/irmin-pack/unix/file_manager.ml
src/irmin-pack/unix/gc.ml
src/irmin-pack/unix/gc_worker.ml
src/irmin-pack/unix/mapping_file.ml
test/irmin-pack/test_pack.ml

A simple PR that is essentially name changes to use the new V4 layout.

irmin-pack: switch to V4 layout

---

CHANGES.md
src/irmin-pack/unix/mapping_file.ml

corresponding opam PR https://github.com/ocaml/opam-repository/pull/22321

Release 3.4.3

---

CHANGES.md

Updating changes to reflect https://github.com/mirage/irmin/pull/2123

Add 3.4.3 release to changelog

---

irmin-tezos.opam

Fix license metadata

---

src/irmin-pack/unix/mapping_file.ml

For the 3.6 release, the mapping file was incorrectly used on big endian platform (s390x).
Tested within qemu with:
```
$ docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
$ docker run --rm -it s390x/ubuntu bash
```

irmin-pack: fix mapping file for big endian

---

CHANGES.md
src/irmin-git/irmin_git_intf.ml
src/irmin/mem/irmin_mem.mli

more info type equality

---

CHANGES.md
irmin-tezos.opam
libirmin.opam

See https://github.com/mirage/irmin/pull/2185 and https://github.com/ocaml/opam-repository/pull/23280 for context

Updates from 3.6.0 release

---

.ocamlformat

Bump ocamlformat version to 0.24.1

Update .ocamlformat to the latest

---

src/irmin-tezos-utils/dune
src/irmin-tezos-utils/parse.ml
src/irmin-tezos-utils/ring.ml
src/irmin-tezos-utils/show.ml

This PR adds an history of the watched entries to the graphical tool.
- The last 50 entries are saved in the history
- Each entry has a button to go back to them faster

irmin-tezos-utils: Add an history (with buttons)

---

examples/irmin-pack/gc.ml
src/irmin-pack-tools/tezos_explorer/files.ml
src/irmin-pack/layout.ml
src/irmin-pack/pack_value.ml
src/irmin-pack/unix/errors.ml
src/irmin-pack/unix/file_manager.ml
src/irmin-pack/unix/file_manager_intf.ml
src/irmin-pack/unix/gc.ml
src/irmin-pack/unix/gc.mli
src/irmin-pack/unix/gc_worker.ml
src/irmin-pack/unix/gc_worker.mli
src/irmin-pack/unix/io_errors.ml
src/irmin-pack/unix/lower.ml
src/irmin-pack/unix/lower_intf.ml
src/irmin-pack/unix/pack_store.ml
src/irmin-pack/unix/sparse_file.ml
src/irmin-pack/unix/sparse_file_intf.ml
src/irmin-pack/unix/store.ml
test/irmin-pack/test_gc.ml

irmin-pack: GC adds data to lower

---

CHANGES.md

Add changelog entry for 3.6.1

---

src/irmin-pack/unix/gc.ml

Previously, this would log a warning for every new GC if the previous results file did not exist, which is the expected state when a GC begins.
Noticed this in logs when debugging an issue with Victor:
```
[WARNING] Unlinking temporary files from previous failed gc. Failed with error No such file or directory
```

irmin-pack: only unlink results file if it exists

---

.github/workflows/git.yml

18.04 is no longer in service so our runs were failing. Also tidied the formatting since I was in the file.

github-ci: update to ubuntu-latest

---

test/irmin-pack/test_inode.ml

NOTE - I have had a go at this issue but am not sure its the correct approach hence I havent updated the CHANGES yet.
It looks like the Invalid_depth exception is raised in two places, on Inode's `Internal.of_concrete_exn` and also when doing a `find` (or more specifically `unsafe_find`).
- of_concrete_exn (included in this PR): the Inode_intf.Internal.of_concrete type has been changed to include an optional `?depth=0` parameter.  This allows to call it with the wrong depth which then surfaces the `Invalid_depth` exception.  My worry is that this is a bit too heavy handed and exposes the wrong API / type for `of_concrete`?  Also, if changed here should it be changed for other `of_concrete` funcs e.g. for `Portable.Proof.of_concrete`?
- Inode.unsafe_find (not included in this PR): I was …

irmin-pack: add test that raises `Invalid_depth`

---

CHANGES.md
src/irmin-pack/unix/gc.ml
src/irmin-pack/unix/gc.mli
src/irmin-pack/unix/store.ml
src/irmin/tree.ml
test/irmin-pack/test_gc.ml
test/irmin-pack/test_tree.ml

Changes from https://github.com/mirage/irmin/pull/2260

Apply 3.7.2 changes to `main`

---

doc/irmin-pack/index.mld

Please let me know if you need any changes.

`irmin-pack` Index Line Editing

---

CONTRIBUTING.md

Minor changes to Contributing

---

doc/irmin-pack/design/README.md

Mostly formatting / sentence structure, varying sentences for better readability

Revision of `irmin-pack` readme

---

doc/irmin-pack/design/lower_layer.md

A lot of tightening syntax (removing unnecessary prepositional phrases, etc.) for clarity and flow. Please check for accuracy. Also grammar and formatting fixes.
Some questions are below as well.

Edits to lower_layer.md

---

codecov.yml

Otherwise, codeconv complains with:
```
$  curl --data-binary @codecov.yml https://codecov.io/validate
Error at ['comment', 'behaviour']:
unknown field
```

Fix codeconv file

---

irmin-cli.opam

This PR attempts to fix the CI

Fix the CI
