mirage/irmin

- _tags
Don't use `-w A` and `-warn-error A` at the same time, it makes your build incompatible with future OCaml versions.
> remove -warn-error A

- lib/http/irmin_http.ml
- lib/http/irmin_http_server.ml
- lib/ir_sync_ext.ml
I have recently experimented with synchronizing different Irmin backends via HTTP and ran into a couple of problems.
Slice-based HTTP sync is not working because parameters for /export API handle are serialized in such a way that max parameter is set to an empty list resulting in empty slice. The first patch fixes this problem by serializing max parameter as optional list.
The second patch fixes a potential race condition in HTTP fetch protocol - the /export is called first and then /head. If after exporting slice remote head is advanced by concurrent process, local repository is left in inconsistent state. I think it is better to fetch remote head first and then ask for slice up to that point.
> Fix slice-based HTTP synchronization

- bin/ir_cli.ml
- lib/git/irmin_git.ml
- lib/http/irmin_http.ml
- lib/http/irmin_http_server.ml
- lib/ir_bc.ml
- lib/ir_bc.mli
- lib/ir_sync.ml
- lib/ir_sync.mli
- lib/ir_sync_ext.ml
- lib/ir_sync_ext.mli
- lib/irmin.ml
- lib/irmin.mli
Would be maybe better to carry the error along as a string instead of just
printing it once and forgetting about it. Not sure the error string would
be very useful for the users still.
Fix #202
> Do not fail silently when a synchronisation fails.

- lib/http/irmin_http.ml
- lib/http/irmin_http_common.ml
- lib/http/irmin_http_common.mli
- lib/http/irmin_http_server.ml
- lib/http/irmin_http_server.mli
- lib/ir_sync_ext.ml
- lib/unix/irmin_unix.mli
The client puts its version in the X-IrminVersion header of the request.
By default, the server will serve the request anyway if the header is not
set, as we still want default browser connections to work fine.
The server puts its version in the `versions` field of the JSON objects that
it returns. The client can deal with that and print the correct error message
instead of failing miserably in case of API mismatch.
Fix #167
> Add HTTP client and server version checks

- lib/http/irmin_http.ml
- lib/http/irmin_http_server.ml
Without this, delete requests over HTTP use the previous store task
which is often the server store creation task. Requires mirage/ocaml-cohttp#383.
Some of the code in `Irmin_http_server` common to `POST` and `DELETE` processing could be factored.
> Tasks should be transmitted with DELETE requests, too

- .travis.yml
Note: the build currently fails because Irmin gets downgraded to 0.9.1 for some reason. I'm not sure why that is. Since irmin-indexeddb doesn't currently specify any version constraints, I assume the cause is elsewhere (though I do need to add a constraint anyway).
> Travis: also test irmin-indexeddb

- lib/unix/irmin_unix.mli
Seems this function is now called `listen`, not `start_server`.
> fix docstring for Irmin_http_server.listen

- lib/http/irmin_http.ml
- lib/http/irmin_http_common.ml
- lib/http/irmin_http_common.mli
- lib/http/irmin_http_server.ml
- opam
The previous API was hard to parse (#266) and wrong (#269). This commit tries to
fix that.
Now the stream is an (almost valid) JSON array which looks like:
[ {"stream":"start"}, {"version":"..."}, {"result":..},..,{"result":..},{"stream":"end"}]
almost valid as the spec doesn't allow multiple fields with the same name; but
most of existing implementation don't really care.
This needs a special release of ezjsonm (0.4.2)
> Change the JSON stream API

- bin/ir_cli.ml
- lib/http/irmin_http_server.ml
- lib/http/irmin_http_server.mli
- lib/unix/irmin_unix.ml
- lib/unix/irmin_unix.mli
- lib_test/test_http.ml
Instead, return the Cohttp configuration for the server and let the user perform the listen. The resulting API is simpler (removes "timeout" and "uri" parameters), more flexible, and easier to use from Mirage.
Here's the diff for irmin-www to switch to the new API: https://github.com/talex5/irmin-www/commit/ff8a4e68e46abc11e698746ab407715caf4caf0e
>  Remove Irmin_http_server.listen

- lib/fs/irmin_fs.ml
- lib/git/irmin_git.ml
- lib/http/irmin_http.ml
- lib/http/irmin_http_common.ml
- lib/http/irmin_http_common.mli
- lib/http/irmin_http_server.ml
- lib/ir_ao.ml
- lib/ir_ao.mli
- lib/ir_bc.ml
- lib/ir_bc.mli
- lib/ir_commit.ml
- lib/ir_commit.mli
- lib/ir_node.ml
- lib/ir_ro.ml
- lib/ir_ro.mli
- lib/ir_rw.ml
- lib/ir_rw.mli
- lib/ir_tag.ml
- lib/ir_tag.mli
- lib/ir_view.ml
- lib/ir_view.mli
- lib/irmin.mli
- lib/mem/irmin_mem.ml
- lib_test/test_link.ml
- lib_test/test_store.ml
Irmin's store interface requires passing a task to every store. However, most stores don't need this for anything. This branch removes them from most places. The `BC` interface is unchanged, so users of the public interface should be unaffected.
Backend providers no longer deal with tasks at all.
Apart from simplifying the code, this change is necessary for adding a separate repository type. This will allow connecting to a database once and then reusing that state for multiple branches. This isn't possible if the backend stores must be recreated for each new commit message.
Notes:
- We might still want to change the `BC` interface, but I think this branch can be merged without that, as it is useful on its own.
- It is now explicit which operations create commits. In particular, the API …
> Remove task from internal stores

- opam
Attempting to compile irmin with git 1.7.0 fails:
```
```
Express this in `opam`.
> git versions < 1.7.1 conflict with irmin 0.9.10

- bin/ir_cli.ml
- bin/ir_resolver.ml
- examples/custom_merge.ml
- examples/deploy.ml
- examples/git_store.ml
- examples/process.ml
- examples/sync.ml
- examples/views.ml
- lib/fs/irmin_fs.ml
- lib/git/irmin_git.ml
- lib/http/irmin_http.ml
- lib/http/irmin_http_server.ml
- lib/ir_ao.ml
- lib/ir_ao.mli
- lib/ir_bc.ml
- lib/ir_bc.mli
- lib/ir_ro.ml
- lib/ir_ro.mli
- lib/ir_s.ml
- lib/ir_s.mli
- lib/ir_sync_ext.ml
- lib/ir_view.ml
- lib/irmin.mli
- lib/mem/irmin_mem.ml
- lib/mirage/irmin_mirage.ml
- lib_test/test_git.ml
- lib_test/test_http.ml
- lib_test/test_memory.ml
- lib_test/test_store.ml
Before, `BC.create` and similar took a `config` argument. Now, they take a `repo` argument, which can be obtained by calling `BC.connect config`.
The main goal here is to allow state to be shared between branches. For example, an Irmin repository backed by a database could open a connection in `connect` once, where currently it must open one connection for every branch or head store created.
A memory store could use this to keep the state (rather than using a global) and an HTTP-backed store could use this for the connection pool.
In fact, the old code didn't open one connection per branch, but 4, because the content, node, commit and tag stores each also open a connection. Ideally, I'd like to share the `repo` with these backing stores to get the number of required connections down to 1, …
> Add BC.repo type

- bin/ir_resolver.ml
- examples/custom_merge.ml
- examples/deploy.ml
- examples/git_store.ml
- examples/process.ml
- examples/sync.ml
- examples/views.ml
- lib/git/irmin_git.ml
- lib/git/irmin_git.mli
- lib/ir_bc.ml
- lib/ir_bc.mli
- lib/ir_s.ml
- lib/ir_s.mli
- lib/irmin.ml
- lib/irmin.mli
- lib/mirage/irmin_mirage.ml
- lib/mirage/irmin_mirage.mli
- lib/unix/irmin_unix.mli
- lib_test/test_common.ml
- lib_test/test_git.ml
- lib_test/test_http.ml
- lib_test/test_memory.ml
- lib_test/test_store.ml
The `Basic` functor makes things confusing for users by hiding what's going on, and restricts all back-ends to providing only the base API.
This branch removes it, changing the examples to use the more explicit form. As back-ends can now provide additional functions, `Irmin_git.Internals` is moved inside the store and the hacks removed (or, at least, moved to just the unit-tests). i.e. you can now only ask for a Git commit object from a Git store.
I also deleted `Ir_bc.Make` and `Ir_bc.MAKER` because a) they were confusing me, b) they aren't used within Irmin, and c) they are not exposed to users of the API.
Code needs to be updated from e.g.
module S = Irmin.Basic(Irmin_git.FS)(Irmin.Contents.String)
to
module S = Irmin_git.FS(Irmin.Contents.String)(Irmin.Ref.String)(Irmin.Hash.SHA1)
> Remove Irmin.Basic

- lib/fs/irmin_fs.ml
- lib/git/irmin_git.ml
- lib/http/irmin_http.ml
- lib/ir_ao.ml
- lib/ir_ao.mli
- lib/ir_bc.ml
- lib/ir_bc.mli
- lib/ir_commit.ml
- lib/ir_dot.ml
- lib/ir_dot.mli
- lib/ir_node.ml
- lib/ir_s.ml
- lib/ir_s.mli
- lib/ir_sync_ext.ml
- lib/ir_sync_ext.mli
- lib/ir_view.ml
- lib/ir_view.mli
- lib/irmin.ml
- lib/irmin.mli
- lib/mem/irmin_mem.ml
`Ir_s` was the only consumer of the `Ir_bc.STORE_EXT` interface, and all it did was repack the values to match its own interface. Now, `Ir_bc` exports the final public API directly. This should make the code easier to work with.
I also removed `AO.config`, as the previous change to `Irmin_git.Internals` meant it was no longer needed (my eventual goal is that internal stores will not take config objects at all).
> Combine Ir_bc.STORE_EXT and Ir_s.STORE

- lib/git/irmin_git.ml
- lib/git/irmin_git.mli
- lib/http/irmin_http.ml
- lib/http/irmin_http_server.ml
- lib/ir_bc.ml
- lib/ir_bc.mli
- lib/ir_commit.ml
- lib/ir_dot.ml
- lib/ir_node.ml
- lib/ir_s.mli
- lib/ir_sync.mli
- lib/ir_sync_ext.ml
- lib/ir_view.ml
- lib/irmin.ml
- lib/irmin.mli
- lib/mirage/irmin_mirage.mli
- lib/unix/irmin_unix.mli
- lib_test/test_common.ml
- lib_test/test_store.ml
Private.Repo is now provided by each back-end, allowing them to share state between their internal stores. For example, `Irmin_git` now creates a single underlying `G.t` store.
There are lots of changes to the unit tests because using `Private.Repo.ref_t` and similar no longer need a task.
`AO` stores are no longer required to provide `create`, so the dummy `Ir_node.Graph.Store.create` and `Ir_commit.History.Store.create` functions are gone.
`Sync.create` now takes a `Repo.t`, not a `config`, allowing `Repo.config` to be removed (and allowing sharing of state with the sync code).
> Allow back-ends to create their own internal stores

- lib/http/irmin_http.ml
- lib/http/irmin_http_server.ml
- lib/ir_bc.ml
- lib/ir_bc.mli
- lib/ir_dot.ml
- lib/ir_s.mli
- lib/ir_sync_ext.ml
- lib/irmin.mli
- lib/mirage/irmin_mirage.ml
- lib_test/test_memory.ml
- lib_test/test_store.ml
These are: `branches`, `remove_branch`, `heads`, `watch_branches`, `import`, `export`, and `task_of_head`.
This should make the API clearer, by making it obvious whether the current branch is or isn't used. Callers of the APIs have been updated in the obvious way (e.g. calling `S.Repo.branches (S.repo t)`), but in future some refactoring may simplify this. For example, the HTTP server currently opens a branch for each request, but ignores it for repo operations.
Note that `heads` used to ensure that the current branch's head was included in the returned set (which made a difference for anonymous branches). This feature has been removed. Ideally, we should use OCaml's GC to track which anonymous branches are still being used and return all of them.
> Move BC operations that ignore the branch to BC.Repo

- CHANGES.md
- bin/ir_cli.ml
- lib/git/irmin_git.ml
- lib/git/irmin_git.mli
- lib/http/irmin_http.ml
- lib/http/irmin_http_server.ml
- lib/ir_bc.ml
- lib/ir_bc.mli
- lib/ir_s.mli
- lib/ir_sync.ml
- lib/ir_sync.mli
- lib/ir_sync_ext.ml
- lib/ir_sync_ext.mli
- lib/ir_view.ml
- lib/ir_view.mli
- lib/irmin.ml
- lib/irmin.mli
- lib/mirage/irmin_mirage.ml
- lib_test/test_common.ml
- lib_test/test_store.ml
Change `type head` to `type commit_id`. `head` was confusing because it applied to all commits, not just branch heads. Putting `id` in the name makes it clear that this is just data and (for example) holding
an ID will not prevent the corresponding commit from being GC'd (once we have GC). `of_head` is now `of_commit_id`, `task_of_head` is now `task_of_commit_id`, `Internals.commit_of_head` is now `Internals.commit_of_id` and `BC.Head` is now `BC.Hash`.
(on top of #319)
> Change "type head" to "type commit_id"

- bin/ir_cli.ml
- examples/org.mirage.irmind.plist
- opam
The `--address` argument of the CLI now supports a URI
`launchd://<name>` where `<name>` corresponds to the section in
the property list file (see examples/org.mirage.irmind.plist).
To make the example work:
1. edit the .plist to contain the full path to the binary, and customise
the program arguments
2. install the .plist somewhere sensible (e.g. ~/Library/LaunchAgents)
3. `launchctl load <.plist path>`
4. connect to port 8080
This requires [mirage/ocaml-conduit#96]
Signed-off-by: David Scott <dave.scott@unikernel.com>
> CLI: Add support for launchd

- lib/git/irmin_git.ml
- lib/git/irmin_git.mli
- lib/ir_s.mli
- lib/ir_view.ml
- lib/irmin.mli
Expose `Store.Key = Contents.Path` in `Irmin.Maker`. Otherwise, the type of steps is abstract.
Also, I included a couple of minor clean-up patches in this PR that I've been too lazy to submit on their own. Let me know if you want them split out into their own PR.
> Fix step type

- bin/ir_resolver.ml
- lib/git/irmin_git.ml
- lib/git/irmin_git.mli
- lib/http/irmin_http.ml
- lib/http/irmin_http.mli
- lib/http/irmin_http_server.ml
- lib/ir_bc.ml
- lib/ir_bc.mli
- lib/ir_dot.ml
- lib/ir_node.ml
- lib/ir_node.mli
- lib/ir_s.mli
- lib/ir_view.ml
- lib/irmin.ml
- lib/irmin.mli
- lib/unix/irmin_unix.mli
- lib_test/test_common.ml
- lib_test/test_store.ml
A Node implementation can now expose additional metadata for each content item. The Git backend uses this to give the type of the file (normal, executable or symlink). This information is stored in the tree object, not the blob, so changing the content type doesn't work well.
Currently, this is only exposed via the private interfaces (not Irmin.BC/VIEW).
> Add directory metadata

- lib/git/irmin_git.ml
- lib/ir_bc.ml
- lib/ir_commit.ml
- lib/ir_commit.mli
- lib/ir_dot.ml
- lib/ir_s.mli
- lib/ir_view.ml
- lib/irmin.mli
- lib_test/test_store.ml
Since we already require a Node.empty, there's no need to make nodes optional too.
Note: `HISTORY.node` previously returned None if the node was missing from the store. It now throws an exception. I believe this is the correct behaviour, rather than pretending the node was empty.
Fixes #349 by ensuring that Git always has a valid node to commit.
> Require all commits to have a root node

- bin/ir_cli.ml
- examples/custom_merge.ml
- examples/deploy.ml
- examples/git_store.ml
- examples/process.ml
- examples/views.ml
- lib/irmin.mli
- lib_test/test_store.ml
See https://github.com/ocsigen/lwt/pull/107
> Lwt_unix.run is deprecated

- Makefile
- lib_test/test.ml
- lib_test/test_http.ml
- pkg/pkg.ml
Use exec to respawn the same binary but with different command-line
argument, eg. `test.native serve 3` which will run a webserver
using the 3rd configuration.
This avoids the scary message:
__THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__()
and should make the tests work on Windows (yay).
> Remove Lwt_unix.fork in the tests

- .merlin
- .travis.yml
- _tags
- irmin-mirage.opam
- pkg/META.mirage
- src-mirage/irmin_mirage.ml
- src-mirage/irmin_mirage.mli
V1/V1_LWT does no longer exist, use mirage-clock / mirage-kv-lwt directly
adjust merlin/tags/opam and META files
> final fixes for MirageOS3

- bin/ir_cli.ml
- bin/ir_resolver.ml
- examples/custom_merge.ml
- examples/deploy.ml
- examples/irmin_git_store.ml
- examples/process.ml
- examples/sync.ml
- examples/views.ml
- src-git/irmin_git.ml
- src-git/irmin_git.mli
- src-http/irmin_http.ml
- src-http/irmin_http.mli
- src-mirage/irmin_mirage.ml
- src-mirage/irmin_mirage.mli
- src-unix/irmin_unix.ml
- src-unix/irmin_unix.mli
- src/ir_s.mli
- src/irmin.ml
- src/irmin.mli
- src/irmin_fs.ml
- src/irmin_fs.mli
- src/irmin_mem.ml
- src/irmin_mem.mli
- test/test_common.ml
- test/test_fs.ml
- test/test_git.ml
- test/test_http.ml
- test/test_mem.ml
- test/test_unix.ml
KV stores use string lists as paths and strings as branches. The rest of the
types (hashes, metadata) is left abstract.
Also add `Metadata` as a parameter to the main `Make` functors.
> Add a simplified KV functor to build a store by only providing contents

- src/ir_contents.ml
- src/ir_merge.ml
- src/ir_merge.mli
- src/irmin.mli
This is already used by Irmin.Contents.String and Irmin.Contents.Cstruct but not yet exposed.
> Add Irmin.Merge.idempotent for values with idempotent operations

- bin/ir_cli.ml
- examples/deploy.ml
- examples/views.ml
- src/ir_s.mli
- src/ir_store.ml
- src/ir_tree.ml
- src/irmin.mli
- test/test_store.ml
And fix the weird case of caching the empty value while the store is being reset.
It is better to have a cleaner API and pay a small runtime cost when handling the
empty tree.
> Revert the `empty` -> empty ()` change

- CHANGES.md
- src/ir_tree.ml
- test/test_store.ml
Regression introduced in 1.0: nested diffs where reported with the wrong path.
Signed-off-by: Thomas Gazagnaire <thomas@gazagnaire.org>
> Fix Irmin.Tree.diff

- src-git/irmin_git.ml
- src-git/irmin_git.mli
- test/main_git.ml
- test/main_unix.ml
- test/test_common.ml
- test/test_git.ml
- test/test_unix.ml
> Stop printing errors on invalid branch names

- src/ir_hash.ml
It should return an Error value instead
> Irmin.Hash.of_string should not raise an exception on invalid hash

- src/irmin-fs/irmin_fs.ml
- src/irmin-git/irmin_git.ml
- src/irmin-mem/irmin_mem.ml
- src/irmin/hash.ml
- src/irmin/irmin.ml
- src/irmin/irmin.mli
- src/irmin/s.ml
- src/irmin/type.ml
- src/irmin/type.mli
- test/common/test_link.ml
On a trivial benchmark (commiting a view with a lot of new key/values), this series of patch introduce a 20-times speed-up (from around 60 seconds to around 3 seconds).
After some profiling, it looks like most of the time was spent on `memcpy` and `to_hex`. To remove unrequired copy/conversion, this series of patch abstract the signature of `Hash.digest` from `Cstruct.t -> t` to `'a Type.t -> 'a -> t`.
Our trivial benchmark is based on `irmin-mem` and `Irmin.Contents.Cstruct`. Half of the speed-up comes from the serialisation of leafs (no encoding to hexadecimal anymore). The rest of the speed is gained from the 'hashing' of nodes (no intermediate JSON representation).
Further optimisation seems doable, but these simple one looks like the only one that requires some change in the functor …
> Abstract digest serialization

- src/irmin/tree.ml
On a trivial benchmark (initialising a tree with a lot of values), this
patch introduces a 10-times speed-up (around 30 seconds to around 3).
This is achieved by removing unrequired structural comparisons when
inserting/removing a value in the tree.
The function `add/add_tree/remove` try to reduce the pressure on the GC
by not reallocating the tree when the resulting tree is (structurally)
equal to the previous one. But instead of only comparing the inserted
value to the previous value (if it exists), the current implementation
also recursively compare all the nodes on the insertion path.
This patch simplify the insertion/removal, by changing the type of the
recursive function `aux`. It now returns an option : `None` when the sub
tree was not modified.
> Tree: improved complexity.

- irmin.opam
Needed because of `Hex.of_cstruct`
> opam: add lower bound to the hex package

- src/bin/jbuild
- src/irmin/irmin.mli
- src/irmin/merge.ml
- src/irmin/merge.mli
- src/irmin/type.ml
- src/irmin/type.mli
- test/common/test_store.ml
Let the programmer decide which size of ints to use to avoid 32/64b
conversion issues.
/cc @hannesm
> Remove non-portable `Type.int` and `Merge.int`

- src/irmin/irmin.mli
updates `record` related examples to reflect the current state of the library
This also swaps out the `foo`s, `x`s, and `bar`s for more concrete examples.
> fix Irmin.Type examples

- README.md
- src/irmin-chunk/irmin_chunk.mli
- src/irmin-unix/bin/ir_cli.ml
The majority of these changes are to the README file, but there are some other small documentation updates included as well.
For now, I've temporarily removed all links to projects that aren't compatible with Irmin 1.0 but am interesting in adding links to related projects that work with the current version at some point. Having the links to the incomaptible libraries is very confusing.
I think the README still needs quite a bit more work, especially in regards to how we describe what Irmin is. This is something I will continue to think about, but if anyone has any opinions on this I would love to hear them.
> Documentation updates

- src/irmin-unix/bin/ir_cli.ml
Fixes an issue with parsing commit hashes when using the revert command (#488)
> Fix revert command

- README.md
- irmin-unix.opam
- src/irmin-unix/bin/ir_cli.ml
- src/irmin-unix/bin/ir_resolver.ml
- src/irmin-unix/jbuild
This update converts the configuration format to YAML, using `ocaml-yaml` as discussed in #502. The name of the configuration file has also been changed from `.irminconfig` to `irmin.yml`
Additionally, I have made it possible to set the path to the configuration file on the command-line.
When this is released we will need to emphasize the fact that old `.irminconfig` files need to be updated to the new format.
> Use YAML for configuration

- src/irmin-test/test_store.ml
- src/irmin/irmin.mli
- src/irmin/s.ml
- src/irmin/store.ml
> Allow `Tree.hash` and `Tree.of_hash` to work on tree leafs

- src/irmin-unix/bin/ir_cli.ml
- src/irmin/irmin.mli
- Fixes a typo in `Irmin.Type` documentation
- Adds `author` parameter to `pull` command
> Fix documentation typo and command argument inconsistency

- src/irmin/store.ml
- src/irmin/tree.ml
- src/irmin/tree.mli
Instead of reading the node, simply create a lazy node which will be resolved
on subsequent writes (if any).
> Speed-up tree import

- src/irmin-test/test_store.ml
- src/irmin/tree.ml
Fixes #524 - I think this is all that's needed. I've tested it on some trees of different depths and it seems to be acting as expected now.
> Fix Tree.to_concrete handling of nested trees

- src/irmin-unix/bin/ir_resolver.ml
- src/irmin-unix/ir_cli.ml
- src/irmin-unix/ir_resolver.ml
- src/irmin/contents.ml
- src/irmin/contents.mli
- src/irmin/irmin.ml
- src/irmin/irmin.mli
This is my current implementation of a JSON datatype -- it is roughly modeled after a document store, like CouchDB or MongoDB, so it restricts top-level values to objects only. 
I think it is a nice addition because even though the `String` type can already be used to store JSON contents, this allows for the JSON encoding to be validated when using the command line tool.
I'm not totally sure if it's ready to be merged but wanted to at least open this up to discussion in order to get some feedback before I continue.
> JSON contents

- src/irmin-chunk/irmin_chunk.ml
- src/irmin-chunk/irmin_chunk.mli
- test/irmin-chunk/test.ml
- use the new `Irmin.Type` combinator instead of a custom serialisation format
- ensure the index trees are well-balanced
> Improve chunking

- src/irmin-http/irmin_http.ml
- src/irmin-http/irmin_http.mli
- src/irmin-unix/ir_unix.ml
- test/irmin-http/test_http.ml
I am not totally sure about the signature that `ctx` should have. `Uri.t -> ctx option Lwt.t` seems pretty generic, but maybe we want something simpler (with `Uri.t` and `Lwt.t`).
> Allow to use the HTTP API over unix local domain sockets

- examples/sync.ml
I also have a few questions about the new remote representation:
1) It seems like having both `Store.remote` and `Sync.remote` is kind of confusing, especially since `Sync.remote` works and `Store.remote` doesn't (at least in the case of the example) - Is there a reason both are exposed? This seems to be causing an issue when using `irmin pull` from the command-line as well (I will make another issue for that).
2) There is now no way to make an `endpoint` from a string or URI in a generic manner - is this true? If that's the case how do you think I should handle something like this: https://github.com/andreas/irmin-graphql/blob/master/src/irmin_graphql.ml#L275 -- I guess another parameter to `Make` that specifies the proper endpoint creation function wouldn't be *so* inconvenient, however …
> Fix examples/sync.ml for changes to remote API

- .travis.yml
- appveyor.yml
- examples/sync.ml
- src/irmin-git/irmin_git.ml
- src/irmin-git/irmin_git.mli
- src/irmin-mirage/irmin_mirage.ml
- src/irmin-mirage/irmin_mirage.mli
- src/irmin-unix/cli.ml
- src/irmin-unix/irmin_unix.mli
- src/irmin-unix/resolver.ml
- src/irmin-unix/resolver.mli
- src/irmin-unix/xgit.ml
- src/irmin-unix/xgit.mli
- src/irmin/irmin.mli
- src/irmin/s.ml
- src/irmin/store.ml
- src/irmin/store.mli
- src/irmin/sync.ml
- src/irmin/sync_ext.ml
- src/irmin/sync_ext.mli
/cc @zshipko and @dinosaure (for Canopy)
no more `Sync.remote` and now `Store.remote` is working (so this fixes #547) and the API is as simple as before: every store where it is possible to use a special remote has a `remote` function with the right type.
> Simplify the new sync API

- src/irmin-git/irmin_git.ml
- src/irmin/irmin.mli
- src/irmin/type.ml
- src/irmin/type.mli
- test/irmin/test.ml
This allows to import/export Git repositories using Irmin's slices. /cc @dinosaure and @g2p
> Serialise Git object using the Git serialisation format

- src/irmin/irmin.ml
- src/irmin/irmin.mli
- src/irmin/s.ml
- src/irmin/store.ml
- src/irmin/store.mli
Irmin.{set, set_tree, remove} now only accepts a `Merge_with_parent c` argument
so that they don't have to run 3-way merges themselves.
Aslo the logic for aborting operatin is now simpler:
- with set: no need, the operation always succeed
- test_and_set: there is a new "retry" parameter to limit the number of retries
in case someone updates the same subtree at the same time at the current
operation.
- merge: no retry operation; if the merge fails, raise an exception and let the
application code deal with that. Retrying in this case doesn't make sense,
as things will not (usually) improve by themselves on the main branch...
> core: more precise merge strategy

- src/irmin-git/irmin_git.ml
- src/irmin-git/irmin_git.mli
- src/irmin-http/irmin_http.ml
- src/irmin/irmin.ml
- src/irmin/irmin.mli
- src/irmin/type.ml
These stores use the underlying AO and RW storage but use the Git format
to serialise objects, which means that the hashes are compatible with
other Git repositories.
This fixes Sync.pull between Git and non-Git repositories.
> Allow to create generic Git stores

- src/irmin/irmin.mli
- src/irmin/object_graph.ml
- src/irmin/type.ml
- src/irmin/type.mli
By really making the add function tail-recursive.
> improve perf for Sync.export

- src/irmin-chunk/irmin_chunk.ml
- src/irmin-chunk/irmin_chunk.mli
Instead of fix-sized chunks, use chunks with a maximal size instead.
> Add a "best-fit" mode for chunking mode

- src/irmin-fs/irmin_fs.ml
- src/irmin-git/irmin_git.ml
- src/irmin-git/irmin_git.mli
- src/irmin-graphql/irmin_graphql.ml
- src/irmin-http/irmin_http.ml
- src/irmin-test/store.ml
- src/irmin-unix/cli.ml
- src/irmin/irmin.ml
- src/irmin/irmin.mli
- src/irmin/s.ml
- src/irmin/store.ml
- src/irmin/store.mli
- src/irmin/sync_ext.ml
- src/irmin/tree.ml
- src/irmin/tree.mli
This allows to make the `hash` functions not blocking, and allow to
check for equality without doing any writes.
> Merge all the S.Private.*.Hash modules into S.Hash

- src/irmin/contents.ml
- test/irmin/test.ml
> Fix json comparison using Irmin.Type.equal

- irmin-graphql.opam
- irmin-mem.opam
- src/irmin-graphql/irmin_graphql.ml
Unfortunately there isn't a good way to model the tree input arguments as recursive objects (as I had hoped):
```json
{
"a": {"b": {"c": "123"}}, 
"foo": "bar"
}
```
Instead, we have to use a flat array of objects:
```json
[
{"key": "a/b/c", "value": "123"}, 
{"key": "foo", "value": "bar"}
]
``` 
Despite this one minor flaw, I think this is a pretty nice way of supporting read/write transactions in `irmin-graphql`!
> Add get_tree and set_tree methods to irmin-graphql server

- src/irmin-git/irmin_git.ml
- src/irmin/irmin.mli
- src/irmin/s.ml
- src/irmin/sync_ext.ml
This should fix #594, although I'm not sure it's the right solution.
I'm happy to make some changes if there's a better way to handle this!
> Remove XXX error when `AlreadySync is encountered

- irmin-graphql.opam
- irmin-mirage.opam
- src/irmin-graphql/dune
- src/irmin-graphql/irmin_graphql.ml
- src/irmin-graphql/irmin_graphql.mli
- src/irmin-mirage/dune
- src/irmin-mirage/irmin_mirage.ml
- src/irmin-mirage/irmin_mirage.mli
- src/irmin-unix/cli.ml
- src/irmin-unix/graphql.ml
- src/irmin-unix/graphql.mli
- src/irmin-unix/irmin_unix.ml
- src/irmin-unix/irmin_unix.mli
Because [graphql-cohttp](https://opam.ocaml.org/packages/graphql-cohttp/) was released over the weekend, we can now merge this code which adds MirageOS support for `irmin-graphql`!
This change-set also includes a major overhaul to the way that GraphQL values are converted to the corresponding Irmin types. This is nice because it significantly reduces the complexity of the method implementations and as well as the number of times that `Irmin.Type.of_string` is used directly.
> Add MirageOS support for GraphQL servers

- src/irmin-graphql/irmin_graphql.ml
- src/irmin-graphql/irmin_graphql.mli
- src/irmin-mirage/irmin_mirage.ml
- src/irmin-mirage/irmin_mirage.mli
- src/irmin-unix/cli.ml
- src/irmin-unix/graphql.ml
- src/irmin-unix/graphql.mli
This PR removes the `SERVER` module type and replaces it with `Cohttp_lwt.S.Server` in the arguments to `Irmin_graphql.Make`. See: https://github.com/mirage/irmin/pull/598#issuecomment-447471791.
Sorry about all the whitespace changes! I forgot to disable `ocp-indent`.
/cc @andreas
> Simplify Irmin_graphql.Make by removing SERVER

- src/irmin/conf.ml
- src/irmin/dune
- src/irmin/irmin.mli
This PR implements the sanity check for Conf.key described in irmin.mli :
```
@raise Invalid_argument if the key name is not made of a
sequence of ASCII lowercase letter, digit, dash or underscore.
FIXME not implemented.
```
> Implement sanity check for Conf.key

- src/irmin-git/irmin_git.ml
- src/irmin-http/irmin_http.ml
- src/irmin/commit.ml
- src/irmin/commit.mli
- src/irmin/irmin.ml
- src/irmin/irmin.mli
- src/irmin/node.ml
- src/irmin/node.mli
- src/irmin/s.ml
The motivation for this PR is that all calls to `Commit.Make` (resp. `Node.Make`) in this repository are using the same value for commit (`C`) and node (`N`) (resp. node (`N`) and contents (`C`)) values.
This PR hence proposes to merge these values. This involves public API changes.
1.  At the `Make` functor level, have only one key argument for both commits/nodes (resp nodes/contents).
2. In the type itself, merging the two types into a `type hash`.
Of course, `1` is doable without `2` to still allow implementations with different key types.
> Simplify redundant keys in Commit and Node

- src/irmin-fs/irmin_fs.ml
- src/irmin-git/irmin_git.ml
A simple PR to replace `Hashtbl` with `Ephemeron` (weak tables), where this is suggested with a `FIXME`.
Please let me know if these could advantageously be replaced somewhere else too.
> Replace hashtables with weak tables

- irmin-graphql.opam
- src/irmin-graphql/irmin_graphql.ml
- src/irmin-graphql/irmin_graphql.mli
*The PR description of https://github.com/andreas/ocaml-graphql-server/pull/141 unintendedly closed https://github.com/mirage/irmin/pull/598 with no option of reopening, so this PR is a copy of #598* 😒
This PR adds the ability to watch the entire store or a specific key with notifications delivered via the GraphQL subscription mechanism (currently only websockets, possibly Server-Sent Events or chunked HTTP responses in the future).
Adding `Irmin_unix.set_listen_dir_hook ()` to `cli.ml` may be required...
> Irmin graphql subscriptions (take 2)

- .travis.yml
- src/irmin-mirage/irmin_mirage.ml
- src/irmin-mirage/irmin_mirage.mli
It's only RO for now, but it is already showing a few issues. The `last_modified` function is very naive and will iterate over the full store (which is not really optimal :p)
I plan to add the new RW functions too and see how it goes :-)
/cc @linse
> Use latest Mirage_kv.RO signature

- src/irmin-test/store.ml
- src/irmin/tree.ml
- test/irmin-http/test_http.ml
- cache the computation of node and contents hashes to not have to recompute it over and over
- make sure `Tree.add`, `Tree.add_tree` and `Tree.remove` are tail-recursive
- test that these functions preserve physical equality too
> Improve trees

- irmin-graphql.opam
`graphql_parser.0.11.0` replaces the dependency on `Str` with `Re`, which makes it Mirage-friendly.  See https://github.com/mirage/irmin/issues/632
> irmin-graphql depends on graphql_parser.0.11.0

- src/irmin/node.ml
- test/irmin/test.ml
/cc @pascutto 
The goal here is to optimise the data representation. It was very unclear if the list/map split was actually useful, so I've removed it (as it was mentioned by @pascutto in a discussion). Also this will probably conflict with the work done to split the contents node into "inodes" but I think it is worth it (and I can help to rebase it if needed).
> Improve the representation of internal nodes

- src/irmin-graphql/irmin_graphql.ml
- src/irmin-graphql/irmin_graphql.mli
Rather than always exposing contents and metadata from Irmin stores as strings in `irmin-graphql`, this PR allows exposing these types as custom GraphQL objects.
Consider an Irmin store containing contacts, that are stored as serialized JSON objects, e.g. `{\"tags\":[],\"aliases\":[],\"phone\":...." }`. Rather than simply returning the JSON string from `irmin-graphql`, a proper GraphQL object could be exposed with fields `tags`, `aliases` and `phone`. This is what this PR enables.
You can then do queries like the following:
```graphql
query {
master {
get(key: "contact/john@doe.org") {
tags
aliases
phone
}
}
}
```
The new functor `Irmin_graphql.MakeExt` adds a new argument compared to `Irmin_graphql.Make`, which has type `PRESENTATION` for configuring the GraphQL presentation:
```ocaml …
```
> Custom GraphQL objects for contents and metadata

- irmin.opam
- src/irmin/dune
- src/irmin/type.ml
- test/irmin/test.ml
This PR adds a special case when encoding/decoding strings with characters outside the range of 0-127.
Similar to `ezjsonm` a string containing invalid characters, such as `"\128\129"`, will be encoded as `{"hex": "8081"}`.
A few concerns about this change should be noted:
- The entire string must be scanned to determine if it's UTF8 safe when encoding
- A string containing a single invalid character becomes twice as long after JSON encoding
I'm happy to address these if there are any ideas regarding how to escape the string more efficiently, but I haven't found a better solution.
Fixes #631
> Fix JSON encoding for non-UTF8 safe characters

- src/irmin-git/irmin_git.ml
- src/irmin/commit.ml
- src/irmin/hash.ml
- src/irmin/irmin.mli
- src/irmin/node.ml
- src/irmin/type.ml
- src/irmin/type.mli
This is an extract of #649 
This allows to serialise a buffer (bytes/string) with or without a lenght header. I am not totally fond of the name of that option, but it's better than `toplevel`...
>  Irmin.Type: add an optional header option to encode/decode/size_of

- irmin-graphql.opam
@zshipko noticed `graphql-cohttp` was using `Str`. This PR bumps the dependency to `0.12` which got rid of this (https://github.com/andreas/ocaml-graphql-server/pull/146).
Awaiting https://github.com/ocaml/opam-repository/pull/13719 to be merged.
> irmin-graphql depends on graphql-cohttp >= 0.12

- src/irmin-graphql/server.ml
As part of reviewing the GraphQL schema, I thought some aspects were slightly confusing as detailed below.
The fields `value`, `metadata` and `hash` are optional for the type `Contents`. This reflects that a particular key could be either present or not, but I suggest this should rather be reflected by returning `null` rather than "empty" Contents object.
In practice, this means instead of returning this JSON ...
```json
{
"someContentsField": {
"key": "key/not/present",
"value": null,
"metadata": null,
"hash": null
}
}
```
... return this JSON instead:
```json
{
"someContentsField": null
}
```
Suggested diff in SDL terms:
```diff
type Contents {
-  hash: String
+  hash: String!
key: String!
-  metadata: String
-  value: String
+  metadata: String!
+  value: String!
}
```
The relationship …
> GraphQL schema suggestions

- src/irmin-mirage/irmin_mirage.ml
- src/irmin-mirage/irmin_mirage.mli
- src/irmin-unix/cli.ml
- src/irmin-unix/graphql.ml
- src/irmin-unix/graphql.mli
The initial renaming of GraphQL modules didn't cover the `irmin-unix`/`irmin-mirage`, so this PR makes sure that all GraphQL server related code is in a module named `*.Graphql.Server`
> Make sure all GraphQL modules conform to the same layout

- examples/process.ml
- src/irmin-test/store.ml
- src/irmin/slice.ml
This allows to propagate errors more quickly to the parent thread.
/cc @NathanReb and @pascutto
> Use Lwt.choose instead of Lwt.join

- src/irmin-graphql/server.ml
- src/irmin-graphql/server.mli
- src/irmin-unix/graphql.ml
- src/irmin-unix/graphql.mli
This PR exposes the current tree and key to the custom GraphQL presenter. In particular, the type of `Irmin_graphql.Server.PRESENTER.to_src` has changed in the following way:
```diff
- val to_src : t -> src
+ val to_src : tree -> key -> t -> src
```
This allows the custom presenter to look up other data in the tree as part of presenting the value (a use case coming from Bushel).
To facilitate this change, the functor `Irmin_graphql.Server.Default_presenter` has been replaced with the functor `Irmin_graphql.Server.Default_presentation`. This is motivated by the type of the tree and key now being part of the `Irmin_graphql.Server.PRESENTER`-signature.
Overriding the default presentation changes in the following way (assuming a module `S` of type `Irmin.S` is in scope):
```ocaml
(* Before …
```
> Expose tree and key to custom GraphQL presenter

- src/irmin-graphql/server.ml
- src/irmin-unix/resolver.ml
- Added `json_value` option for content type argument on command-line
- Prevent a few graphql methods from raising exceptions
> Add json_value content type

- src/irmin-chunk/irmin_chunk.ml
- src/irmin-http/irmin_http_server.ml
- src/irmin-test/store.ml
- src/irmin/irmin.mli
- src/irmin/lock.ml
- src/irmin/lock.mli
- src/irmin/s.ml
- src/irmin/store.ml
- src/irmin/tree.ml
- src/irmin/tree.mli
Every tree node/contents/hash has an associated info field stored in an
ephemeron. We try to alway keep alive only one version of similar values.
> Use hash-consing for tree nodes and contents.

- test/irmin-http/test_http.ml
INSIDE_DUNE allows dune to recursively call itself without creating
a new dune-project file.
/thx @emillon for the fix
> irmin-http: better recursive call to dune

- src/irmin-http/irmin_http.ml
- src/irmin-http/irmin_http_common.ml
- src/irmin-http/irmin_http_common.mli
- src/irmin-http/irmin_http_server.ml
This avoid having to recode all the merge logics on the client side.
> irmin-http: use a separate route to handle tree merges

- src/irmin-chunk/irmin_chunk.ml
- src/irmin-http/irmin_http.ml
- src/irmin-test/store.ml
- src/irmin/commit.ml
- src/irmin/contents.ml
- src/irmin/hash.ml
- src/irmin/hash.mli
- src/irmin/irmin.ml
- src/irmin/irmin.mli
- src/irmin/node.ml
- src/irmin/object_graph.ml
- src/irmin/s.ml
- src/irmin/store.ml
- src/irmin/store.mli
- src/irmin/tree.ml
- src/irmin/type.ml
- src/irmin/type.mli
- test/irmin-chunk/test.ml
- test/irmin-chunk/test_chunk.ml
- test/irmin-git/test_git.ml
- test/irmin/test.ml
Previous uses of `val hash: t -> int` are renamed to `short_hash`
to avoid confusion.
> Move code around and renamde digest -> hash

- .travis.yml
- README.md
- irmin-pack.opam
- src/irmin-pack/bitv.ml
- src/irmin-pack/bitv.mli
- src/irmin-pack/bloomf.ml
- src/irmin-pack/bloomf.mli
- src/irmin-pack/dune
- src/irmin-pack/irmin_pack.ml
- src/irmin-pack/irmin_pack.mli
- src/irmin-test/store.ml
- test/irmin-pack/dune
- test/irmin-pack/test.ml
- test/irmin-pack/test.mli
- test/irmin-pack/test_pack.ml
> irmin-pack

- src/irmin-pack/bench/dune
- src/irmin-pack/bench/pack_bench.ml
Hi!
This adds an executable that repeatedly adds files to a directory. This shows how tree operations perform.
I parameterized this:
if a number is passed as a command line argument, it will be used as number of commits.
`dune build @bench` will run this with ncommits=1000.
> Bench operations with large trees

- src/irmin/tree.ml
Divide by 2 the number of times we call `Node.Val.list` in Tree.export. This was found using the new tree perf counters + pack_bench.
> irmin.tree: optimise tree.export

- src/irmin-pack/irmin_pack.ml
Two small fixes here :
- There were some variable named `fd` in `IO` that are actually of type `t`.
- I find `Index.t.cache` misleading since it's not really a cache, but more a memory representation of `log`.
> Pack renames

- .travis.yml
From what I understood, these are equivalent, but `travis-docker.sh` uses docker images for switches instead of rebuilding them, which makes the builds faster.
> CI: Use .travis-docker.sh instead of .travis-opam.sh

- src/irmin-test/store.ml
- src/irmin/tree.ml
This will allow short-lived tree objects to be GC-ed more quickly.
> irmin.tree: use ephemerons again for caching trees

- src/irmin-pack/irmin_pack.ml
This occurs when the store file is corrupted. Before this fix, Irmin would repeatedly
increase the buffer size and retry, causing an Out of Memory error.
> Correctly deal with EOF result from Unix.read

- src/irmin-test/store.ml
In some cases, the next test will start before all the threads were complete --
for some reasons, it causes the next thread to be very confused and fail.
> irmin-test: fix flaky test

- src/irmin-pack/irmin_pack.ml
- src/irmin-pack/irmin_pack.mli
This adds two new `stats` fields to track the proportion of appended hashes that are encoded as offsets for compression purposes, making it possible to determine the space-efficiency of a bulk import mechanism w.r.t. the offset compression.
> irmin-pack: track offset/hash append ratio in stats

- src/irmin-chunk/irmin_chunk.mli
- src/irmin/irmin.mli
A spate of improvements to the documentation.
The most opinionated changes are in `Irmin.Type`. I've clarified the record and variant encodings slightly and changed the ordering of the presentation in the interface to make it slightly easier to read (in my opinion).
> irmin: documentation improvements

- .travis.yml
- irmin-chunk.opam
- irmin-fs.opam
- irmin-git.opam
- irmin-graphql.opam
- irmin-http.opam
- irmin-mirage.opam
- irmin-pack.opam
- irmin-test.opam
- irmin-unix.opam
This updates the opam files to ensure that the various irmin packages depend on the same version that is released from the repo. This is certainly required for irmin 2, but can be relaxed in the future as minor versions are released.
Also remove pin-depends on git 2.1.0 since that is now released.
> update opam files

- src/irmin-pack/pack.ml
- src/irmin-pack/pack_index.ml
- `fan_out_size` is now a number of bits
- the `Key` module requires the size of the hash
> Reflect API change in index

- src/irmin-pack/inode.ml
- src/irmin-pack/inode.mli
- src/irmin-pack/irmin_pack.ml
- src/irmin-pack/irmin_pack.mli
- src/irmin-pack/pack.ml
- src/irmin-pack/pack.mli
- test/irmin-pack/bench.ml
- test/irmin-pack/test_pack.ml
There is now two modes of operations for inodes:
- small inodes (#children <= Conf.stable_hash) have their hashes identical to
what would flat nodes do.
- large inodes (#children > Conf.stable_hash) would have a more optimised hash,
which can be computed whithout having to read the full children first.
> irmin-pack: support for large inodes

- src/irmin-fs/irmin_fs.ml
- src/irmin-mem/irmin_mem.ml
- src/irmin-pack/irmin_pack.ml
- src/irmin-unix/resolver.ml
- src/irmin/irmin.mli
- test/irmin/test.ml
This is a candidate solution for #727.
[SHA-1 has been broken](https://shattered.io/), and so is no longer a sensible default.
> Change default hash to BLAKE2b

- src/irmin-pack/irmin_pack.ml
- src/irmin-pack/irmin_pack.mli
- src/irmin-pack/pack.ml
- src/irmin-pack/pack.mli
- src/irmin-pack/pack_index.ml
- src/irmin-pack/pack_index.mli
- test/irmin-pack/test_pack.ml
This will probably conflict with #805 but with a different aim/goal. The goal here is to make sure we are calling `Pack_index.Make` only once.
/cc @CraigFe
> irmin-pack: do not duplicate the creation of the Index module

- src/irmin/irmin.mli
- src/irmin/s.ml
- src/irmin/sync_ext.ml
This is a candidate solution for #755.
There may be a more elegant solution unifying local and remote status types, but this avoids changing either type for now.
> irmin: expose additional pretty-printers

- src/irmin-pack/IO.ml
- src/irmin-pack/IO.mli
- src/irmin-pack/dict.ml
- src/irmin-pack/inode.ml
- src/irmin-pack/inode.mli
- src/irmin-pack/irmin_pack.ml
- src/irmin-pack/pack.ml
- src/irmin-pack/pack.mli
- test/irmin-pack/test_pack.ml
This pulls out instantiation of the Index.t from the `Pack` functor and makes it a compulsory argument to the construction of any `Pack` index, making sharing of the index more explicit. Previously, the behaviour relied on the sharing properties of the Index library:
https://github.com/mirage/irmin/pull/799#discussion_r303423708
N.B. there's at least one bug in this currently. Not to be merged.
> irmin-pack: instantiate index once

- src/irmin-pack/pack.ml
- test/irmin-pack/test_pack.ml
https://github.com/mirage/index/pull/14 will allow to add duplicate keys in the index (e.g. shorter hashes) and get them using `find_all`.
This PR reflects the API change. It does not use shorter hashes, a separate PR might be better for that.
> Use `Index.find_all`

- test/irmin-http/test_http.ml
Cohttp server creation now allows passing of an exception handler, fixing a previous issue where the server would crash on a user-raised exception.
See: https://github.com/mirage/ocaml-cohttp/pull/669
> irmin-http: remove exception handling workaround in tests

- src/irmin-graphql/server.mli
This PR exposes `Irmin_graphql.Server.Schema` as an alias of `Graphql_lwt.Schema`, which there's really no reason in hiding and makes things simpler as a user of `Irmin_graphql.Server`.
/cc @zshipko
> irmin-graphql: Expose Schema as alias of Graphql_lwt.Schema

- src/irmin-pack/IO.ml
- src/irmin-pack/IO.mli
- src/irmin-pack/dict.ml
- src/irmin-pack/dict.mli
- src/irmin-pack/irmin_pack.ml
- src/irmin-pack/irmin_pack.mli
- src/irmin-pack/pack.ml
- src/irmin-pack/pack_dict.ml
- extracts the caching of `Dict` constructions to a separate `Pack_dict` module;
- parameterises `Dict` on an arbitrary `IO` module, and hides the internal IO instance (this was only being used to do `IO.sync`, which is already exposed via `Dict.sync`).
These changes will aid potential future extraction of the `Dict` functionality.
> irmin-pack: improve Dict module abstraction

- src/irmin-pack/pack_dict.mli
Takes care of a few loose ends in https://github.com/mirage/irmin/pull/828:
- ~~removes a redundant `shared` argument in the constructor of `Dict`~~
- adds missing copyright header / `.mli` file for `Dict`
> irmin-pack: minor cleanup in Dict

- .ocamlformat-ignore
- README.md
- examples/dune
- examples/readme.ml
This fixes #830. 
The README example is also copied to the `examples/` directory to discourage this from happening again.
> irmin: update README to 2.0 interface

- src/irmin-pack/irmin_pack.ml
- src/irmin-pack/pack_index.ml
- src/irmin-pack/pack_index.mli
- test/irmin-pack/test_pack.ml
See https://github.com/mirage/index/pull/32
> irmin-pack: adapt to latest change in index (no more fan_out_size)

- src/irmin/type.ml
This PR alters the `short_hash` function to reduce the amount of work done to mix the hash.
It doesn't replicate exactly the behaviour of `hash (hash s, !h)` instead it passes `!h` in as a seed value which is mixed with `hash s`. This may or may not be acceptable. 
Benchmarking the change I see `test/irmin-pack/bench.exe --clear -a 20` taking 1.61s with the change vs 1.85s baseline (after running a couple of times to burn in).
> Faster short_hash implementation in type

- src/irmin-chunk/irmin_chunk.ml
- src/irmin-fs/irmin_fs.ml
- src/irmin-git/irmin_git.ml
- src/irmin-graphql/server.ml
- src/irmin-http/irmin_http.ml
- src/irmin-mem/irmin_mem.ml
- src/irmin-mirage/git/irmin_mirage_git.ml
- src/irmin-pack/inode.ml
- src/irmin-pack/irmin_pack.ml
- src/irmin-pack/pack.ml
- src/irmin-test/store.ml
- src/irmin-unix/fs.ml
- src/irmin/commit.ml
- src/irmin/contents.ml
- src/irmin/merge.ml
- src/irmin/node.ml
- src/irmin/store.ml
- src/irmin/sync.ml
- src/irmin/sync_ext.ml
- src/irmin/tree.ml
- test/irmin-git/test_git.ml
- test/irmin-http/test_http.ml
- test/irmin-pack/test_pack.ml
- test/irmin-unix/test_unix.ml
Replaces all instances of `Lwt.replace` in the codebase with a specialised `Lwt.return_*` form when this is possible.
-  For constant values, this [avoids a minor allocation](https://ocsigen.org/lwt/3.2.1/api/Lwt#3_Preallocatedpromises).
- In other cases (`Some`, `Ok`, `Error`), there is no associated optimisation, but it seems worth being consistent anyway.
> Standardise usage of pre-provided Lwt promises

- src/irmin-chunk/irmin_chunk.ml
- src/irmin-fs/irmin_fs.ml
- src/irmin-git/irmin_git.ml
- src/irmin-http/irmin_http.ml
- src/irmin-mem/irmin_mem.ml
- src/irmin-pack/irmin_pack.ml
- src/irmin/irmin.ml
- src/irmin/irmin.mli
- src/irmin/s.ml
- src/irmin/store.ml
- src/irmin/store.mli
This needs backends to provide their own close implementation.
Currently it's a no-op for most backends but would be good to add
consistent exceptions when users try to deal with an empty store.
This is demonstrated in the irmin-mem backend where every operation
is not checked against a `closed` flag stored in the repository state.
> irmin: add a Repo.close operation to the high-level API

- test/irmin-http/dune
- test/irmin-unix/dune
/cc @CraigFe 
Will hopefully fix #847
> test: use a lock to avoid races between irmin-unix and irmin-http tests

- src/irmin-pack/pack.ml
The index file is the source of truth regarding which objects are present
in the pack file or not, so it should be updated last.
> irmin-pack: fix a small race when updating the pack file

- src/irmin-test/store.ml
- src/irmin/store.ml
Fixes #681.
Currently, when only one commit is present in the store, the following operation is evaluated to `true`, as reported by @aweis :
```OCaml
S.history t >|= S.History.is_empty
```
This is due to the `filter_map` function called in `history`, which iterates over edges. There are obviously none when only one vertex is present in the graph, thus I handled this case separately.
The proposed solution is not really elegant, but I do not want to induce a performance cost here. Any idea to make it look better is appreciated.
> Fix `history` when only one commit is present

- test/irmin-http/dune
- test/irmin-unix/dune
Lock names are interpreted as file names, and so the irmin-{http,unix}
test suites were holding _different_ `http` locks in their respective
directories. This fixes the tests to run mutually exclusively by holding
an `http` lock in the shared parent directory.
> Fix dune locks used in the HTTP tests

- test/irmin-git/test_git.ml
This test instance was polluting the main test/ directory, causing
issues with `git` believing it to be a submodule (e.g. erroring
on `git add .`).
> Move irmin-git test repository to _build/ directory

- examples/custom_graphql.ml
- examples/dune
- src/irmin-graphql/server.ml
- src/irmin-graphql/server.mli
- src/irmin-unix/graphql.ml
- src/irmin-unix/graphql.mli
When mutating values via `irmin-graphql`, the caller is currently required to provide the serialized version of values. As an example, consider the custom content type `Car` from the Irmin tutorial ([link](https://zshipko.github.io/irmin-tutorial/Contents.html#record)). Before this PR, the caller would be required to make a GraphQL request such as the following to set a value:
```graphql
mutation {
set(key: "foo", value: "{\"license\":\"AB123456\",\"year\":1955,\"make_and_model\":[\"Ford\",\"Thunderbird\"],\"color\":\"White\",\"owner\":\"John Doe\"}") {
}
}
```
This is clearly not great, and breaks symmetry with the ability to provide a custom GraphQL presenter (https://github.com/mirage/irmin/pull/643).
This PR allows providing a custom value GraphQL input  type for `irmin-graphql`, such …
> Allow custom value GraphQL input type for irmin-graphql

- irmin-mirage-git.opam
- irmin-mirage.opam
- src/irmin-mirage/git/dune
- src/irmin-mirage/git/irmin_mirage_git.ml
- src/irmin-mirage/git/irmin_mirage_git.mli
- src/irmin-mirage/graphql/dune
- src/irmin-mirage/irmin_mirage.ml
- src/irmin-mirage/irmin_mirage.mli
awaits a release of git (see mirage/ocaml-git#376), is then ready for mirage 3.7 :D
> adapt to mirage 3.7.0 API changes

- src/irmin-pack/IO.ml
See https://github.com/mirage/index/pull/131 for a similar fix in index.
> irmin-pack: avoid writes of size 0

- src/irmin-mirage/git/irmin_mirage_git.ml
- src/irmin-mirage/git/irmin_mirage_git.mli
What I try to accomplish?
I have a web service which interacts via HTTP to user(s). Its data is stored via a Mirage_kv.RW in a key-value store. Now, an (potentially authenticated) web client may use HTTP to modify data in the store. The web service itself does the KV (and git) interaction, but I'd appreciate to embed the (HTTP-authenticated) user name in the git commit (i.e. "Author: alice via my-web-service"), which is radically more useful than "Author: my-web-service", especially for triaging issues and auditing changes.
Now, the control and data flow is already a bit intricate, thus this PR only uses `unit -> string` for the `author` to be used (similarly to `msg: op -> string`). I.e. the author name to be provided from something more globally known (for me, dynamically bound (and …
> irmin-mirage-git: KV_RW provide 'author' delayed (unit -> string) instead of string

- src/irmin-pack/pack_index.ml
This is already used by Tezos (https://gitlab.com/tezos/tezos/blob/zeronet/vendors/irmin-pack/pack_index.ml#L31)
> Set hash size to Tezos's default one

- CHANGES.md
- src/irmin-unix/resolver.ml
- src/irmin-unix/resolver.mli
- src/irmin/hash.ml
- src/irmin/hash.mli
- src/irmin/irmin.mli
Closes #896.
- Adds new `Make_BLAKE2X` functors to `Irmin.Hash` (matching those in `Digestif`), which allow the user to set the bit-length of these hash functions. The original `BLAKE2B` and `BLAKE2S` modules have been kept as sensible defaults.
- Add a `--hash` parameter to the `irmin` binary, allowing the hash function to be specified. For BLAKE2b and BLAKE2s, the bit-length may be specified with a trailing slash, as in `--hash=blake2b/16`. This behaviour is documented in the `--help` and manpages.
- Generally improves the documentation produced by `Cmdliner` (e.g. by exposing the various store / content types as enum values).
~~__TODO__: add an error when attempting to set the hash function in combination with a Git-compatible backend (for which the hash function must be `SHA1`). At …
> Add CLI options for setting the hash function

- test/irmin-chunk/test_chunk.ml
- test/irmin-git/test_git.ml
- test/irmin-mem/test_mem.ml
- test/irmin-pack/test_pack.ml
The `clean` function, run after a test, sometimes re-opens the store. In Irmin-pack this leads to many fd in use during tests.
> Close repo in tests

- src/irmin/object_graph.ml
Hashes are read as numerical value and confuse Graphviz. This leads to a
warning: syntax ambiguity - badly delimited number; and to weird png
files. The fix is to enquote the vertex name.
> Add quotes on hashes when generating dot files

- irmin-git.opam
- src/irmin-git/irmin_git.mli
`Irmin_value_store` doesn't provide any constructors for its various stores and doesn't expose the stores' types either, so it appears to be impossible to construct them. The changes in this PR would allow building irmin-indexeddb without any pins.
> Add missing type equalities to irmin-git

- src/irmin/irmin.mli
- src/irmin/node.ml
- src/irmin/object_graph.ml
- src/irmin/object_graph.mli
- src/irmin/s.ml
In order to make https://github.com/mirage/irmin/pull/882 more manageable I'll make a few smaller PRs which introduce some modifications for 882 but not strictly related to the layered store. 
This PR introduces an `iter_on_closure` operation which applies a function to the nodes and the edges of the closure graph as it traverse it. This way the closure graph is not be returned (and need not be in memory). 
`iter_on_closure` duplicates code from `closure` because I'm worried that resolving unit promises for every node and every edge in the closure graphs introduces performance overhead for `closure`.  
`iter_on_closure` is introduced for object_graph and the node store (this is what I need for the layered store), but for consistency I could also introduce it for the commit store.
> Iter on closure

- src/irmin/slice.ml
This behaviour also is closer to the one of `Lwt_list.iter_p`: wait for all iter functions to resolve before returning.
> Make slice iter blocking

- CHANGES.md
- src/irmin/diff.mli
- src/irmin/dot.mli
- src/irmin/hash.mli
- src/irmin/info.ml
- src/irmin/info.mli
- src/irmin/irmin.mli
- src/irmin/lock.mli
- src/irmin/merge.mli
- src/irmin/s.ml
- src/irmin/type.mli
- src/irmin/type/irmin_type.mli
- src/irmin/watch.mli
This is a first attempt at inlining the duplicated signatures in Irmin core.
Mostly consists of pushing documentation from `irmin.mli` to `s.ml` or
`<filename>.mli`, and making the alias explicit in `irmin.mli`:
```ocaml
module type APPEND_ONLY_STORE = sig ... end
(* becomes *)
module type APPEND_ONLY_STORE = S.APPEND_ONLY_STORE
```
There are three API changes here:
- exposing `Type.pp_ty`, which was previously unused;
- removing `Info.with_message`, also unused;
- exposing `Merge.with_conlict`, which was used internally but not exposed in
the public signature. I feel as though we might as well provide this.
> Partially de-duplicate signatures contained in irmin.mli

- src/irmin-test/store.ml
- src/irmin/node.ml
- src/irmin/object_graph.ml
- src/irmin/object_graph.mli
- src/irmin/s.ml
Replaced bfs with dfs in `iter` in order to support traversal of the closure graph in both direction: when `rev = false` then a node (and the edges to its predecessors) is treated when it is first visited. Otherwise a node is treated only after all of its predecessors have been treated first. `skip` and `level` are verified when first visiting each node.
> Add reverse traversal to iter

- .ocamlformat
- src/irmin-chunk/irmin_chunk.mli
- src/irmin-fs/irmin_fs.mli
- src/irmin-git/irmin_git.mli
- src/irmin-http/irmin_http.mli
- src/irmin-http/irmin_http_server.mli
- src/irmin-mem/irmin_mem.mli
- src/irmin-mirage/git/irmin_mirage_git.mli
- src/irmin-mirage/irmin_mirage.mli
- src/irmin-pack/pack.mli
- src/irmin-unix/irmin_unix.mli
- src/irmin-unix/resolver.mli
- src/irmin/irmin.mli
- src/irmin/node.mli
- src/irmin/object_graph.mli
- test/irmin-pack/common.mli
... and remove `profile = conventional`, since it's no longer necessary.
Based on https://github.com/mirage/irmin/pull/926 for convenience.
> Autoformat documentation strings with OCamlformat

- src/irmin-test/store.ml
- src/irmin/irmin.mli
- src/irmin/node.ml
- src/irmin/object_graph.ml
- src/irmin/object_graph.mli
- src/irmin/s.ml
- src/irmin/store.ml
- src/irmin/sync_ext.ml
`closure` on the commit graph need at least one node in the `max` list, since the graph is directed. Functions that compute closures on the commit graph now return an error when `max` is empty.  If there are nodes in `min` that are not connected to at least one `max` node an error is returned as well. 
`export` is similar to `closure` but is defined at the level of a store and therefore can retrieve the current head. Functions that compute exports therefore use head whenever `max` is empty and only return an error for a disconnected min node.
> Clarify closures and exports of commit graph 

- irmin-test.opam
A quick fix to the development environment while we wait for the Alcotest 1.0.1 release to make it to the CI (after which point https://github.com/mirage/irmin/pull/942 can be merged).
CC. @icristescu
> Constrain Alcotest to pre-1.0

- CHANGES.md
- src/irmin-graphql/server.ml
@voodoos raised the issue that introspection was broken with GraphiQL for `irmin-graphq`. The issue turns out to be due to duplicate GraphQL type names 🤦‍♂ The duplicate names were introduced in https://github.com/mirage/irmin/pull/867, which allowed users to customize more of the GraphQL types exposed by `irmin-graphql`.
In this PR, I have simply renamed the two offending cases. A better solution would be https://github.com/mirage/irmin/pull/771, such that new scalar types are not introduced needlessly. As an example, a branch name is often a string, and the built-in GraphQL scalar `String` would be perfectly suitable to reuse, rather than introduce a new scalar `BranchName`, which is a string under the hood anyway.
> Ensure unique default GraphQL type names

- irmin-test.opam
- src/irmin-test/common.ml
- test/irmin-pack/test_pack.ml
Making the tests compatible with the new releases of alcotest and alcotest-lwt raises two issues:
- one related to https://github.com/mirage/alcotest/issues/183 : I used the default value of `80` instead of adding dependencies to the tests;
- alcotest-lwt does not let us run `Alcotest_lwt.test_case` and `Alcotest.test_case` together anymore in `irmin-pack`. I decided to add an `Lwt_main.run` inside the tests as this is what we do in all tests, except for `irmin-pack`. If we want to use alcotest_lwt I think we should do a refactoring of all irmin tests.
> Alcotest fix

- ppx_irmin.opam
- test/ppx_irmin/deriver/dune
- test/ppx_irmin/deriver/gen_dune_rules.ml
Currently based on https://github.com/mirage/irmin/pull/952 (unmerged), as we intend to merge that first.
> ppx-irmin: remove test dependency on Fmt

- src/irmin-pack/IO.ml
- test/irmin-pack/common.ml
- test/irmin-pack/common.mli
- test/irmin-pack/dune
- test/irmin-pack/multiple_instances.ml
- test/irmin-pack/multiple_instances.mli
- test/irmin-pack/test_pack.ml
This is similar to [commit on index](https://github.com/mirage/index/commit/5551cf2d879bd46e14d2a8b73317f43a36916cec): when a RO instance of pack is opened it should not clear the buffers it shares with RW instances.
> Fix shared buffer clear

- CHANGES.md
- src/irmin/type/irmin_type.ml
- src/irmin/type/irmin_type.mli
- test/irmin/test.ml
As part of the ongoing [fuzz testing of `Irmin.Type`](https://github.com/pascutto/irmin/pull/1), I discovered that we currently allow the declaration of records, variants and enums for which two fields or cases share the same name.
While this this isn't a problem in most use cases, it might create some problems when dealing with JSON encoding and decoding (since `decode_json` relies on the user-provided names to uniquely identify each field or case).
This pull request solves the problem by enforcing that:
- No two fields of a record have the same name (otherwise `sealr` will raise);
- No two cases __of the same arity__ of a variant have the same name (otherwise `sealv` will raise);
- No two cases of an enum have the same name (otherwise `enum` will raise).
Note that __two cases of a …
> Forbid duplicate field and case names in `Irmin.Type`.

- dune-project
- examples/dune
- src/irmin-chunk/dune
- src/irmin-fs/dune
- src/irmin-git/dune
- src/irmin-graphql/dune
- src/irmin-http/dune
- src/irmin-mem/dune
- src/irmin-mirage/dune
- src/irmin-mirage/git/dune
- src/irmin-mirage/graphql/dune
- src/irmin-pack/dune
- src/irmin-test/dune
- src/irmin-unix/bin/dune
- src/irmin-unix/dune
- src/irmin/dune
- test/irmin-chunk/dune
- test/irmin-fs/dune
- test/irmin-git/dune
- test/irmin-http/dune
- test/irmin-mem/dune
- test/irmin-pack/dune
- test/irmin-unix/dune
- test/irmin/dune
I suggest we shift to Dune's autoformatter for `dune` files.
The formatting is not ideal, but I'd rather have it than not.
> Use autoformatting for dune files

- appveyor.yml
Appveyor is adding a lot of noise to our PRs, and we've stopped paying any attention to it when merging. I suggest we disable it until someone has time to debug it.
An eventual fix is tracked by: https://github.com/mirage/irmin/issues/963.
> Temporarily disable Appveyor CI

- ppx_irmin.opam
To be consistent with the other packages in this repository. ISC is
functionally identical to BSD-2 (the original license).
See https://github.com/mirage/irmin/pull/952#issue-381486598.
> Relicense ppx_irmin under ISC

- CHANGES.md
- src/irmin/type/irmin_type.mli
- src/irmin/type/type_json.ml
- test/irmin/test.ml
Last one for the day: when [fuzz testing the JSON encoder of `Irmin.Type`](https://github.com/pascutto/irmin/pull/1), I also discovered that we are using an ambiguous representation of `'a option`, where `None` is represented as `null` and `Some x` is unboxed into `x` directly.
This causes–admittedly unlikely–issues when trying to encode nested option types, since e.g. `None` and `Some None` would both turn into `null`.
To avoid these issues, this pull request changes the representation of options to lists: 
- `None` is now encoded as `[]` in general;
- `Some x` is now encoded as `[x]` in general.
However, to maintain backwards-compatibility with most use-cases (as suggested by @samoht):
- Fields of records with the value `None` are still omitted altogether;
- Fields of records with the …
> Change the JSON representation of 'a option and unit to avoid ambiguity.

- src/irmin/irmin.mli
- src/irmin/type.mli
Uses the `@inline` annotation to expand references to the signatures file in the documentation, avoiding unneccesary noise. This can't be extended to module types that are _not_ aliased in `irmin.ml`, but this mostly applies to those in `Private` anyway.
Also inlines the inclusion of `Irmin_type` into `Irmin.Type`, hopefully encouraging users to use the latter.
> irmin: use Odoc @inline annotation to hide aliases into s.ml

- src/irmin/type/type_pp.ml
- test/irmin/test.ml
Resolves https://github.com/mirage/irmin/issues/959. In the same vein as https://github.com/mirage/irmin/pull/965, test the behaviour of the `Irmin.Type.pp_ty` operation. Found and fixed a format string bug in doing so.
Shares a LCA with https://github.com/mirage/irmin/pull/965 for the `ppx_irmin` dependency.
Some thoughts about the current behaviour:
- pretty-printed output for algebraic types isn't particularly helpful (c.f. https://github.com/mirage/irmin/issues/958);
- the `Prim` node could be skipped during pretty-printing;
- `Custom (foo)` is really `Like (foo)` from a user perspective;
- we could consider a more OCaml-friendly ordering & capitalisation (e.g. `int list` rather than `List (Prim Int)`).
> irmin.type: test the `pp_ty` operation

- README.md
- irmin-git.opam
... and add installation instructions to the README for installing Irmin from `master`.
I'm sure I've mentioned this before, but I feel that issues with `opam install .` should be caught by the CI.
Resolves https://github.com/mirage/irmin/issues/972.
> Fix irmin-git -> irmin constraint

- CHANGES.md
- src/irmin/type/irmin_type.ml
- src/irmin/type/irmin_type.mli
- src/irmin/type/type_core.ml
- src/irmin/type/type_json.ml
- test/irmin/test.ml
As part of the ongoing [fuzz testing of `Irmin.Type`](https://github.com/pascutto/irmin/pull/1), and particularly of the encoding and decoding of Irmin values into JSON, I discovered a nasty edge case that would crash the JSON decoder whenever the name of a record field or a variant case was not proper UTF-8.
Here is a minimal example:
```ocaml
open Irmin.Type
let e = enum "e" ["\128\255\255\r\012\247\r\r\r\r\r\r\003\r\r\r\r\r\rl", `Weird]
let v = `Weird
let json = to_json_string e v
let oops = of_json_string e json
```
The last line raises an OOB which can be traced back to `src/irmin/type/type_json.ml:364`.
In short, what happens is that:
- Irmin encodes nullary constructors as strings (the name of the constructor), and unary constructors as objects (which map the name of the …
> Forbid non-UTF8 names for record fields and variant cases.

- ppx_irmin.opam
- test/ppx_irmin/deriver/passing/alias.expected
- test/ppx_irmin/deriver/passing/arguments.expected
- test/ppx_irmin/deriver/passing/basic.expected
- test/ppx_irmin/deriver/passing/composite.expected
- test/ppx_irmin/deriver/passing/module.expected
- test/ppx_irmin/deriver/passing/nonrec.expected
- test/ppx_irmin/deriver/passing/polyvariant.expected
- test/ppx_irmin/deriver/passing/record.expected
- test/ppx_irmin/deriver/passing/signature.expected
- test/ppx_irmin/deriver/passing/tuple_deep.expected
- test/ppx_irmin/deriver/passing/variant.expected
This release of `ppxlib` supports up to OCaml 4.10 (previously we could use up to OCaml 4.08).
> ppx_irmin: upgrade to Ppxlib 0.12.0

- CHANGES.md
- irmin-graphql.opam
- src/irmin-graphql/server.ml
- test/irmin-graphql/common.ml
- test/irmin-graphql/common.mli
- test/irmin-graphql/dune
- test/irmin-graphql/test.ml
- test/irmin-graphql/test.mli
Resolves an issue [reported on `discuss.ocaml.org`](https://discuss.ocaml.org/t/irmin-graphql-keys-are-reversed/5509) in which key information returned by `get_tree.list` and `get_contents` is reversed. For example, the following query:
```graphql
{
master {
tree {
get_tree(key: "/a/b/c") {
list {
key
}
}
}
}
}
```
would return keys of the form `/c/b/a/foo` rather than `/a/b/c/foo`.
This PR fixes the bug and adds an initial end-to-end test suite for `irmin-graphql` exposing the original bug. The test suite props up a GraphQL server, queries it, then checks the response using `yojson` (a new test dependency).
> irmin-graphql: fix path ordering with get_{contents,tree.list}

- CHANGES.md
- src/irmin-test/store.ml
- src/irmin/s.ml
- src/irmin/stdlib_ext.ml
- src/irmin/stdlib_ext.mli
- src/irmin/store.ml
- src/irmin/store_intf.ml
- src/irmin/tree.ml
`S.Tree.t` was previously a concrete type with redundant constructurs `of_node` and `of_contents`. In some places, we were using these constructors; in others, we were constructing the value directly. 
This change encourages delegation by requiring all instances of `S.Tree.t` to go via the constructors and destructors in `S.Tree`.
I made this change last week while experimenting with 'foreign' hashes support (which likely want to add a case to this type), but I think it stands as an improvement by itself.
> Make `S.Tree.t` abstract

- CHANGES.md
- irmin-graphql.opam
- src/irmin-mem/irmin_mem.ml
- src/irmin-mem/irmin_mem.mli
- test/irmin-graphql/common.ml
- test/irmin-graphql/common.mli
- test/irmin-graphql/dune
- test/irmin-graphql/test.ml
The test-suite introduced by https://github.com/mirage/irmin/pull/989 was accidentally attached to the `irmin-git` package, causing CI for `irmin-git` to fail in Travis (but not in OCaml-CI, since these cross-package bugs are not caught there).
Only _one_ of the two failures on that PR were "unrelated"...
> irmin-graphql: use irmin-mem in tests

- dune-project
As of Dune 2.5.0, warnings are emitted if the `(using lang <foo>)` stanza is using a version higher than is supported. This gives us the following warning in CI:
```
File "dune-project", line 3, characters 11-14:
3 | (using fmt 1.2)
^^^
Warning: Version 1.2 of integration with automatic formatters is not
supported until version 1.11 of the dune language.
Supported versions of this extension in version 1.8 of the dune language:
- 1.0 to 1.1
```
> Use correct fmt version in dune-project

- CHANGES.md
- README_PPX.md
- src/ppx_irmin/deriver/ppx_irmin.ml
- src/ppx_irmin/lib/attributes.ml
- src/ppx_irmin/lib/attributes.mli
- src/ppx_irmin/lib/deriver.ml
- test/ppx_irmin/deriver/errors/dune.inc
- test/ppx_irmin/deriver/errors/nobuiltin_nonempty.expected
- test/ppx_irmin/deriver/errors/nobuiltin_nonempty.ml
- test/ppx_irmin/deriver/passing/dune.inc
- test/ppx_irmin/deriver/passing/nobuiltin.expected
- test/ppx_irmin/deriver/passing/nobuiltin.ml
`@nobuiltin` is a [standard](https://github.com/ocaml-ppx/ppx_deriving#plugin-conventions) attribute for deriving plugins that causes them to view the annotated type as abstract / not use any built-in derived form for that type. This is ocassionally useful when shadowing types in the library: I implemented it more for the sake of convention than anything else.
> ppx_irmin: add support for the @nobuiltin attribute

- CHANGES.md
- README_PPX.md
- src/ppx_irmin/deriver/ppx_irmin.ml
- src/ppx_irmin/lib/deriver.ml
- src/ppx_irmin/lib/deriver.mli
- test/ppx_irmin/deriver/errors/dune.inc
- test/ppx_irmin/deriver/errors/lib_invalid.expected
- test/ppx_irmin/deriver/errors/lib_invalid.ml
- test/ppx_irmin/deriver/passing/dune.inc
- test/ppx_irmin/deriver/passing/lib_relocated.expected
- test/ppx_irmin/deriver/passing/lib_relocated.ml
This adds support for a `lib` argument to `[@@deriving irmin]` that can be used to pull type representations from a location other than `Irmin.Type` (such as when `Irmin.Type` is aliased to another name).
> ppx_irmin: support primitive representations outside 'Irmin.Type'

- CHANGES.md
- src/irmin/type/type.ml
- src/irmin/type/type_binary.ml
- src/irmin/type/type_core.ml
- src/irmin/type/type_json.ml
- src/irmin/type/type_ordered.ml
- src/irmin/type/type_pp.ml
- src/irmin/type/type_size.ml
- test/irmin/test.ml
Resolves https://github.com/mirage/irmin/issues/958.
This changes the pretty-printer for Irmin types to more closely match OCaml types (e.g. `(unit * int) option` rather than `Option (Pair (Prim Unit, Prim Int))`). It adds functionality for pretty-printing the components of algebraic types: record types are pretty-printed like OCaml object types and variants are pretty-printed similarly to OCaml polymorphic variants.
The tricky case here is recursive types, which were previously broken (would cause stack overflow when pretty-printed). Handling this properly requires preserving the `unroll` function passed to the `mu` combinator for later use. The type can then be pretty-printed by unrolling once with a type alias:
```ocaml
type my_recursive_record = { head : int; tail : …
```
> irmin.type: improve pp_ty

- src/irmin-pack/IO.ml
Fixes https://github.com/mirage/irmin/issues/998.
This function is inlined by flambda, causing the outer call to no longer be in tail position and the `[@tailcall]` annotation to be rejected.
> irmin-pack: drop tailcall annotation causing build failure on flambda

- src/irmin-http/irmin_http.mli
- src/irmin-pack/irmin_pack.mli
- src/irmin/irmin.ml
- src/irmin/irmin.mli
- src/irmin/sync.ml
- src/irmin/sync.mli
This allows 'endpoints' for backends that do not support `SYNC` (such as `Irmin_pack`) to be serialised.
> irmin: expose unit implementation of Sync.None.endpoint

- src/irmin-mem/irmin_mem.mli
- src/irmin/irmin.mli
- src/irmin/store_intf.ml
... in stores constructed via `S_MAKER`s such as `irmin-mem`.
> Expose more unit endpoint types

- ppx_irmin.opam
- src/ppx_irmin/lib/attributes.ml
- test/ppx_irmin/deriver/bugs/json_module.expected
- test/ppx_irmin/deriver/bugs/json_module.ml
- test/ppx_irmin/deriver/errors/dune.inc
- test/ppx_irmin/deriver/gen_dune_rules.ml
- test/ppx_irmin/deriver/passing/alias.expected
- test/ppx_irmin/deriver/passing/alias.ml
- test/ppx_irmin/deriver/passing/arguments.expected
- test/ppx_irmin/deriver/passing/arguments.ml
- test/ppx_irmin/deriver/passing/composite.expected
- test/ppx_irmin/deriver/passing/composite.ml
- test/ppx_irmin/deriver/passing/dune.inc
- test/ppx_irmin/deriver/passing/lib_relocated.expected
- test/ppx_irmin/deriver/passing/lib_relocated.ml
- test/ppx_irmin/deriver/passing/nobuiltin.expected
- test/ppx_irmin/deriver/passing/nobuiltin.ml
- test/ppx_irmin/deriver/passing/nonrec.expected
- test/ppx_irmin/deriver/passing/nonrec.ml
- test/ppx_irmin/deriver/passing/tuple_deep.expected
- test/ppx_irmin/deriver/passing/tuple_deep.ml
... and use this to catch a bug in the `passing/nonrec.ml` test.
Also adds a (broken) test case witnessing the bug described by https://github.com/mirage/irmin/issues/923 (cc. @pascutto). I couldn't find an easy way to assert that this bug exists as part of `dune runtest` (doing so would likely require something like [janestreet/toplevel_expect_test](https://github.com/janestreet/toplevel_expect_test)).
> ppx_irmin: strengthen the tests to compile and run the output

- irmin-pack.opam
- src/irmin-pack/IO.ml
Fixes https://github.com/mirage/irmin/issues/1009.
Depends on https://github.com/mirage/index/pull/176.
> irmin-pack: use pread/pwrite to avoid lseek calls

- src/irmin-test/store.ml
- test/irmin-pack/multiple_instances.ml
We cannot use two instances of RW as they share the same index. This PR remove the problematic test from the test suite (which was working before, as we forgot to close a repo in another test). 
In a first commit I added some tests to show the problem occurs for both RW and RO instances. They are also removed in the second commit.
> Test close

- ppx_irmin.opam
Currently ppx_irmin is flagged as requiring exactly ppxlib 0.12.0. I'm not totally sure why this constraint is so strict, but I just tested it with ppxlib 0.13.0 and it compiles fine.
Incidently, this PR allows ppx_irmin to be installable with OCaml 4.11 as ppxlib is only compatible with OCaml 4.11 as of 0.13.0.
If this PR is accepted I'll go ahead and return the fix in opam-repository in `ppx_irmin.2.2.0`.
> Allow ppx_irmin to use ppxlib >= 0.12.0

- irmin-pack.opam
We cannot use the latest commits from index because of the pin in `irmin-pack.opam`. This changes the pin to `index#master`.
> update pin index

- .travis.yml
I've spent quite a bit of time staring at Travis recently, and realised we can probably speed it up by ~8 minutes just by running the `irmin-unix` tests (which take the longest) first. Travis runs through these jobs in a sequential window, and putting `unix` first gives it a head-start.
> Travis: run irmin-unix tests first

- src/irmin-test/store.ml
This is picked by dune2 which makes these file read-only.
> irmin-test: make sure test outputs do not overwrite each other

- irmin-pack.opam
- src/irmin-pack/pack_index.ml
- src/irmin-pack/pack_index.mli
This updates the Index pin to current master, adding the minimal necessary changes.
This supersedes https://github.com/mirage/irmin/pull/1042, which was a little _too_ minimal.
> irmin-pack: use explicit instance sharing API for Index

- src/irmin/type/type.ml
- src/irmin/type/type.mli
- src/irmin/type/type_pp.ml
- src/irmin/type/type_pp.mli
- test/irmin/test_type.ml
This pull request solves two issues regarding the `Irmin.Type` pretty-printer:
1. Right now, the pretty printer falls back to the JSON encoder in some cases (see `src/irmin/type/type_pp.ml:27`). This can lead to consistency issues when the behavior of the JSON encoder changes, which would be the case if #979 gets merged for instance.
2. Right now, the output of the pretty-printer is a mixture of OCaml-like syntax and JSON. Ideally (cc. @CraigFe), the pretty-printer should "give us something that can be copy-pasted" into an OCaml REPL, which could be helpful when debugging Alcotest diffs.
The first commit rewrites `Type_pp.t` to remove the dependency on the JSON encoder, and to use a new output format which "can be copy-pasted". The second commit updates the unit tests to reflected the new …
> Better pretty-printer output.

- .github/workflows/changelog-check.yml
This will enable a GitHub action failing iff CHANGES.md was not modified and no-changelog-needed tag is not present.
Taken from https://github.com/ocaml-ppx/ocamlformat/blob/6c2524ba7cb737dda647176f47f155b4d74aa90f/.github/workflows/main.yml.
> Add a changelog check

- CHANGES.md
- src/irmin/type/type_json.ml
- test/irmin/test_type.ml
While running the fuzzer, I discovered that we don't properly support the floating-point value `NaN`. 
When converting it into JSON, we pass it to Jsonm which produces the token `nan` (because Jsonm uses `string_of_float` and `string_of_float Float.nan = "nan"`). Yet, since `nan` is not a valid JSON token [according to the specification](https://www.json.org/json-en.html), Jsonm doesn't know how to print it and fails with an "illegal literal" error when decoding.
This pull request fixes the issue by encoding `NaN` floats to `null`.
> Fixed "illegal literal" error when JSON-decoding NaN.

- irmin-bench.opam
This updates our version of Bechamel to include https://github.com/dinosaure/bechamel/pull/8, which fixes our CI.
> irmin-bench: use latest Bechamel

- src/irmin/type/type_pp.ml
OCaml-CI pushed 4.11 builders over the weekend, which causes our CI to
fail due to this warning.
> irmin: fix warning on OCaml 4.11

- test/irmin-unix/dune
This should fix at least some of the spurious failures in the CI at present.
Cherry-picked from https://github.com/mirage/irmin/pull/991, since it may be some time before that can be merged.
> Use workaround for broken locks in Dune pre-2.5.1

- .ocamlformat
- examples/custom_graphql.ml
- src/irmin-chunk/irmin_chunk.ml
- src/irmin-containers/linked_log.ml
- src/irmin-git/irmin_git.ml
- src/irmin-pack/inode.ml
- src/irmin/contents.ml
- src/irmin/diff.ml
- src/irmin/merge.ml
- src/irmin/node.ml
- src/irmin/object_graph.ml
- src/irmin/s.ml
- src/irmin/slice.ml
- src/irmin/store.ml
- src/irmin/sync_ext.ml
- src/irmin/tree.ml
- src/irmin/type/type.ml
- test/irmin/test_type.ml
Hi, this is what the project would look like after being reformated with the current version (candidate) of ocamlformat 0.15.0.
**Please do not merge until ocamlformat.0.15.0 is available with opam.**
The main changes are due to the improved inconsistency of option `indicate-multiline-delimiters`, a lot of spaces where missing before closing parentheses in the previous versions.
Please let me know if you see any regressions that I may have missed.
> Upgrade to ocamlformat 0.15.0

- Makefile
- bench/irmin/dune
- test/irmin-mem/dune
- test/irmin-pack/dune
We don't want to run these benchmarks as part of `dune build`, so can't have `run` aliases for them as we do for the tests.
> Remove @runbench targets

- src/irmin-pack/IO.ml
We are now caching the IO instances instead. Also, this could lead
to tricky bugs when we start to rename files.
This is similar to https://github.com/mirage/index/commit/f8fdc9367bab6acfce0800c4e2aa928bbbe3eb01
> Remove caching of buffers

- test/irmin-unix/dune
The unix tests alos contains HTTP tests, so they might try to use
the same ressources and then explode.
> Do not run the HTTP test and the unix tests concurrently

- src/ppx_irmin/deriver/dune
Temporarily solution to Travis CI errors caused by the latest release of Ppxlib. A better solution would be to just require the latest version, but other packages in the repository are not compatible with it (see https://github.com/mirage/irmin/pull/1063).
> ppx_irmin: implicitly depend on Base

- src/irmin-git/irmin_git.ml
- src/irmin-http/irmin_http.ml
- src/irmin-test/store.ml
- src/irmin/store.ml
- src/irmin/watch.ml
- test/irmin-graphql/common.ml
- test/irmin-http/test_http.ml
Discard stale events
There are two different ways to produce events (which are then consumed by watchers):
- every update to the reference store will call notify, which will notify watcher connected to the same repository in that process
- there is a background thread, using irmin-watcher (with either polling mode, inotify or fsevents), which check for filesystem changes, and call notify whenever a reference change.
It is necessary that the events are delivered in (commit) order, as the API is exposing diffs and it would be confusing if the events go back in time.
There is a small race right now between these two mechanism: the background thread could read a new reference value, be interrupted, and then call notify. During that interruption, the store can change and events be delivered. …
> Flaky tests: discard stale events

- CHANGES.md
- irmin-test.opam
- src/irmin-chunk/irmin_chunk.ml
- src/irmin-fs/irmin_fs.ml
- src/irmin-git/closeable.ml
- src/irmin-git/irmin_git.ml
- src/irmin-http/closeable.ml
- src/irmin-http/irmin_http.ml
- src/irmin-http/irmin_http_server.ml
- src/irmin-http/s.ml
- src/irmin-mem/irmin_mem.ml
- src/irmin-pack/closeable.ml
- src/irmin-pack/inode.ml
- src/irmin-pack/irmin_pack.ml
- src/irmin-test/dune
- src/irmin-test/store.ml
- src/irmin/commit.ml
- src/irmin/contents.ml
- src/irmin/irmin.ml
- src/irmin/node.ml
- src/irmin/s.ml
- test/irmin-chunk/test_chunk.ml
- test/irmin-mem/test_mem.ml
- test/irmin-pack/common.ml
- test/irmin-pack/common.mli
- test/irmin-pack/multiple_instances.ml
- test/irmin-pack/test_pack.ml
This supersedes the other half of https://github.com/mirage/irmin/pull/1015, along with https://github.com/mirage/irmin/pull/1070. The implementation is mostly unchanged from the original.
> Add a clear function to all backends

- CHANGES.md
- examples/dune
- irmin-git.opam
- irmin-http.opam
- irmin-unix.opam
- irmin.opam
- src/irmin-git/dune
- src/irmin-unix/bin/dune
- test/irmin-chunk/dune
- test/irmin-fs/dune
- test/irmin-git/dune
- test/irmin-http/dune
- test/irmin-mem/dune
- test/irmin-pack/dune
- test/irmin-unix/dune
- test/irmin/dune
Using `digestif.0.8.0` allows to use `digestif.c` as the default variant and thus does not require a specific mention in the `dune` files anymore.
> Use digestif default variant

- irmin-pack.opam
- test/irmin-pack/migration.ml
The `--recursive` flag does not work on macOS
```
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
```
and also updated the pin on index.
> recursive flag for cp on macOS

- examples/custom_merge.ml
- examples/dune
- src/irmin/irmin.mli
Hi! I was trying out Irmin for the first time, and following the example on in the `irmin.mli` docs, but found that some of the code didn't compile.
The principle point of this PR is to sync the docs with the current code in `examples/custom_merge.ml` (12fac5f). Along the way I also
- fixed one misnamed target (i think) that blocked (abe3758)
- made some tiny tweaks to the example code, for readability and documentation (cf794de)
- this commit also applies auto formatting my editor imposed due to the `.ocamlformat` config in the repo. Let me know if you'd like me to revert that stuff.
> Sync merge example and doc example

- ppx_irmin.opam
This fixes a cyclic actions error when attempting to install all packages in the Irmin repository along with their test dependencies:
```
The actions to process have cyclic dependencies:
- install irmin.dev -> install ppx_irmin.dev -> install irmin.dev
No solution found, exiting
```
As discussed offline, neither of our CIs caught this error, but the fix is witnessed by the following `Dockerfile`:
```dockerfile
FROM ocurrent/opam:alpine-3.12-ocaml-4.09
WORKDIR /src
RUN sudo chown opam /src
RUN opam update -u
RUN git clone --single-branch --branch add-missing-post https://github.com/CraigFe/irmin /src
RUN opam pin add -yn ppx_irmin.dev "./" && \
opam pin add -yn irmin.dev "./" && \
opam pin add -yn irmin-unix.dev "./" && \
opam pin add -yn irmin-test.dev "./" && \
opam pin add -yn …
```
> Add missing `post` flag in the `ppx_irmin` → `irmin` dependency

- src/irmin/type/type.mli
The given definition and type representation were not matching in the old version. Updated it to make it correct.
> Minor documentation change

- CHANGES.md
- src/irmin/commit.ml
- src/irmin/s.ml
- src/irmin/store.ml
- src/irmin/store_intf.ml
The two `iter` functions are used in the [layered store](https://github.com/mirage/irmin/pull/882), to iterate over the [commi graph](https://github.com/mirage/irmin/pull/882/files#diff-52ce06d08638434eac31d8f0240b3b5eR583) and the [node graph](https://github.com/mirage/irmin/pull/882/files#diff-52ce06d08638434eac31d8f0240b3b5eR546). Having two separate functions allows us to choose in which order we iterate over the commit graph, whereas for the node graph the order is fixed: we have to iterate in reverse order to keep the compression of inodes.
> Iter on node and commit graphs

- ppx_irmin.opam
- src/ppx_irmin/lib/dune
... and drop dependency on `ocaml-syntax-shims`. Irmin itself requires 4.07.0 now, and this enables using `ppxlib.metaquot` in the implementation of `ppx_irmin`, which is a nice plus.
> ppx_irmin: require OCaml 4.07.0

- CHANGES.md
- README_PPX.md
- ppx_irmin.opam
- src/ppx_irmin/deriver/ppx_irmin.ml
- src/ppx_irmin/deriver/ppx_irmin.mli
- src/ppx_irmin/lib/algebraic.ml
- src/ppx_irmin/lib/algebraic.mli
- src/ppx_irmin/lib/algebraic_intf.ml
- src/ppx_irmin/lib/attributes.ml
- src/ppx_irmin/lib/attributes.mli
- src/ppx_irmin/lib/deriver.ml
- src/ppx_irmin/lib/deriver.mli
- src/ppx_irmin/lib/dune
- src/ppx_irmin/lib/monad.ml
- src/ppx_irmin/lib/monad.mli
- src/ppx_irmin/lib/monad_intf.ml
- test/ppx_irmin/deriver/passing/arguments.expected
- test/ppx_irmin/deriver/passing/arguments.ml
- test/ppx_irmin/deriver/passing/nonrec.expected
- test/ppx_irmin/deriver/passing/nonrec.ml
- test/ppx_irmin/deriver/passing/signature.expected
- test/ppx_irmin/deriver/passing/signature.ml
... and fix uses of the word 'generic' in the code and documentation.  In the
literature, the term 'generic' describes an operation that is parameterised
over run-time type representations. The type representations themselves are not
'generic's.
> ppx_irmin: simplify implementation with Metaquot

- src/ppx_irmin/lib/algebraic.ml
- src/ppx_irmin/lib/algebraic_intf.ml
- src/ppx_irmin/lib/deriver.ml
- src/ppx_irmin/lib/monad.ml
- src/ppx_irmin/lib/monad_intf.ml
- test/ppx_irmin/deriver/errors/unsupported_type_arrow.expected
- test/ppx_irmin/deriver/errors/unsupported_type_extension.expected
- test/ppx_irmin/deriver/errors/unsupported_type_open_polyvariant.expected
- test/ppx_irmin/deriver/errors/unsupported_type_package.expected
- test/ppx_irmin/deriver/errors/unsupported_type_poly.expected
- test/ppx_irmin/deriver/errors/unsupported_type_variable.expected
Also contains a small refactoring to scrap an unnecessary functor in the implementation.
Depends on https://github.com/mirage/irmin/pull/1083.
> ppx_irmin: improve locations in Unsupported error messages

- CHANGES.md
- README_PPX.md
- src/ppx_irmin/lib/algebraic.ml
- src/ppx_irmin/lib/deriver.ml
- src/ppx_irmin/lib/raise.ml
- src/ppx_irmin/lib/raise.mli
- src/ppx_irmin/lib/utils.ml
- test/ppx_irmin/deriver/errors/dune.inc
- test/ppx_irmin/deriver/errors/unsupported_type_variable.expected
- test/ppx_irmin/deriver/errors/unsupported_type_variable.ml
- test/ppx_irmin/deriver/passing/dune.inc
- test/ppx_irmin/deriver/passing/type_params.expected
- test/ppx_irmin/deriver/passing/type_params.ml
e.g. the type `('a, 'b) t` is represented as `'a typ -> 'b typ -> ('a, 'b) t typ`.
> ppx_irmin: add support for higher-kinded types

- CHANGES.md
- README_PPX.md
- src/ppx_irmin/deriver/ppx_irmin.ml
- src/ppx_irmin/lib/deriver.ml
- src/ppx_irmin/lib/deriver.mli
Allow the `lib` argument to be set globally by passing a command-line flag.  This will be helpful when using `ppx_irmin` inside `irmin` itself.
> ppx_irmin: add --lib command-line flag

- irmin-bench.opam
- irmin-chunk.opam
- irmin-containers.opam
- irmin-fs.opam
- irmin-git.opam
- irmin-graphql.opam
- irmin-http.opam
- irmin-layers.opam
- irmin-mem.opam
- irmin-mirage-git.opam
- irmin-mirage-graphql.opam
- irmin-mirage.opam
- irmin-pack.opam
- irmin-test.opam
- irmin-type.opam
- irmin-unix.opam
- irmin.opam
- ppx_irmin.opam
As discussed offline, the plan is to conduct simultaneous releases of all Irmin packages in future. This PR adds `{= version}` constraints to avoid us needing to manually maintain individual version bounds for each internal dependency (since we have no tooling capable of enabling this).
Dpeends on https://github.com/mirage/irmin/pull/1100.
> Add {= version} constraints on all internal dependencies

- CHANGES.md
- examples/custom_merge.ml
- src/irmin-git/irmin_git.ml
- src/irmin-type/type.ml
- src/irmin-type/type.mli
- src/irmin/contents.ml
- src/irmin/hash.ml
- src/irmin/irmin.mli
- src/irmin/path.ml
- src/irmin/store.ml
- test/irmin-type/test.ml
This splits the existing `~cli` argument to the `Type.{v,like,map}` constructors into two separate arguments `~pp` and `~of_string`. The original naming seems to be legacy from the original use of these operations for the `irmin-unix` CLI. 
When using typereps for pretty-printing only (e.g. for debugging / testing), it's helpful to be able to quickly override `~pp` (even if this means that `pp` and `of_string` are no longer inverses).
> irmin-type: allow `pp` and `of_string` to be overridden separately

- Makefile
A quick fix to Makefile targets.
Follow-up to #1100; removing target entirely in anticipation of #1106.
(skipping changelog to match #1100)
> Remove inaccurate benchmark target

- src/irmin-layers/irmin_layers.ml
- src/irmin-layers/irmin_layers_intf.ml
- src/irmin-layers/stats.ml
- src/irmin-layers/stats.mli
- src/irmin-pack/inode_layers.ml
- src/irmin-pack/inode_layers_intf.ml
- src/irmin-pack/irmin_pack_layers.ml
- src/irmin-pack/layered_store.ml
- src/irmin-pack/pack_index.ml
- src/irmin-pack/pack_intf.ml
- src/irmin-test/layered_store.ml
- src/irmin/commit.ml
- src/irmin/dune
- src/irmin/node.ml
- src/irmin/object_graph.ml
- src/irmin/object_graph.mli
- test/irmin-pack/layered.ml
Adds a `self_contained` function to make the upper layer self contained. When we have a simple store (i.e. not layered) as for instance in the benchmarks, we might want to make the upper layer self contained. Unfortunately, I cannot use it for the benchmarks, because I don't know the `min`, `max` commits (and I tried to guess them with no success), but it could be useful for the migration process.
Some other fixes as well, that are all independent of which type of upper layer we use, they will be useful for https://github.com/mirage/irmin/pull/1099 as well.
> Build a self contained upper, and some other fixes

- src/irmin-layers/irmin_layers.ml
- src/irmin-layers/irmin_layers_intf.ml
- src/irmin-pack/IO.ml
- src/irmin-pack/IO.mli
- src/irmin-pack/IO_layers.ml
- src/irmin-pack/IO_layers.mli
- src/irmin-pack/closeable.ml
- src/irmin-pack/inode_intf.ml
- src/irmin-pack/inode_layers.ml
- src/irmin-pack/inode_layers_intf.ml
- src/irmin-pack/irmin_pack_layers.ml
- src/irmin-pack/layered_store.ml
- src/irmin-pack/pack.ml
- src/irmin-pack/pack_intf.ml
- src/irmin-pack/s.ml
- src/irmin-pack/store.ml
- test/irmin-pack/test_existing_stores.ml
The recovery mechanism needs a `clear` that does not change the generation for the files on disk. 
I had to introduce an extra `clear_keep_generation` function in the pack to avoid adding a `keep_generation` argument to clear functions for backends other than irmin-pack.
> Recovery mechanism for freeze

- src/irmin-pack/inode_layers.ml
- src/irmin-pack/inode_layers_intf.ml
- src/irmin-pack/irmin_pack.mli
- src/irmin-pack/irmin_pack_layers.ml
- src/irmin-pack/irmin_pack_layers.mli
- src/irmin-pack/layered_store.ml
- src/irmin-pack/pack_intf.ml
- src/irmin-pack/s.ml
- src/irmin-test/layered_store.ml
- src/irmin-test/store.ml
- src/irmin/node.ml
- src/irmin/s.ml
- src/irmin/store_intf.ml
Before this PR, newies (the objects added in upper during a concurrent freeze) were copied in the next upper, without being traversed. However, a "newie" can include an object still present in upper but deleted at the end of the freeze. Therefore we have to traverse the newies as well when copying them to the next upper, to ensure the upper remains self contained.
Also included a `skip_contents` function for a node's graph traversal, to prevent unnecessary visits of contents.
> Traverse newies

- src/irmin/s.ml
- src/irmin/store_intf.ml
> doc: do not link to refer to private modules in doc strings.

- CHANGES.md
- src/irmin-chunk/irmin_chunk.ml
- src/irmin-git/irmin_git.ml
- src/irmin-pack/inode.ml
- src/irmin-pack/inode_layers.ml
- src/irmin-pack/irmin_pack_layers.ml
- src/irmin-pack/pack.ml
- src/irmin-pack/pack_index.ml
- src/irmin-pack/store.ml
- src/irmin/node.ml
- src/irmin/store.ml
- src/irmin/tree.ml
> Stage Type.equal

- src/irmin-pack/irmin_pack_layers.ml
- test/irmin-pack/bench_layers.ml
- test/irmin-pack/dune
The benchmark for the layered store is similar to the tezos use case: each commit adds on average 100 objects with one freeze per cycle which copies the last 5 cycles, the size of the upper after 5 cycles is 400M
> Bench layers is closer to the tezos usecase

- CHANGES.md
- src/irmin-pack/irmin_pack_layers.ml
- src/irmin-test/store.ml
- src/irmin/commit.ml
- src/irmin/dot.ml
- src/irmin/node.ml
- src/irmin/object_graph.ml
- src/irmin/object_graph.mli
- src/irmin/s.ml
- src/irmin/store.ml
- src/irmin/store_intf.ml
It allows to iterate efficiently over the object graph.
Extracted from #1124
> irmin: add Repo.iter

- test/irmin-pack/bench_layers.ml
- test/irmin-pack/dune
Looks like we've recently added a dependency on the `memtrace` package (without adding it into an `opam` file). Unfortunately, we can't afford this dependency on the main `irmin-pack.opam` file (even as a test dependency), since it would prevent us from being able to test on the version of OCaml currently used in Tezos.
> irmin-pack: remove dependency on memtrace

- src/irmin-layers/dune
- src/irmin-layers/irmin_layers.ml
- src/irmin-layers/irmin_layers_intf.ml
- src/irmin-pack/inode_layers_intf.ml
- src/irmin-pack/irmin_pack_layers.ml
- src/irmin-pack/irmin_pack_layers.mli
- src/irmin-pack/pack_intf.ml
- src/irmin-test/layered_store.ml
- test/irmin-pack/layered.ml
- test/irmin-pack/test_existing_stores.ml
Just refactoring to avoid duplication of layer IDs and cleanup some testing logic.
> irmin-layers: define layer IDs in one place

- CHANGES.md
- Makefile
- bench/irmin-pack/dune
- bench/irmin-pack/layers.ml
- irmin-bench.opam
@icristescu suggested 2005 as the number of commits since every 1000 commits, a tree is committed and there's 2 freeze cycles so that time can also be taken into account, I'd be open to just using the default value as well.
> Add json output and make target for benchmarking layered store.

- CHANGES.md
- src/irmin/hash.ml
- test/irmin/test.ml
- test/irmin/test_hash.ml
- test/irmin/test_hash.mli
This changes the function used to compute `short_hash ~seed:None` to be more efficient.
> irmin: use an optimized short hash function for crypto hashes

- CHANGES.md
- bench/irmin-pack/layers.ml
- src/irmin-pack/irmin_pack.ml
- src/irmin-pack/irmin_pack.mli
- test/irmin-pack/cli/generate.ml
- test/irmin-pack/cli/irmin_fsck.ml
- test/irmin-pack/layered.ml
- test/irmin-pack/test_existing_stores.ml
- test/irmin-pack/test_pack.ml
- exposes the `Checks` module, which I forgot to do in https://github.com/mirage/irmin/pull/1141;
- exposes a module type for the layered store, and moves this into its own `Layered` namespace.
This is the necessary counterpart of https://github.com/tarides/tezos/pull/7.
> irmin-pack: expose Checks module and Layered.S module type

- CHANGES.md
- src/irmin-pack/irmin_pack_layers.ml
- src/irmin-pack/layered_store.ml
- src/irmin/store.ml
- src/irmin/store_intf.ml
> irmin-pack: use Repo.iter to speed-up copies between layers

- CHANGES.md
- src/irmin-pack/inode.ml
- src/irmin-pack/inode_intf.ml
- src/irmin-pack/inode_layers.ml
- src/irmin-pack/inode_layers_intf.ml
- src/irmin-pack/irmin_pack_layers.ml
- src/irmin-pack/layered_store.ml
- src/irmin-pack/pack_intf.ml
- src/irmin/store.ml
- src/irmin/store_intf.ml
(extracted from #1124)
(on top of #1150)
before:
```
▶ dune exec -- ./bench/irmin-pack/layers.exe -n 100
1500 commits completed in 9.30s.
[0.006s per commit, 161 commits per second]
```
after:
```
▶ dune exec -- ./bench/irmin-pack/layers.exe -n 100
1500 commits completed in 7.54s.
[0.005s per commit, 199 commits per second]
```
>  irmin-pack: do not recompute hashes on copy 

- CHANGES.md
- src/irmin-pack/closeable.ml
- src/irmin-pack/inode.ml
- src/irmin-pack/inode_layers.ml
- src/irmin-pack/layered_store.ml
- src/irmin-pack/pack.ml
- src/irmin-pack/pack_intf.ml
> irmin-pack: add an (unsafe) option to bypass data integrity checks on reads

- src/irmin-pack/irmin_pack_layers.ml
Pinning `irmin-pack` and `irmin-layers` on master on a `4.09` switch, fails due to a mismatch in the `check_self_contained` function. Also (on my machine at least) it compiles fine with `4.11`, but not with `4.09`, I'm not sure why it's not picked up by the CI.
> Fix opam pin

- src/irmin-pack/closeable.ml
- src/irmin-pack/inode.ml
- src/irmin-pack/inode_layers.ml
- src/irmin-pack/layered_store.ml
- src/irmin-pack/pack.ml
- src/irmin-pack/pack_intf.ml
- test/irmin-pack/test_pack.ml
before:
```
▶ time dune exec -- ./bench/irmin-pack/layers.exe -n 300
4500 commits completed in 30.63s.
[0.007s per commit, 147 commits per second]
dune exec -- ./bench/irmin-pack/layers.exe -n 300  24.61s user 6.61s system 97% cpu 32.100 total
```
after:
```
▶ time dune exec -- ./bench/irmin-pack/layers.exe -n 300
4500 commits completed in 27.53s.
[0.006s per commit, 163 commits per second]
dune exec -- ./bench/irmin-pack/layers.exe -n 300  21.97s user 6.12s system 99% cpu 28.245 total
```
> irmin-pack: faster copies

- CHANGES.md
- src/irmin/hash.ml
- test/irmin/test_hash.ml
This reverts commit bd53984a9390c953bab523a4768edde1c562c781.
See #1164
> Revert "irmin: use an optimized short hash function for crypto hashes"

- CHANGES.md
- src/irmin/store.ml
As explained in this [issue](https://github.com/mirage/irmin/issues/1109), the current implementation of the function `last_modified` doesn't consider the case of a key creation as a modification.
After discussing a bit about it with @pascutto, it seems that this was not the intended behaviour. This PR simply adds the case in the pattern matching.
> Considering key creation case in last_modified

- src/irmin-pack/inode.ml
before:
```
▶ dune exec -- ./bench/irmin-pack/layers.exe -n 300
4500 commits completed in 29.51s.
[0.007s per commit, 153 commits per second]
```
after:
```
▶ dune exec -- ./bench/irmin-pack/layers.exe -n 300
4500 commits completed in 27.66s.
[0.006s per commit, 163 commits per second]
```
> irmin-pack: allocate less in inodes

- CHANGES.md
- src/irmin-unix/cli.ml
- src/irmin-unix/resolver.ml
Fixes #934
I re-used some code from the internal dune XDG library since it seemed to handle Windows correctly, but I don't have a Windows machine and can't verify. If Windows support isn't necessary then I can remove that part altogether.
> Fix irmin-unix config path to respect XDG_CONFIG_HOME

- src/irmin-pack/inode_layers_intf.ml
- src/irmin-pack/irmin_pack_layers.ml
- src/irmin-pack/layered_store.ml
- src/irmin-pack/pack_intf.ml
Only print one debug line instead of two.
> irmin-pack: restructure the error messages a bit in case of add+freeze

- CHANGES.md
- src/irmin/tree.ml
This adds polymorphic type annotations to many of the CPS-ed fold functions in `tree.ml`, ensuring that they call the continuation appropriately. This catches the bug fixed by https://github.com/mirage/irmin/pull/1174, and so is rebased on that.
> irmin: ensure that fold functions are polymorphic in their continuation

- src/irmin-pack/irmin_pack.ml
This avoids quite a bit of allocation during the Index reconstruction.
> irmin-pack: correctly stage reconstruction decoders

- CHANGES.md
- src/irmin-test/store.ml
- src/irmin/tree.ml
- src/irmin/tree_intf.ml
- test/irmin/test_tree.ml
This adds various tests of `Tree.fold` (particularly of the `~force` parameter), and strengthens the test of `Tree.clear`. Like https://github.com/mirage/irmin/pull/1180, this witnesses the bug fixed by https://github.com/mirage/irmin/pull/1174 and so is based on that.
Fix https://github.com/mirage/irmin/issues/1175.
> irmin: add tests of `Tree.fold ~force`

- bench/irmin-pack/layers.ml
- src/irmin-pack/config.ml
- src/irmin-pack/config.mli
- src/irmin-pack/irmin_pack.ml
- src/irmin-pack/irmin_pack.mli
- src/irmin-pack/irmin_pack_layers.ml
This simply discard new `freeze` operations until the current freeze is completed.
Fixes #1156 
The results are impressive, as we are doing way less freezes:
```
» time dune exec -- ./bench/irmin-pack/layers.exe -n 300
Running benchmarks in bench/irmin-pack/layers.ml:
{ ncommits = 300;
ncycles = 10;
depth = 10;
root = "test-bench";
clear = false;
no_freeze = false;
show_stats = false;
freeze_throttle = Block_writes }
+1607450672us [WARNING] irmin.layers freeze blocked for 1.382350 seconds due to a previous unfinished freeze
+1607450675us [WARNING] irmin.layers freeze blocked for 1.879525 seconds due to a previous unfinished freeze
+1607450677us [WARNING] irmin.layers freeze blocked for 2.189845 seconds due to a previous unfinished freeze
+1607450680us [WARNING] irmin.layers freeze blocked …
```
> irmin-pack: add a memory overcommit option for freeze

- bench/irmin-pack/layers.ml
- src/irmin-pack/irmin_pack_layers.ml
The layered store used the index with a `log_size` 4 times larger than the one passed on as argument. This was to prevent blocking merges during a freeze without using `index_throttle:Overcommit_memory`. 
In PR https://github.com/mirage/irmin/pull/1183 no merge is triggered during a freeze; a merge is called only at the end of the freeze. So we can revert the `log_size` to its normal value, for all operations not caused by freeze.
I also removed `index_throttle:Overcommit_memory` from the layers benchmark: we are not using this option in tezos; and we cannot see the effects when reducing the `log_size` with this option on.
> Revert log size to normal value

- .ocamlformat
- src/irmin-git/irmin_git.ml
- src/irmin-graphql/server.ml
- src/irmin-pack/inode.ml
- src/irmin-test/store.ml
- src/irmin-unix/cli.ml
- test/irmin-git/test_git.ml
Hi, this pull-request is a preview of the soon to be released ocamlformat.0.16.0. The main changes in this diff are:
- the indentation of module includes has been fixed;
- the cases of anonymous functions are all properly broken.
Let me now if you notice any regressions.
> Preview of ocamlformat.0.16.0

- CHANGES.md
- src/irmin-pack/checks.ml
- src/irmin-pack/checks_intf.ml
- src/irmin-pack/irmin_pack_layers.ml
- src/irmin-pack/irmin_pack_layers.mli
- test/irmin-pack/cli/irmin-fsck-help.txt
- test/irmin-pack/test_existing_stores.ml
- Adds an `integrity-check` command to `irmin-fsck`
- Updates `src/irmin-pack/checks_intf.ml` with `Integrity_check` and `Reconstruct_index` definitions
* Needed for https://github.com/tarides/tezos/issues/8
- Closes #1195 
- Updates `Irmin_pack_layers.S.check_integrity` function return type
> Add integrity-check command to irmin-fsck

- src/irmin-pack/irmin_pack_layers.ml
- src/irmin-pack/pack.ml
- src/irmin/irmin.ml
- src/irmin/irmin.mli
- src/irmin/lru.ml
- src/irmin/lru.mli
- src/irmin/object_graph.ml
- src/irmin/object_graph.mli
- src/irmin/store.ml
- src/irmin/store_intf.ml
Alternative implementation of #1122 ; that seems to work as expected but I haven't benchmarked / tested this extensively.
> irmin: add a LRU cache to Repo.iter

- src/irmin-pack/inode_layers.ml
- src/irmin-pack/inode_layers_intf.ml
- src/irmin-pack/irmin_pack_layers.ml
- src/irmin-pack/layered_store.ml
- src/irmin-pack/pack_intf.ml
- src/irmin-pack/s.ml
Experimenting with another way to reduce the number of `newies`: only track the new commits and let `Repo.iter` complete the missing ones :-)
But this doesn't pass the tests and I am not sure why..
> irmin-pack: only remember commits in `newies'

- src/irmin-pack/pack.ml
- src/irmin/lru.ml
- src/irmin/lru.mli
- src/irmin/object_graph.ml
- src/irmin/object_graph.mli
This is an alternative implementation of #1166 but where only the in-memory structures are using the optimised hash. That'll ensure that the order of index entries is not modified (e.g. no diff in `irmin-pack/pack_index.ml`)
> irmin: always use short hashes for in-memory caches

- src/irmin-pack/irmin_pack_layers.ml
- src/irmin-pack/layered_store.ml
- src/irmin-pack/layered_store.mli
Show on which upper a freeze take places.
e.g.:
```
+1608311296us [INFO] irmin-pack [upper1] freeze cancelled { id=9; total-duration=17.824ms; freeze-lock=893us }
```
> irmin-pack: improve log messages

- src/irmin-pack/irmin_pack_layers.ml
These seem to be the last remaining hotspots of allocation in the recent traces.
Not totally sure about all of the changes, but they seem to make a difference.
Before:
```
▶ dune exec -- ./bench/irmin-pack/layers.exe -n 300
4500 commits completed in 28.02s.
[0.006s per commit, 161 commits per second]
```
After:
```
▶ dune exec -- ./bench/irmin-pack/layers.exe -n 300
4500 commits completed in 24.35s.
[0.005s per commit, 185 commits per second]
```
> irmin-pack: allocate less

- irmin-pack.opam
- src/irmin-pack/pack.ml
Always add entries with overcommit=true and try to do a merge at the end of a
batch. This ensures writes are done in "batches" without index locks
interfering.
> irmin-pack: try to call merges less often

- src/irmin-pack/inode.ml
- src/irmin-pack/inode_intf.ml
- src/irmin-pack/inode_layers.ml
- src/irmin-pack/layered_store.ml
- src/irmin-pack/pack_intf.ml
This causes a (very small) difference but simplifies the code.
```
(remove-pause) [0.002s per commit, 474 commits per second]
(master) [0.002s per commit, 469 commits per second]
```
> Remove Lwt.pause in inodes

- CHANGES.md
- src/irmin-pack/checks.ml
- src/irmin-pack/checks_intf.ml
Adds an optional `heads` argument to `check-self-contained` command in `irmin-pack` checks. This will be needed to enable some updates to the tezis-node CLI.
> Add heads argument to check-self-contained command

- CHANGES.md
- examples/deploy.ml
- examples/process.ml
- irmin-git.opam
- irmin-http.opam
- irmin-mirage-git.opam
- irmin-mirage-graphql.opam
- irmin-unix.opam
- src/irmin-git/irmin_git.ml
- src/irmin-git/irmin_git.mli
- src/irmin-mirage/git/dune
- src/irmin-mirage/git/irmin_mirage_git.ml
- src/irmin-mirage/git/irmin_mirage_git.mli
- src/irmin-mirage/graphql/dune
- src/irmin-mirage/graphql/irmin_mirage_graphql.ml
- src/irmin-mirage/graphql/irmin_mirage_graphql.mli
- src/irmin-unix/cli.ml
- src/irmin-unix/dune
- src/irmin-unix/graphql.ml
- src/irmin-unix/irmin_unix.mli
- src/irmin-unix/resolver.ml
- src/irmin-unix/resolver.mli
- src/irmin-unix/xgit.ml
- src/irmin-unix/xgit.mli
- test/irmin-git/dune
- test/irmin-git/test_git.ml
- test/irmin-unix/test_unix.ml
This is a draft about an update to the new version of git presented on mirage/ocaml-git#395 and the new version of conduit presented on mirage/ocaml-conduit#311 (including patches into mirage/ocaml-cohttp#692). I think the patch is small enough. The CI will fail but locally (with a `pin` of `conduit` and `cohttp` and a simple `dune runtest`) it's work (believe me).
This is a draft but people can start to comment it if some details are obscures. Currently, the biggest change is about the synchronization where I updated the interface which seems to be much more simpler.
> Update irmin to the last version of ocaml-git

- src/irmin-pack/IO.ml
- src/irmin-pack/IO.mli
- src/irmin-pack/dict.ml
- src/irmin-pack/dict_intf.ml
- src/irmin-pack/ext.ml
- src/irmin-pack/ext.mli
- src/irmin-pack/irmin_pack.ml
- src/irmin-pack/irmin_pack.mli
- src/irmin-pack/layered/irmin_pack_layered.ml
- src/irmin-pack/pack.ml
- src/irmin-pack/pack_dict.ml
- src/irmin-pack/pack_dict.mli
- src/irmin-pack/pack_intf.ml
- src/irmin-pack/store.ml
- src/irmin-pack/store_intf.ml
- test/irmin-pack/cli/irmin_fsck.ml
- test/irmin-pack/common.ml
- test/irmin-pack/common.mli
- test/irmin-pack/layered.ml
- test/irmin-pack/multiple_instances.ml
- test/irmin-pack/test_existing_stores.ml
- test/irmin-pack/test_pack.ml
During the 2.2.0 → 2.3.0 transition, we added a generation number header to the Pack file in order to support a `clear` operation needed by `irmin-layers`.
At the time, we broke compatibility with pre-2.3.0 stores and provided an automatic migration. However, since the next release of Tezos will not use the layered stores – at least by default – it's helpful to have access to V1-era pack files so as to not force an unnecessary migration on Tezos users. This PR does this in the simplest way I could imagine: having the `Pack.File` functor take an IO version to use, which is set to `V1` in `irmin-pack` and `V2` in `irmin-pack.layered`.
> irmin-pack: retain compatibility with V1 IO

- CHANGES.md
- src/irmin-git/irmin_git.ml
- src/irmin-graphql/server.ml
- src/irmin-mirage/git/irmin_mirage_git.ml
- src/irmin-pack/inode.ml
- src/irmin-test/layered_store.ml
- src/irmin-test/store.ml
- src/irmin-unix/cli.ml
- src/irmin/node.ml
- src/irmin/s.ml
- src/irmin/store_intf.ml
- src/irmin/tree.ml
- src/irmin/tree_intf.ml
- test/irmin-pack/cli/stat.t/run.t
- test/irmin/test_tree.ml
This PR adds paginated lists. 
The element order of `list` is not specified anymore (as the paginated lists will fold over the underlying structure) but it is guaranteed to be stable.
> Add paginated lists

- ppx_irmin.opam
- src/ppx_irmin/dune
These are a hold over from before the extraction of `ppx_repr`, and are no longer accurate thanks to https://github.com/mirage/repr/pull/35.
> ppx_irmin: remove unnecessary dependencies

- CHANGES.md
- src/irmin-pack/inode.ml
- src/irmin-pack/inode_intf.ml
- test/irmin-pack/common.ml
- test/irmin-pack/common.mli
- test/irmin-pack/test_inode.ml
Add a test to assert representation uniqueness after an [add]/[remove] for all trees up to depth=3.
Without the fix on `inode.ml`, the test fails with:
```
FAIL The representation of a tree obtained through [remove] differs from the one obtained through [v].
Expected: `
{'hash': 'Samuel~~',
'stable': True,
'v': {'Inodes': {'entries': [{'Inode': {'hash': 'Darcy~~~',
'tree': {'hash': 'Darcy~~~',
'stable': False,
'v': {'Inodes': {'entries': [{'Inode': {'hash': 'Robert~~',
'tree': {'hash': 'Robert~~',
'stable': False,
'v': {'Values': [['e', {'contents': 'Ruth~~~~'}],
['n', {'contents': 'Michael~'}]]}}}},
{'Inode': {'hash': 'Brad~~~~',
'tree': {'hash': 'Brad~~~~',
'stable': False,
'v': {'Values': [['j', {'contents': 'Stephen~'}]]}}}}],
'length': 3,
'seed': 1}}}}},
'Empty'],
'length': 3, …
```
> Test and fix representation uniqueness of inode

- src/irmin-test/store.ml
As suggested in https://github.com/mirage/irmin/pull/1241#discussion_r555676980. A bit late for https://github.com/mirage/irmin/pull/1241, but could be useful for future inode/tree refactoring. 
However, it takes around 4 minutes to run for irmin-pack, so I marked it `Slow`. (I tried smaller nodes, but they don't trigger stack overflow for incorrect usage of `List.map`.)
> Add test for wide nodes

- CHANGES.md
- bench/irmin-pack/bench_common.ml
- bench/irmin-pack/bench_common.mli
- bench/irmin-pack/dune
- bench/irmin-pack/layers.ml
- bench/irmin-pack/tree.ml
- irmin-bench.opam
Not sure what are the best benchmarks for inodes, I'm introducing three modes here for now:
- ` dune exec -- ./bench/irmin-pack/tree.exe --mode=tezos-log `
consists of mimicking tezos tree operations: `tezos.log` contains the tree add and remove operations for the first 21480 commits of a bootstrap. Each commit starts with an empty tree.
- Add large trees
```
dune exec -- ./bench/irmin-pack/tree.exe --mode=large --width=1000000 --nlarge=1 --ncommits=2
+1610285517us  application Large trees mode: 2 commits, each consisting of 1 large trees of 1000000 entries completed in 76.20s
+1610285517us: total size of store : 237 M
```
- Add long trees 
```
dune exec -- ./bench/irmin-pack/tree.exe --mode=chains --depth=1000000 --nchain=3 --ncommits=2
+1610285741us  application Chain trees mode: 2 …
```
> Add benchmarks for trees

- CHANGES.md
- src/irmin/tree.ml
We don't want to recursively explore the parameters to check if
add_tree is a no-op (to try to preserve physical equality). The
cost is too high in this case.
Spotted by @camlspotter and profiled by @CraigFe and @Ngoguey42
> Tree: fix add_tree to be constant-time

- CHANGES.md
- src/irmin-test/common.ml
- src/irmin-test/store.ml
- src/irmin/tree.ml
- src/irmin/tree_intf.ml
- test/irmin/dune
- test/irmin/test.ml
- test/irmin/test_tree.ml
Resolves https://github.com/mirage/irmin/issues/1270.
`Tree.update_tree` is quite complicated, with many edge cases that I've tried to test as much as is practical. Fortunately, the functions `Tree.add`, `Tree.add_tree`, `Tree.remove` and `Tree.update` can all be implemented in terms of it with little to no performance cost, which I've done here.
> Implement Tree.update and Tree.update_tree

- test/irmin-mem/dune
This is necessary to avoid a cycle between the `irmin` and `irmin-test` packages.
> irmin: attach irmin-mem tests to irmin-test package

- CHANGES.md
- irmin-graphql.opam
- src/irmin-graphql/server.ml
- src/irmin-test/common.ml
- src/irmin-test/layered_store.ml
- src/irmin-test/store.ml
- src/irmin/store.ml
- src/irmin/store_intf.ml
- src/irmin/tree.ml
- src/irmin/tree_intf.ml
- test/irmin-graphql/dune
- test/irmin-graphql/test.ml
- test/irmin/test_tree.ml
This changes the type of trees to support lazy contents values:
```diff
- type t = Node of lazy_node | Contents of blob * metadata
+ type t = Node of lazy_node | Contents of lazy_contents
```
This means that contents are (internally) handled symmetrically to nodes: as unforced pointers to values in the underlying stores wherever possible. The user-facing changes are: 
- `Tree.destruct` returns unforced contents pointers that can be dereferenced with `Tree.Contents.force`.
- `Tree.of_hash` and `Tree.shallow` now take _kinded_ hashes with appropriate metadata.
This is motivated by https://github.com/mirage/irmin/issues/1284, which stems from the fact that we don't currently support "shallow" tree leaves. With this change, it's easy to extend `Tree.shallow` to support this, and I've added …
> Change Tree.t representation to use lazy contents values

- CHANGES.md
- bench/irmin-pack/bench_common.ml
- bench/irmin-pack/bench_common.mli
- bench/irmin-pack/dune
- bench/irmin-pack/tree.ml
- irmin-bench.opam
Diff 1: `--quick` is now `--mode quick`, and `--mode` gives more choices.
Diff 2: The configurations for the `quick` and `slow` modes are now hard coded and can't be changed from the CLI. The other modes can be configured from the CLI.
Diff 3: Add `--flatten` for trace mode to collapse the 6 step-long hashes to single steps. 
Diff 4: Add a progress bar using https://github.com/CraigFe/progress
Diff 5: Trace mode now tracks the time spent by the 8 unitary operation, using mtime and https://github.com/barko/bentov (more info in tree.ml).
I also have a python script to plot the histograms
> More features in bench/tree.exe

- CHANGES.md
- src/irmin/import.ml
- src/irmin/tree.ml
Resolves #1272
Commit it now ~14 times quicker, it is repaired.
Remove is now only ~3 times quicker because of the poor implementation of `Tree.Node.is_empty`. 
```
dune exec -- ./bench/irmin-pack/tree.exe --mode trace --inode-config 32 --flatten  ~/boostrap_trace.json
Replaying trace  13300/13315 commits  09:16  [##########################.]  99%
Tezos_log mode on inode config [32, 256]: 13315 commits
895827 "Add" 2.376 sec (0.4%)
54196 "Remove" 204.781 sec (37.1%)
2950152 "Find" 12.638 sec (2.3%)
669692 "Mem" 2.185 sec (0.4%)
439329 "Mem_tree" 0.528 sec (0.1%)
13314 "Checkout" 0.029 sec (0.0%)
59 "Copy" 0.000 sec (0.0%)
13315 "Commit" 329.685 sec (59.7%)
Total time: 551.869637
Size on disk: 114 M
```
```
dune exec -- ./bench/irmin-pack/tree.exe --mode trace --inode-config 32 --flatten …
```
> Tree.remove scaling

- src/irmin/dune
Adding `ppx_irmin` to the `libraries` field break cross-compilation as it's introduced as a _runtime_ dependency. 
The solution is to simply remove it, as it's already inferred from the `preprocess` field.
> Remove ppx_irmin runtime dependency

- src/irmin/import.ml
- src/irmin/tree.ml
Tiny fixup for consistency; we should probably use `import.ml` for all such extensions in future.
> irmin: move list_is_longer_than to List extension

- bench/irmin-pack/layers.ml
- src/irmin-layers/stats.ml
- src/irmin-layers/stats.mli
- src/irmin-pack/layered/ext_layered.ml
- src/irmin-test/layered_store.ml
```
freeze 0 blocked 40.672s (35%), and yielded 1min15s (65%). Total 1min56s.
Event counts: copy_contents:208847, copy_nodes:1465555, copy_commits:13315, copy_branches:0, adds:1312338, skips:2369230, yields:13316, copy_newies_loops:1
Longest block 3.454s (during "copy newies (loop)"). Longest yield 1min15s (during "copy to lower"). 114.231 yield per sec.
Timeline:
wait for freeze lock took 1.27us (0% of total) and blocked 0.873us (0% of total).
misc took 471us (0% of total) and blocked 471us (0% of total).
copy to lower took 1min20s (69% of total) and blocked 4.661s (11% of total).
copy to next upper took 0.299us (0% of total) and blocked 0.291us (0% of total).
copy branches took 3.791us (0% of total) and blocked 3.792us (0% of total).
flush lower took 131us (0% of total) and blocked …
```
> irmin-layered: New fancy stats for freeze

- CHANGES.md
- irmin-layers.opam
- ppx_irmin.opam
Corresponding `opam-repository` PR: https://github.com/ocaml/opam-repository/pull/18168
> Prepare 2.5.0 release

- CHANGES.md
- irmin-git.opam
- irmin-mirage-git.opam
- irmin-unix.opam
- src/irmin-git/irmin_git.ml
`ocaml-git` updates the interfaces to fix #917 at the `ocaml-git` level. That mostly means that the hack into `irmin` to produce well formed commit is not needed anymore.
> A git commit expects a string option now

- CHANGES.md
- src/irmin-pack/inode.ml
- test/irmin-pack/dune
- test/irmin-pack/test_inode.ml
Resolves https://github.com/mirage/irmin/issues/1266.
irmin-pack: adapt inode.ml to acknowledge root inodes that are not directory roots
- [Conf.entries <= Conf.stable_hash] is now an invariant.
- Can now detect and raise when an inodes that isn't the root of directory attempts a write-only operation.
- Add Val_impl.is_root.
> irmin-pack: Inode detect non roots

- CHANGES.md
- bench/irmin-pack/tree.ml
TLDR ; Freeze is extremely sensible to cooperative yields
Test setup: 
- `dune exec -- ./bench/irmin-pack/tree.exe --mode trace --inode-config 32 ~/boostrap_trace.json`.
- Using a layered store.
- 13315 commits total.
- By default, one freeze launched after commit 1664.
- By default, main thread doesn't yield control.
- By default, freeze thread yields control every time it hits a commit.
- After the 13315 commits, we wait for the freeze to end, if still ongoing.
As soon as freeze calls Lwt.pause (from `copy to lower`), it is never resumed until the end of the main thread.
Lots of newies.
```
freeze 0 blocked 40.672s (35%), and yielded 1min15s (65%). Total 1min56s.
Event counts: copy_contents:208847, copy_nodes:1465555, copy_commits:13315, copy_branches:0, adds:1312338, skips:2369230, …
```
> irmin-bench: bench/tree.exe supports layered store

- bench/irmin-pack/tree.ml
Fixes a few places where the configured `width` and `depth` values are being overwritten
> bench/irmin-pack/tree.exe: respect arguments from CLI

- Makefile
- bench/irmin-pack/layers.ml
Removing this target for now as it will get the layers benchmarks in the pipeline, working on getting the `tree` benchmarks in in the meantime.
> Remove non-existent bench target

- CHANGES.md
- src/irmin-pack/inode.ml
- src/irmin-pack/inode_intf.ml
- test/irmin-pack/test_inode.ml
New attempt to serialise and deserialise inodes this time using Irmin.Type
As an example, the current version will transform the following inode (use `json-pretty-print-buffer` in emacs to display it in a human readable way):
```json
{"hash":"46fe6c68a11a6ecd14cbe2d15519b6e5f3ba2864","stable":true,"v":{"Tree":{"depth":0,"length":3,"entries":[null,{"some":{"hash":"3b35271ed01c21d2ffd305eeae99a518c3e979c9","target":{"hash":"3b35271ed01c21d2ffd305eeae99a518c3e979c9","stable":false,"v":{"Tree":{"depth":1,"length":3,"entries":[{"some":{"hash":"1ea663b1d5da857985ae54e6306a9c5203eb57e2","target":{"hash":"1ea663b1d5da857985ae54e6306a9c5203eb57e2","stable":false,"v":{"Tree":{"depth":2,"length":3,"entries":[{"some":{"hash":"4c908006bc050c8ceea78934223332f573ec4eb5","target":{"hash":"4c908006bc050c8c …
```
> irmin-pack: expose internal inode trees

- CHANGES.md
- src/irmin-git/irmin_git.ml
- src/irmin/node.ml
- src/irmin/node_intf.ml
- src/irmin/tree.ml
Alternative to #1257 in order to finish improving the performances of `Tree.remove`.
> Node.length to rescue Tree.is_empty

- CHANGES.md
- bench/irmin-pack/bench_common.ml
- bench/irmin-pack/bench_common.mli
- bench/irmin-pack/layers.ml
- bench/irmin-pack/tree.ml
- The trace used to be a JSON file 
- ⇨ it is now a binary made of repr serialisations.
- The replay used to crash after ~13k commits 
- ⇨ it doesn't crash anymore (tested up to ~654k commits).
- The trace used to be fully loaded in memory before replay (causing memory issues) 
- ⇨ it is now streamed from disk (~84 bytes read per operation).
- The histogram used to be computed live 
- ⇨ the timings are now streamed to disk (4 bytes written per operaration) and processed after replay.
- ⇨ A new plot to highlight performance decay over replay time.
([normal png](https://user-images.githubusercontent.com/9285880/110479219-72fd4880-80e5-11eb-816e-08772777828a.png), [flattened png](https://user-images.githubusercontent.com/9285880/110479252-7c86b080-80e5-11eb-9a5b-7ba409b5d87c.png))
([normal …
> irmin-bench: tree.exe better than ever

- CHANGES.md
- src/irmin-pack/checks.ml
- src/irmin-pack/checks_intf.ml
- src/irmin-pack/layered/checks.ml
- src/irmin-pack/utils.ml
- test/irmin-pack/cli/stat.t/run.t
The command `./tezos-node storage stat-pack --data-dir ../tezos_docs/store/` now returns also the number of objects in the store. It takes `63s` for a `42GB` store.
> irmin-fsck: Add number of objects in stats

- CHANGES.md
- src/irmin/tree.ml
- src/irmin/tree_intf.ml
I need a `Tree.length` to record the size of the largest directory in `bench/irmin-pack/tree.exe`.
2 alternative signatures:
- `val length_exn : node -> int Lwt.t`
- `val length : node -> int or_error Lwt.t`
> irmin: Add Store.Tree.length

- CHANGES.md
- bench/irmin-pack/layers.ml
- src/irmin-layers/irmin_layers.ml
- src/irmin-layers/irmin_layers_intf.ml
- src/irmin-pack/layered/config.ml
- src/irmin-pack/layered/config.mli
- src/irmin-pack/layered/ext_layered.ml
- src/irmin-pack/layered/ext_layered.mli
- src/irmin-pack/layered/irmin_pack_layered.mli
- src/irmin-test/layered_store.ml
- src/irmin-test/store.ml
- test/irmin-pack/cli/generate.ml
- test/irmin-pack/layered.ml
- test/irmin-pack/test_existing_stores.ml
Followup on #1238 and our recent need for a way to specify a different set of `max` commits for the copy to next upper.
I chose to simplify to a maximum:
- Before:  `?min ?max ?squash ?copy_in_upper ?min_upper` (+ `copy_in_upper` in repo config)
- Now: `?min_lower ?max_lower ?min_upper ?max_upper`
Only one change in the default behaviours: the default config of the layered store used to be `copy_in_upper=false`. This parameter is gone, and by default we copy to next upper.
> irmin-layers: Rework freeze API

- bench/irmin-pack/dune
- bench/irmin-pack/tree.ml
- irmin-bench.opam
Same kind of mistake as #1286. Won't happen again!
> irmin-bench: Add tree.exe's compilation to runtest

- .gitignore
- .gitmodules
- CHANGES.md
- bench/irmin-pack/bench_common.ml
- bench/irmin-pack/bench_common.mli
- bench/irmin-pack/dune
- bench/irmin-pack/layers.ml
- bench/irmin-pack/tree.ml
I added an `encoding` package directly in `irmin-pack/bench` and this is a copy of what we have in https://github.com/tarides/tezos-context-hash. I tried depending on that package instead but I got a complaint from dune
```
Error: Conflict between the following libraries:
- "irmin" in _build/default/src/irmin
- "irmin" in /Users/icristes/.opam/itezos/lib/irmin
```
I'm happy to retry if we don't want to duplicate the encodings.
> Check hash of commit in tree benchmarks

- CHANGES.md
- bench/irmin-pack/tree.ml
- src/irmin-pack/IO.ml
- src/irmin-pack/IO_intf.ml
- src/irmin-pack/checks.ml
- src/irmin-pack/checks_intf.ml
- src/irmin-pack/dict.ml
- src/irmin-pack/ext.ml
- src/irmin-pack/ext.mli
- src/irmin-pack/irmin_pack.ml
- src/irmin-pack/irmin_pack.mli
- src/irmin-pack/layered/ext_layered.ml
- src/irmin-pack/pack.ml
- src/irmin-pack/pack_dict.ml
- src/irmin-pack/pack_dict.mli
- src/irmin-pack/pack_intf.ml
- src/irmin-pack/store.ml
- src/irmin-pack/store_intf.ml
- src/irmin-pack/version.ml
- src/irmin-pack/version.mli
- test/irmin-pack/cli/irmin_fsck.ml
- test/irmin-pack/common.ml
- test/irmin-pack/multiple_instances.ml
- test/irmin-pack/test_pack.ml
- Rename Version into Version.S (and change `val io_version` to `version`)
- Modify the order of functors to always keep the Version parameter first.
> irmin-pack: add a Version module to help version management

- CHANGES.md
- src/irmin-pack/IO.ml
- src/irmin-pack/IO_intf.ml
- src/irmin-pack/dict.ml
- src/irmin-pack/pack.ml
- src/irmin-pack/store.ml
Pack files do not have generation numbers in V1, so `force_generation` was
always returning a corrupted value, which was forcing a cleanup of all
the existing caches on every sync.
> [2.5] irmin-pack: fix a bad performance regression for read-only instances

- CHANGES.md
- bench/irmin-pack/tree.ml
extracted from #1332
Introduces the `--path_conversion` parameter to `tree.exe`. The possible values are `none`, `v0`, `v1`, `v0+v1`.
Notation:
- `\d` is `[0-9]`
- `\x` is `[0-9a-f]`
The patterns:
- `v1`: from:`"(\x\x/){6}"`, to:`""`, origin:[tezos/tezos/2771](https://gitlab.com/tezos/tezos/-/merge_requests/2771).
- `v0`: from:`"(\x\x/){5}\x{30}/"`, to:`"\x{40}/"`, origin:`tree.exe`'s legacy method.
3 columns:
- Prefix pattern.
- Unique number of directories matching the prefix pattern.
- Average number of unique entries seen, per unique prefix.
| prefix                                                    | dirs | average  | comment                                                                                                      | …
> irmin-bench: Path conversion

- CHANGES.md
- src/irmin-pack/IO.ml
- src/irmin-pack/IO_intf.ml
- src/irmin-pack/dict.ml
- src/irmin-pack/pack.ml
- src/irmin-pack/store.ml
Pack files do not have generation numbers in V1, so `force_generation` was
always returning a corrupted value, which was forcing a cleanup of all
the existing caches on every sync and reloading the dict file from scratch.
This is #1360 applied to `master`.
> irmin-pack: fix a bad performance regression for read-only instances

- src/irmin-pack/inode.ml
- src/irmin-pack/inode_intf.ml
- src/irmin-pack/layered/inode_layers.ml
- src/irmin-pack/layered/layered_store.ml
- src/irmin-pack/layered/s.ml
- src/irmin-pack/pack.ml
- src/irmin-pack/pack_intf.ml
- test/irmin-pack/test_inode.ml
- Rename Inode.Elt to Inode.Raw
- When appropriate, rename encode_bin, to_bin amd of_bin to encode_raw, to_raw
and of_raw.
- Rename Inode.Intermediate to Inode.Internal
> irmin-pack: internal renamings

- CHANGES.md
- src/irmin/tree.ml
- test/irmin/test_tree.ml
This is a quick fix, but we should do a more thorough review of what behaviour these typereps are exposing and provide e.g. `is_empty` explicitly.
> Bugfix: Tree.Node.t needs custom equality semantics

- src/irmin-test/store.ml
If I understand correctly, the default behaviour for `async_exception_hook` is to print a message on the stderr, which seems to be ignored by alcotest (unless we run it with the `--verbose` flag). This PR seems to behave a bit better, as alcotest correctly detects an error in the freeze thread and outputs the corresponding logs. 
It then also needs https://github.com/mirage/alcotest/issues/287 to work properly.
As a side node, it works because the `Repo.close` always waits  for the freeze thread to finish.
> Reraise exception from the async thread

- .ocamlformat
- src/irmin-http/irmin_http_server.ml
This is a preview of the not-yet-released ocamlformat.0.18.0, please wait until the package is published in opam to merge this PR.
The diff is composed of:
- empty lines between one-liner class items are removed (now consistently with structure items and signature items) when `module-item-spacing = compact`
> Preview: upgrade to ocamlformat.0.18.0

- bench/irmin-pack/dune
- bench/irmin-pack/layers.ml
- irmin-bench.opam
I added a slow mode to the benchmarks and removed the overcommit option, to highlight two issues that occur in the tezos benchmarks: 
- without the overcommit option, the merge blocks sometimes;
- we need to add thread yields in the freeze thread to ensure fairness.
> Log maxrss in the layer benchmarks

- bench/irmin-pack/bench_common.ml
- src/irmin-test/dune
- src/irmin-test/irmin_bench.ml
- src/irmin-test/irmin_test.ml
- src/irmin-test/irmin_test.mli
- src/irmin-test/store_watch.ml
Removing them from tests to make them reproducible
Changing them to mtime in benchmakrs to make them more precise
> do not use gettimeofday in the test/benchs

- src/irmin-pack/pack.ml
This reverts commit 587e219351e9a147cb7e3cea281ab025b61098c2.
The implementation of `Index.try_merge` is broken: it will attempt a merge even when one is already running. As a result, whenever a batch was completed, the main thread blocked on the completion of an ongoing merge. This restores the old behaviour until a fix can be written and tested in Index.
> irmin-pack: fix merge blocking issue with batches

- CHANGES.md
- src/irmin-pack/content_addressable.ml
Forward-ports the bugfix currently included only in 2.5.4, and updates the CHANGES to reflect recently released features / bug-fixes.
> Make master consistent with 2.5.4 and 2.6.0 releases

- CHANGES.md
- src/irmin-git/irmin_git.ml
- src/irmin-pack/inode.ml
- src/irmin-pack/inode_intf.ml
- src/irmin-pack/pack.ml
- src/irmin/node.ml
- src/irmin/node_intf.ml
- src/irmin/tree.ml
- test/irmin-pack/test_inode.ml
The UI does a poor job of rendering it, but this is `2.6.1` = merge(`2.6.0`, `2.5.4`)
```
*  2.6.1
|\
* | 2.6.0
| * 2.5.4
|/
* 2.5.3
* 2.5.2
```
cc. @samoht
> Prepare 2.6.1 release

- CHANGES.md
- src/irmin-pack/content_addressable.ml
It's only needed when the pack file is really empty
> irmin-pack: avoid clearing the files too much

- CHANGES.md
- src/irmin-unix/resolver.ml
- src/irmin-unix/resolver.mli
- Raise an exception when a config path is specified but doesn't exist or the the provided YAML file is invalid
- Adds `load_config` function to load `Irmin.config` without opening the store. This is needed for `irmin-client`, where we want the ability to read the existing config to determine store/contents/hash type without actually opening the store
> irmin-unix: A few small changes to Irmin_unix.Resolver

- CHANGES.md
- bench/irmin-pack/dune
- bench/irmin-pack/trace_definitions.ml
- bench/irmin-pack/trace_stat_summary_pp.ml
- bench/irmin-pack/trace_stat_summary_utils.ml
- bench/irmin-pack/trace_stat_summary_utils.mli
- bench/irmin-pack/trace_stats.ml
- bench/irmin-pack/tree.ml
- irmin-bench.opam
- test/irmin-bench/misc.ml
- test/irmin-bench/test.ml
Last PR extracted from #1332
I'm not totally happy with `trace_stat_summary_pp.ml`. I will improve it when new features are needed.
A single summary pretty print:
```
dune exec -- ./bench/irmin-pack/trace_stats.exe pp /data/ngoguey/irmin/_artefacts/master_none/boostrap_summary.json
Hostname        | comanche
Word Size       | 64 bits
Start Time      | 2021/04/15 19:12:54 (GMT)
Inode Config    | mls:32 bf:32 sh:256
Store Type      | pack
Path Conversion | none
Block played count *C                  | 0 (before) |   335874   |   671748   |  1007622   | 1343496 (end)
Blocks progress *C                     |     0%     |    25%     |    50%     |    75%     |     100%
|            |            |            |            |
Wall time elapsed *C                   |        0us |    3h53min | …
```
> irmin-bench: CLI and PP for stat trace

- CHANGES.md
- src/irmin-git/commit.ml
- src/irmin-git/commit.mli
- src/irmin/commit.ml
- src/irmin/commit_intf.ml
This fixes a regression introduced by https://github.com/mirage/irmin/pull/1400 that caused the format of V1 commits to change.
Alternative to https://github.com/mirage/irmin/pull/1428.
> Require specific Info implementation for `Commit.V1`

- src/irmin/dune
This ensures that users have access to `Irmin.Type`, even if they're
using `(implicit_transitive_deps false)` without stating a dependency on
the `repr` library.
> irmin: re-export Repr library

- src/irmin-pack/ext.mli
- src/irmin-pack/irmin_pack.mli
Necessary to compile Tezos with Irmin master.
> irmin-pack: add a missing equality on `info` in `Make_ext`

- CHANGES.md
- bench/irmin-pack/trace_stat_summary.ml
- bench/irmin-pack/trace_stat_summary_pp.ml
This shows a slowdown on the [Copy](https://github.com/mirage/irmin/blob/master/bench/irmin-pack/trace_replay.ml#L212-L215) operation:
```
|       |      min      |       max        |      avg
Copy duration (s)             | jan   | 0.800 µs      |    0.101 ms      |  6.481 µs     
| feb   | 0.868 µs 108% |    0.452 ms 448% |  7.601 µs 117%
| mars  | 0.909 µs 114% |    1.044 ms  10x |  8.547 µs 132%
| april | 1.059 µs 132% |    1.815 ms  18x | 16.110 µs 249%
| may   | 0.967 µs 121% |    2.070 ms  21x | 10.933 µs 169%
```
I'm not 100% sure this is relevant.
<details>
<summary>The full (approximate) diff on PP</summary>
```diff
-- setups --
| jan                       | feb                       | mars                      | april                     | may
Hostname        | …
```
> irmin-bench: More summaries and new tables in PP

- bench/irmin-pack/dune
As of now, if `uutf` or `uucp` are not installed, `printbox.unicode` won't be installed. This behaviour is silent making it really hard to know why dune is complaining about `printbox.unicode` being unavailable. Making `uutf` and `uucp` mandatory dependencies should make it easier:
```
> opam switch create . ocaml-base-compiler -y
> dune external-lib-deps --missing @@default
> dune build
```
> Mandatory dependencies to install printbox.unicode

- CHANGES.md
- bench/irmin-pack/main.ml
- bench/irmin-pack/tree.ml
- src/irmin-pack/checks.ml
- src/irmin-pack/irmin_pack.ml
- src/irmin-pack/layered/ext_layered.ml
- src/irmin-pack/version.ml
- src/irmin-pack/version.mli
- test/irmin-bench/replay.ml
- test/irmin-pack/common.ml
- test/irmin-pack/multiple_instances.ml
- test/irmin-pack/test_pack.ml
More refactoring from https://github.com/mirage/irmin/pull/1436.
> irmin-pack: provide `Version.{V1,V2}` modules

- src/irmin-pack/checks.ml
- src/irmin-pack/content_addressable.ml
- src/irmin-pack/content_addressable_intf.ml
- src/irmin-pack/ext.ml
- src/irmin-pack/inode.ml
- src/irmin-pack/inode_intf.ml
- src/irmin-pack/irmin_pack.ml
- src/irmin-pack/irmin_pack_intf.ml
- src/irmin-pack/layered/ext_layered.ml
- src/irmin-pack/layered/layered_store.ml
- src/irmin-pack/layered/s.ml
- src/irmin-pack/pack_index.ml
- src/irmin-pack/pack_index_intf.ml
- src/irmin-pack/pack_value.ml
- src/irmin-pack/pack_value.mli
- src/irmin-pack/pack_value_intf.ml
- test/irmin-pack/common.ml
- test/irmin-pack/test_existing_stores.ml
This is some refactoring extracted from #1436. Does two things:
- uses types for magic chars;
- provides functors for interacting with pack value triplets, avoiding some duplication in `irmin-pack.layered`.
> irmin-pack: extract `Pack_value` abstraction

- CHANGES.md
- irmin-pack.opam
- src/irmin-git/commit.ml
- src/irmin-git/contents.ml
- src/irmin-git/node.ml
- src/irmin-pack/IO.ml
- src/irmin-pack/IO_intf.ml
- src/irmin-pack/checks.ml
- src/irmin-pack/checks_intf.ml
- src/irmin-pack/inode.ml
- src/irmin-pack/inode_intf.ml
- src/irmin-pack/layered/inode_layers.ml
- src/irmin-pack/pack_value.ml
- src/irmin-pack/pack_value_intf.ml
- src/irmin-pack/reconstruct_index.ml
- src/irmin/commit.ml
- src/irmin/contents.ml
- src/irmin/hash.ml
- src/irmin/node.ml
- test/irmin-pack/common.ml
... using the improved `size_of` functions provided by https://github.com/mirage/repr/pull/69.
The new implementation avoids decoding Inode / Node values from the read buffer, which avoids needing to use the path dictionary and reduces the number of allocations significantly. (As a result, certain corruptions of the data file itself will no longer be noticed during index reconstruction, but we have other integrity checks for those.)
Also exposes an `index_log_size` parameter to allow the user to override the default. To compensate for using very large log sizes during reconstruction, we now attempt a manual merge at the end of the process.
> irmin-pack: refactor Index reconstruction implementation

- CHANGES.md
- src/irmin-unix/resolver.ml
- src/irmin-unix/resolver.mli
Currently when using `Irmin_unix.Resolver.load_config` we're only searching in the default paths, this adds a `config_path` argument so a specific configuration file can be loaded.
> irmin-unix: Add `config_path` argument to `Irmin_unix.Resolver.load_config`

- CHANGES.md
- src/irmin-test/store.ml
- src/irmin/tree.ml
- src/irmin/tree_intf.ml
- test/irmin/test_tree.ml
The existing implementation of `Tree` contains several operations that consider "dangling" hashes (internal tree hashes that are `Not_found` in the underlying store) to be equivalent to empty nodes. For instance:
- `Tree.find` at a path that contains a dangling hash will return `None` (and similarly `Tree.mem` returns `false`).
- `Tree.update` at a path that contains a dangling hash will observe a false empty node at the end of the path (... with similar results for `add` / `remove` etc.)
This behaviour can be triggered by the user using `Tree.shallow`, but also arises when the underlying store is corrupt (and certain internal objects can't be found). In each case, silently coercing to an empty node is surprising, and so this commit changes these operations to raise a `Dangling_hash` …
> Avoid implicit coercions of dangling hashes to empty nodes

- bench/irmin-pack/bench_common.ml
- bench/irmin-pack/bench_common.mli
- bench/irmin-pack/dune
- bench/irmin-pack/trace_replay.ml
- bench/irmin-pack/tree.ml
- irmin-bench.opam
- irmin-pack.opam
Let's wait for `progress=0.2.1` before merging
> irmin-bench: Upgrade progress library version

- CHANGES.md
- src/irmin-pack/checks.ml
- src/irmin-pack/traverse_pack_file.ml
- test/irmin-pack/cli/dune
- test/irmin-pack/cli/irmin-fsck-help.txt
- test/irmin-pack/cli/irmin_fsck.ml
- test/irmin-pack/cli/stat.t/run.t
- check a corrupted store
```
time PACK=tezos dune exec -- ./test/irmin-pack/cli/irmin_fsck.exe integrity-check-index ../store/pirbo-tezos-node_20210521/context/
>> Beginning index checking with parameters: { log_size = 500000 }
Reconstructing index     4.8 GiB  09:42  [###############################.]  97%irmin-fsck: internal error, uncaught exception:
(Failure
"Pack entry with idx=49_972_463 containing [5254590022,358,\"N\"] is bound to [5313859794,358,\"N\"] in index")
________________________________________________________
Executed in  522.20 secs
```
- reconstruct index 
```
time PACK=tezos dune exec -- ./test/irmin-pack/cli/irmin_fsck.exe reconstruct-index --index-log-size=10_000_000 ../store/pirbo-tezos-node_20210521/context/
>> Beginning index reconstruction with parameters: { …
```
> Add integrity-check-index command to irmin_fsck

- .ocamlformat
- bench/irmin-pack/trace_stat_summary_pp.ml
- examples/deploy.ml
- examples/process.ml
- src/irmin-pack/irmin_pack_intf.ml
- src/irmin-pack/layered/irmin_pack_layered.mli
- src/irmin/conf.mli
- src/irmin/object_graph.ml
- src/irmin/tree_intf.ml
This is a preview of the not-yet-released `ocamlformat.0.19.0`, please wait until the package is published in opam to merge this PR. The output is still likely to slightly change before the package is released.
> [Preview] Upgrade to ocamlformat.0.19.0

- CHANGES.md
- src/irmin-pack/checks.ml
- src/irmin-pack/checks_intf.ml
- src/irmin-pack/ext.ml
- src/irmin-pack/inode.ml
- src/irmin-pack/inode_intf.ml
- src/irmin-pack/layered/ext_layered.ml
- src/irmin-pack/mem/irmin_pack_mem.ml
- src/irmin-pack/s.ml
- src/irmin/object_graph.ml
- src/irmin/object_graph_intf.ml
- src/irmin/store.ml
- src/irmin/store_intf.ml
- test/irmin-pack/cli/generate.ml
- test/irmin-pack/cli/irmin-fsck-help.txt
- test/irmin-pack/cli/stat.t/run.t
- test/irmin-pack/test_inode.ml
Added a new subcommand in irmin-fsck which traverses the graph under one commit and reports: the longest paths, the widest nodes, and the "biggest" Merklee proof = the chain from root to leaf that stores the most hashes, where for each node we store its siblings. For the first two, we need to visit all nodes, but for the MP we need to visit all inodes as well. I think this is what we want to compare inode configurations, let me know if I got it wrong. 
It also prints all paths in a separate file. It's still draft because I'm not sure how we want to print/report these.
> irmin-fsck: traverse head commit for stats

- irmin.opam
This revision contains the fix to recursive pre-hashing here: https://github.com/mirage/repr/pull/71.
> Use the latest version of Repr

- src/irmin-pack/atomic_write.ml
- src/irmin-pack/atomic_write_intf.ml
- src/irmin-pack/ext.ml
- src/irmin-pack/layered/ext_layered.ml
- test/irmin-pack/common.ml
- test/irmin-pack/test_pack.ml
We currently use `Repr.of_bin_string` in `Irmin_pack.Atomic_write` to construct a "zero" value that is assumed never to be constructed by the user. This doesn't extend to non-hash keys (as will be required by https://github.com/mirage/irmin/pull/1389), so this commit changes the API to be more upfront about what properties are required.
> irmin-pack: avoid assuming the encoding of atomic write keys

- irmin-git.opam
The tests currently segfaults on s390x with:
```
Backtrace stopped: Cannot access memory at address 0x3ffff7fffb0
```
(from ocaml-git's Value.to_raw)
> irmin-git: temporary disable the package on s390x

- CHANGES.md
- src/irmin/tree.ml
... rather than using the default structural definition supplied by Repr, which is sensitive to caching and not stable.
Fix https://github.com/mirage/irmin/issues/1396.
> irmin: compare lazy nodes and contents by hash

- src/irmin-pack/layered/layered_store.ml
- src/irmin-test/common.ml
- src/irmin-test/store.ml
- src/irmin/commit.ml
- src/irmin/import.ml
Fix https://github.com/mirage/irmin/issues/1517.
> Avoid implicit use of polymorphic equality via `List.mem`

- src/irmin-mirage/git/irmin_mirage_git_intf.ml
It seems that #1470 inadvertently changed the signature of a KV functor in irmin-mirage. 
Some other constraints might be missing in there but I'm not sure
CC @dinosaure
> irmin-mirage: Add missing constraint on Irmin_mirage_git.KV_maker

- CHANGES.md
- src/irmin/import.ml
- src/irmin/tree.ml
- src/irmin/tree_intf.ml
This is a small improvement in the memory usage for the migration - in my benchmarks the peak allocations are down by 0.5G, but the maxrss only of approx 0.2G.
> Use seq in Tree.fold

- CHANGES.md
- src/irmin/tree.ml
- src/irmin/tree_intf.ml
In tezos, the [`fold`](https://gitlab.com/tezos/tezos/-/blob/master/src/lib_context/helpers/context.ml#L73) is called with a `contents` function which requires the value of a content to build up a tree of it. But the fold function already manipulates the contents as trees, so there is an unnecessary indirection to go from `Contents.t` to `contents`.
Printing out stats during the migration, shows that we are looking up a lot of contents on disk (and incrementing the `contents_find` [here](https://github.com/mirage/irmin/blob/master/src/irmin/tree.ml#L228)). For example for flattening `contracts/index 1 delegated` we have:
```
"contents_hash": 43709,
"contents_find": 70956,
"contents_add": 43709,
```
This PR adds a `tree` function as parameter to `fold` that allows us to rewrite the fold in …
> Use a `tree` parameter in `fold` 

- CHANGES.md
- src/irmin-git/node.ml
- src/irmin-pack/inode.ml
- src/irmin-test/store.ml
- src/irmin/node.ml
- src/irmin/node_intf.ml
- src/irmin/store.ml
- src/irmin/store_intf.ml
- src/irmin/tree.ml
- src/irmin/tree_intf.ml
- test/irmin/test_tree.ml
This PR introduces GC in inodes and sets everything up to micro-manage the caching in tree.
For example, it allows (I believe) to compute the hash of a tree without keeping anything heaving in memory at any time.
> Rework caching

- test/irmin-pack/test_pack.ml
Introduced by https://github.com/mirage/irmin/pull/1513.
> irmin-pack: fix typo in name of the `irmin-test` suite

- src/irmin/tree.ml
- src/irmin/tree_intf.ml
In order to match the released behaviour
> Change `Tree.list ~cache` to true

- CHANGES.md
- src/irmin/tree.ml
- src/irmin/tree_intf.ml
- test/irmin-pack/dune
- test/irmin-pack/test_pack.ml
- test/irmin-pack/test_tree.ml
- test/irmin/test_tree.ml
The issue with the dangling hash is that the fold in https://github.com/mirage/irmin/pull/1525, visits values by reading their children from disk, but newly added values are not on disk, hence the error. 
We can fix this by visiting the updatemap separately (in commit https://github.com/mirage/irmin/commit/40ccecebeb33df3b7f9bba20fc430d0aaf3f14f0). This works on the backport (see https://github.com/mirage/irmin/pull/1531) but does not work with the current upstream, where `to_value` is going to raise an error if there are elements in the updatemap. Another possibility is to just revert to `to_map`. I don’t see a significant difference between the two in my benchmarks in terms of neither memory and run time for the migration, so the quick fix is maybe the way to go?
> Fix fold in the case the update map is not empty

- src/irmin-test/store_watch.ml
See https://github.com/mirage/irmin/issues/1447.
This is currently failing our CI very frequently. It's hard to reproduce locally and noone has yet had time to debug it. Let's just disable it in the mean-time.
> irmin-test: disable flaky test 'Watch.Basic operations'

- CHANGES.md
- bench/irmin-pack/dune
- bench/irmin-pack/layers.ml
- src/irmin-pack/conf.ml
- test/irmin-tezos/stat.t/run.t
As mentioned [here](https://github.com/mirage/irmin/pull/1555#pullrequestreview-787904335), there were some changes included in 2.8 not yet in `main`. This PR fixes that.
> Forward-port changes introduced in the 2.8 release

- bench/irmin-pack/trace_common.ml
- irmin-pack.opam
- irmin.opam
- src/irmin-chunk/irmin_chunk.ml
- src/irmin-git/commit.ml
- src/irmin-git/contents.ml
- src/irmin-git/node.ml
- src/irmin-pack/atomic_write.ml
- src/irmin-pack/dict.ml
- src/irmin-pack/inode.ml
- src/irmin-pack/pack_index.ml
- src/irmin-pack/pack_store.ml
- src/irmin-pack/pack_value.ml
- src/irmin-pack/pack_value_intf.ml
- src/irmin-pack/traverse_pack_file.ml
- src/irmin/commit.ml
- src/irmin/hash.ml
- src/irmin/node.ml
- test/irmin-pack/common.ml
- test/irmin-pack/test_inode.ml
> Adapt to mirage/repr#81 (improved binary decoder type)

- src/irmin-test/store.ml
Following up on https://github.com/mirage/irmin/pull/1581, here's another pair of tests that are currently flaking and should be debugged separately.
See https://github.com/mirage/irmin/issues/1090 and https://github.com/mirage/irmin/issues/1383.
> irmin-test: disable more flaky tests

- CHANGES.md
- src/irmin-unix/resolver.ml
- src/irmin-unix/resolver.mli
This PR utilizes `Yaml.Util` functions instead of `List.assoc` and renames some functions involved in parsing config files which makes the whole process a little straight forward.
> CLI: Cleanup config parsing using `Yaml.Util` 

- CHANGES.md
- src/irmin-unix/cli.ml
- Adds `branches` command to list available branches
- Adds `log` command which is similar to `git log`
Here's part of the output of `log` command using `irmin log -s git --root .` in the irmin repository:
```
commit 9f7bc69ff2443124916a7b84e70b54bfe165b5ec
Author: Craig Ferguson
Date: Wed Nov 17 04:17:14 2021
Merge pull request #1604 from CraigFe/disable-flaky-tests
irmin-test: disable more flaky tests
commit ae78151ea7819bc108d35a3c72f0bd47fce28f49
Author: Craig Ferguson
Date: Tue Nov 16 05:12:35 2021
Merge pull request #1547 from CraigFe/adapt-to-repr-81
Adapt to mirage/repr#81 (improved binary decoder type)
commit f8142b83fb142c35613369e714f4f29a6cb8b5ce
Author: Craig Ferguson
Date: Wed Nov 17 03:17:01 2021
irmin-test: disable flaky test 'with_tree strategies'
See …
```
> CLI: Additional commands

- CHANGES.md
- src/irmin-unix/cli.ml
- src/irmin-unix/resolver.ml
- src/irmin-unix/resolver.mli
This generalises `Irmin_unix.Resolver.Store.t` to support backend implementations that use generic keys. Resolvers constructed in this way may not be used to build HTTP / GraphQL servers (and attempting to do so will raise
an exception).
This is an interim solution to unblock https://github.com/mirage/irmin/pull/1534 without requiring `irmin-http` and `irmin-graphql` to support structured keys immediately. That can be done in a follow-up PR (and we should make an issue to track that if we merge this).
> irmin-unix: support resolvers for generic-keyed backends

- CHANGES.md
- bench/irmin-pack/trace_stat_summary_pp.ml
Change the printer of `trace_stat` to export the text as a format understood by the `hackmd`.
Closes #1614
> Bench Pretty Printer support for hackmd format

- src/irmin-unix/resolver.ml
- src/irmin-unix/resolver.mli
This is needed after the changes to `Irmin_unix.Resolver` in #1603, which removed `Irmin_unix.Resolver.Store.destruct` because `irmin-server` and `irmin-rs`/`libirimin` need a way to access the store module and remote function from `Irmin_unix.Resolver.Store.t` directly.
> Expose Irmin_unix.Resolver.Store impl and remote fields

- src/irmin/proof.ml
- src/irmin/proof_intf.ml
Now use a functor to simplify the documentation of the involved types (managing 3 or 4 type parameters is a bit annoying 😓 )
> Refactor proofs, take 2

- CHANGES.md
- src/irmin/tree.ml
> [2.9] irmin: use CPS for conversions between trees and proofs

- src/irmin-test/store.ml
- src/irmin-test/store_watch.ml
... by replacing them with the almost-equivalent `Lwt.pause`. Promises constructed in this way have slightly different scheduling behaviour, but this shouldn't impact the correctness of our code.
This may make our tests that use these functions more or less flaky; I'm not sure.
See https://github.com/ocsigen/lwt/issues/855 for more details.
> Avoid use of deprecated `Lwt_main.yield`

- CHANGES.md
- src/irmin-git/node.ml
- src/irmin-pack/inode.ml
- src/irmin-test/node.ml
- src/irmin-test/store.ml
- src/irmin/commit.ml
- src/irmin/node.ml
- src/irmin/node_intf.ml
- test/irmin-pack/test_inode.ml
This ensures that users get fresh empty nodes, so they cache their `key` values obtained during export separately. This is required for an efficient implementation of structured keys in `irmin-pack` (that caches export state within inodes).
Very similar to https://github.com/mirage/irmin/pull/1566. Extracted from https://github.com/mirage/irmin/pull/1534.
> irmin: change `Node.empty` to take a unit argument

- src/irmin-unix/resolver.ml
- test/irmin-unix/test_command_line.t
> irmin-unix: Update `Irmin_unix.Resolver.Store.create` to use `hash` argument

- src/irmin-pack/inode.ml
- src/irmin/node.ml
- src/irmin/node_intf.ml
This is now exactly the same API as 'generic' nodes
On top of #1611
> irmin: have a more complete API for portable nodes

- bench/irmin-pack/trace_collection.ml
- bench/irmin-pack/trace_definitions.ml
- bench/irmin-pack/trace_stat_summary.ml
- bench/irmin-pack/trace_stat_summary_cb.ml
- bench/irmin-pack/trace_stat_summary_pp.ml
- src/irmin-pack/pack_store.ml
- src/irmin-pack/stats.ml
- src/irmin-pack/stats.mli
- test/irmin-bench/replay.ml
Changes `irmin-pack/stats.ml` to keep more granular information about `Store.find` operations (namely, _where_ each successful find came from). Doesn't (yet) expose this in the pack trace.
Drops `t.cache_misses`, since this can now be derived from the location information.
Extracted from https://github.com/mirage/irmin/pull/1534, which also splits the `Pack` location into `Pack_indexed` and `Pack_direct` (corresponding to whether or not the index was consulted for the length information). The advantage is that we can handle breaking the trace format in this PR to reduce the diff of #1534 considerably.
> irmin-pack: collect location information for `find` operations

- src/irmin-pack/pack_value.ml
- src/irmin-pack/pack_value_intf.ml
- src/irmin-pack/traverse_pack_file.ml
These simplify the process of extending the `Pack_value.Kind.t` type with extra cases.
> irmin-pack: provide utility functions over value kinds

- CHANGES.md
- bench/irmin-pack/layers.ml
- bench/irmin-pack/tree.ml
- examples/deploy.ml
- examples/trees.ml
- src/irmin-graphql/server.ml
- src/irmin-mirage/git/irmin_mirage_git.ml
- src/irmin-test/irmin_bench.ml
- src/irmin-test/layered_store.ml
- src/irmin-test/store.ml
- src/irmin-unix/cli.ml
- src/irmin/store.ml
- src/irmin/tree.ml
- src/irmin/tree_intf.ml
- test/irmin-git/test_git.ml
- test/irmin-pack/cli/generate.ml
- test/irmin-pack/layered.ml
- test/irmin-pack/multiple_instances.ml
- test/irmin-pack/test_existing_stores.ml
- test/irmin-pack/test_tree.ml
- test/irmin/test_tree.ml
Backport for #1566 as this is needed for proper separation of env caches in #1625
> [2.10] Tree.empty now takes a unit argument

- CHANGES.md
- bench/irmin-pack/main.ml
- bench/irmin-pack/tree.ml
- src/irmin-pack/conf.ml
- src/irmin-pack/conf.mli
- src/irmin-pack/ext.ml
- src/irmin-pack/inode.ml
- src/irmin-pack/layered/ext_layered.ml
- src/irmin-pack/mem/irmin_pack_mem.ml
- src/irmin-pack/pack_value.ml
- src/irmin-pack/pack_value_intf.ml
- src/irmin-tezos/irmin_tezos.ml
- test/irmin-pack/common.ml
- test/irmin-pack/test_existing_stores.ml
- test/irmin-pack/test_inode.ml
- test/irmin-pack/test_pack.ml
- test/irmin-tezos/generate.ml
Adds a configuration option requiring the user to specify whether or not their contents value uses an LEB128-encoded length header. This option is currently unused, but will be required to enable direct pointers to contents values in a future version of `irmin-pack`.
> irmin-pack: add support for reading contents length headers

- test/irmin-pack/test_inode.ml
The automatic merge of https://github.com/mirage/irmin/pull/1644 and https://github.com/mirage/irmin/pull/1642 introduced a bug to `main` that is resolved by this diff.
> irmin-pack: fix bad merge in inode tests

- CHANGES.md
- src/irmin-pack/inode.ml
- src/irmin-test/store.ml
- src/irmin/irmin.ml
- src/irmin/irmin.mli
- src/irmin/proof.ml
- src/irmin/proof_intf.ml
- src/irmin/store.ml
- src/irmin/store_intf.ml
- src/irmin/tree.ml
- src/irmin/tree_intf.ml
- test/irmin-pack/test_tree.ml
Expose `Tree.produce_proof` and `Tree.verify_proof` which takes a dynamic computation as a callback instead of a static set of paths as `Tree.Proof.of_keys` was exposing.
This allows generating proof for all operations supported in the Tree API (including paginated lists and folds).
On top of #1624
> [2.10] more powerful proof API

- CHANGES.md
- src/irmin-unix/cli.ml
- src/irmin-unix/resolver.ml
- src/irmin-unix/resolver.mli
Currently 'Resolver.Store.add` will add the new store type, but it won't be available since the term has already been computed - if we delay this computation then the newly added store/hash/content types will be valid options (as intended).
> CLI: Delay evaluation of `store` and other user modifiable terms

- CHANGES.md
- src/irmin-git/backend.ml
- src/irmin-git/irmin_git.ml
- src/irmin-http/irmin_http.ml
- src/irmin-pack/ext.ml
- src/irmin-pack/layered/ext_layered.ml
- src/irmin-pack/mem/irmin_pack_mem.ml
- src/irmin/backend.ml
- src/irmin/commit.ml
- src/irmin/commit_intf.ml
- src/irmin/irmin.ml
- src/irmin/node_intf.ml
This is needed by users of generic-keyed backends in order to compute the hash of purely in-memory commits.
I'm not so happy with the extra boilerplate that this requires of the backends. That could be avoided by providing a helper functor such as `Irmin.Of_hash_keyed_backend`, but I'll leave it for a different PR as this is already the case for the `Node_portable` module.
> irmin: introduce an abstraction for portable commits

- CHANGES.md
- src/irmin-pack/checks.ml
- src/irmin-pack/inode.ml
- src/irmin-pack/pack_store.ml
- src/irmin-pack/pack_value.ml
- src/irmin-pack/pack_value_intf.ml
- src/irmin-pack/traverse_pack_file.ml
- src/irmin-test/helpers.ml
- test/irmin-bench/replay.ml
- test/irmin-pack/common.ml
This PR adds three new types of pack entry:
- **`Inode_v1_root`** / **`Inode_v1_nonroot`** (taken from https://github.com/mirage/irmin/pull/1601). These are similar to the existing `Node` and `Inode` except:
- the discriminator between types of node is now `is_root` rather than `is_stable`;
- the pack entry has a varint length header after the kind (and before the data).
- **`Commit_v1`**. These are similar to the existing `Commit`, except:
- references to other values (parent commits and root nodes) are serialised as direct offsets when possible (i.e. when the value being referenced already exists in the store). (_I was hoping that this would always be possible, but the upper layered store relies on serialising an orphan commit_.)
- the pack entry has a varint length header after the …
> irmin-pack: add new pack entries with length headers

- src/irmin-pack/inode.ml
- test/irmin-pack/test_inode.ml
The automatic merge of https://github.com/mirage/irmin/pull/1633 and https://github.com/mirage/irmin/pull/1649 introduced a bug to `main` that is resolved by this diff.
(I think we should consider altering our GitHub workflow to prevent this from happening in future.)
> irmin-pack: fix binary encoding of new inode values

- CHANGES.md
- src/irmin-tezos/schema.ml
- src/irmin/commit.ml
- src/irmin/commit_intf.ml
- test/irmin-pack/test_hashes.ml
When computing the hash of a commit, we want to use the `pre_hash` of node keys and parent keys, instead of their `encode_bin`. This change is necessary for the structured keys PR.
The `encode_bin` was only necessary as a substitute for `pre_hash`, and it is not called anywhere else (I'm not sure why).
On top of https://github.com/mirage/irmin/pull/1633.
> Box the hash of parents and nodes in a commit's prehash

- CHANGES.md
- src/irmin-pack/IO.ml
- src/irmin-pack/IO_intf.ml
- src/irmin-pack/pack_store.ml
- src/irmin-pack/pack_value.ml
- src/irmin-pack/pack_value_intf.ml
- src/irmin-pack/version.ml
- src/irmin-pack/version.mli
Based on https://github.com/mirage/irmin/pull/1654.  Still needs tests.
> irmin-pack: bump version header when appending new pack values

- test/irmin-pack/common.ml
- test/irmin-pack/common.mli
- test/irmin-pack/test_existing_stores.ml
- test/irmin-pack/test_inode.ml
- test/irmin-pack/test_pack.ml
Changes extracted from https://github.com/mirage/irmin/pull/1534 that are not strictly relevant to direct addressing in `irmin-pack`.
> irmin-pack: miscellaneous test refactoring for structured keys

- CHANGES.md
- src/irmin-pack/inode.ml
- src/irmin-test/store.ml
- src/irmin/node.ml
- src/irmin/node_intf.ml
- src/irmin/proof.ml
- src/irmin/proof_intf.ml
- src/irmin/store_intf.ml
- src/irmin/tree.ml
- src/irmin/tree_intf.ml
Do not use ground types with lots of parameters anymore. We loose type
equalities between proofs of different stores, but we gain better error
messages, tooling support (including merlin and odoc).
It's a good tradeoff for now.
> [2.10] Simplfify the proof API

- src/irmin/node.ml
The function should proxy to the underlying store implementation, rather than just returning `None`. This bug was introduced by f20ea38945fcc6503d56c9994084108e1fb4e78c, and is exercised by Tezos' snapshot import process.
> irmin: fix implementation of `Node.Generic_key.Make.index`

- CHANGES.md
- src/irmin-git/irmin_git.ml
- src/irmin-pack/inode.ml
- src/irmin-pack/inode_intf.ml
- src/irmin-test/store.ml
- src/irmin/node.ml
- src/irmin/node_intf.ml
- src/irmin/proof.ml
- src/irmin/proof_intf.ml
- src/irmin/tree.ml
- src/irmin/tree_intf.ml
- test/irmin-pack/test_inode.ml
This is more involved that I initially thought, as we also need to track effects inside inodes (hence the new `map_env` function).
> [2.10] irmin-pack: fix proofs for large inodes

- CHANGES.md
- irmin-unix.opam
- src/irmin-unix/dune
- src/irmin-unix/resolver.ml
- src/irmin-unix/resolver.mli
This allows the tezos store type to be picked from the command-line
> [2.10] Add tezos store type to resolver.ml

- src/irmin-pack/inode.ml
- src/irmin/node.ml
- src/irmin/node_intf.ml
- src/irmin/proof.ml
- src/irmin/proof_intf.ml
- src/irmin/tree.ml
- test/irmin-pack/test_inode.ml
Similar to Plebeia, compress the proof paths for singleton nodes.
> [2.10] irmin-pack: use extenders in proofs

- CHANGES.md
- bench/irmin-pack/bench_common.ml
- bench/irmin-pack/bench_common.mli
- bench/irmin-pack/main.ml
- bench/irmin-pack/tree.ml
- src/irmin-pack/conf.ml
- src/irmin-pack/conf.mli
- src/irmin-pack/inode.ml
- src/irmin-test/store.ml
- src/irmin-tezos/irmin_tezos.ml
- src/irmin-unix/resolver.ml
- test/irmin-pack/cli/generate.ml
- test/irmin-pack/cli/irmin_fsck.ml
- test/irmin-pack/common.ml
- test/irmin-pack/common.mli
- test/irmin-pack/layered.ml
- test/irmin-pack/multiple_instances.ml
- test/irmin-pack/test_existing_stores.ml
- test/irmin-pack/test_inode.ml
- test/irmin-pack/test_pack.ml
- test/irmin-pack/test_tree.ml
By default, use the relevant bits in a cryptographic hash of the keys instead
of relying on a seeded short hash.
Fix #1599
> [2.10] irmin-pack: add an option to configure the index function

- CHANGES.md
- src/irmin/proof.ml
- src/irmin/proof_intf.ml
- src/irmin/tree.ml
After a careful analysis of the current algorithm for the computation of merkle proof, I could come up with some simplifications.
On branch 2.10 the computation of proofs relies both on the `with_handler` function and the pointer sharing between inodes. It turned out that `with_handler` is currently not necessary, the pointer sharing being enough.
The `tree_of_proof` function on 2.10 behaved quadratically given the number of inode roots. I've switched to a `load_proof` scheme to solve this.
I've added 2 more tags in `Env`'s `mode` to better keep track of what is supposed to happen.
I have changed `verify_proof` and `produce_proof` so that `f ` and `Proof.of_tree` act on cache-less tree (only `Env`). This has the advantage that these cache can't hide bugs during UT.
> Simpify merkle proof computation

- src/irmin-pack/checks.ml
- src/irmin-pack/inode.ml
- src/irmin-pack/pack_value.ml
- src/irmin-pack/pack_value_intf.ml
- src/irmin-pack/traverse_pack_file.ml
Renames the original object types as `*_v1`, and the new ones (with added length headers) as `*_v2` to be consistent with the one-indexing used for pack _store_ version headers. Now a V1 pack store is a file containing only V1 objects, and V2 pack stores may also contain V2 objects.
> irmin-pack: use one-indexed versioning for pack value version

- src/irmin-git/irmin_git.ml
- src/irmin-pack/inode.ml
- src/irmin-test/store.ml
- src/irmin/node.ml
- src/irmin/node_intf.ml
- src/irmin/proof.ml
- src/irmin/proof_intf.ml
- src/irmin/store_intf.ml
- src/irmin/tree.ml
- src/irmin/tree_intf.ml
- test/irmin-pack/test_tree.ml
This WIP PR is a rebase on 2.10 of #1673. See the full diff  https://github.com/samoht/irmin/compare/samoht:merkle-traces-5..Ngoguey42:streamed-proof-as-hash-array
It contains most of the diffs from #1673. 
I've removed the `Empty` tag from the streamed proofs as this didn't seem mandatory.
I've removed the `stream` type from `Node.S`
It misses the extenders for the streamed proofs. @icristescu is working on it.
It misses some documentation.
> [2.10] irmin: add Merkle stream proofs

- CHANGES.md
- src/irmin-pack/ext.ml
- src/irmin-pack/inode.ml
- src/irmin-pack/inode_intf.ml
- src/irmin-pack/mem/irmin_pack_mem.ml
- src/irmin-pack/pack_key.ml
- src/irmin-pack/pack_key_intf.ml
- src/irmin-pack/pack_store.ml
- src/irmin-pack/pack_value.ml
- src/irmin-pack/pack_value.mli
- src/irmin-pack/pack_value_intf.ml
- src/irmin-test/common.ml
- src/irmin-test/irmin_test.mli
- src/irmin-test/store.ml
- src/irmin-unix/resolver.ml
- test/irmin-pack/common.ml
- test/irmin-pack/test_hashes.ml
- test/irmin-pack/test_inode.ml
- test/irmin-pack/test_pack.ml
Contains the minimal changes necessary to introduce direct pointers to `irmin-pack`, without changing the indexing strategy (or allowing the user to do the same).
> irmin-pack: add a direct-addressing mode for internal pointers

- bench/irmin-pack/trace_collection.ml
- bench/irmin-pack/trace_definitions.ml
- bench/irmin-pack/trace_stat_summary.ml
- bench/irmin-pack/trace_stat_summary_cb.ml
- bench/irmin-pack/trace_stat_summary_pp.ml
- src/irmin-pack/pack_store.ml
- src/irmin-pack/stats.ml
- src/irmin-pack/stats.mli
- test/irmin-bench/replay.ml
Finds via `Direct` keys are much more efficient than finds via `Indexed` keys, and our metrics should keep track of which are which.
> irmin-pack: split metrics for `find` according to key type

- CHANGES.md
- src/irmin-pack/conf.ml
- src/irmin-pack/conf.mli
- src/irmin-pack/ext.ml
- src/irmin-pack/inode_intf.ml
- src/irmin-pack/irmin_pack_intf.ml
- src/irmin-pack/pack_store.ml
- src/irmin-pack/pack_store_intf.ml
- test/irmin-pack/common.ml
- test/irmin-pack/test_inode.ml
- test/irmin-pack/test_pack.ml
Now that internal references between pack entries can be resolved without use of the index, it is no longer necessary to index every object for correctness of the store. The index is now used to de-duplicate exported (concrete) values, which impacts only the size of the store and not its consistency.
This commit allows the user to define their own indexing strategy, with two pre-provided strategies:
- `always`: equivalent to the old behaviour;
- `minimal`: index only the objects that are necessary for store
correctness (currently just commit objects).
The `irmin-pack` test suite is now run twice, once for each of these pre-provided strategies.
> irmin-pack: add support for user-defined indexing strategies

- CHANGES.md
- src/irmin-test/store.ml
- src/irmin/irmin.ml
- src/irmin/irmin.mli
- src/irmin/proof.ml
- src/irmin/proof_intf.ml
- src/irmin/store_intf.ml
- src/irmin/tree.ml
- src/irmin/tree_intf.ml
Use a result type and define a more precise datatype to encode proof invariants
> [2.10] Proof api tweaks

- CHANGES.md
- irmin-git.opam
- irmin-mirage-git.opam
- irmin-unix.opam
- src/irmin-mirage/git/dune
- src/irmin-mirage/git/irmin_mirage_git.ml
- src/irmin-unix/dune
- src/irmin-unix/xgit.ml
- test/irmin-git/dune
- test/irmin-git/test_git.ml
> Remove Git_paf and lint dependencies according to the last version of Git

- irmin.opam
These versions fail when attempting to build Irmin's documentation:
```
odoc: internal error, uncaught exception:
Not_found
Raised at Stdlib__map.Make.find in file "map.ml", line 137, characters 10-25
Called from Odoc_xref2__Env.ElementsByName.remove in file "src/xref2/env.ml", line 116, characters 12-33
Called from Odoc_xref2__Env.remove in file "src/xref2/env.ml", line 241, characters 11-52
Called from Stdlib__list.fold_left in file "list.ml", line 121, characters 24-34
Called from Odoc_xref2__Compile.include_.get_expansion in file "src/xref2/compile.ml", line 335, characters 20-63
Called from Odoc_xref2__Compile.signature_items.(fun) in file "src/xref2/compile.ml", line 236, characters 21-35
Called from Stdlib__list.fold_left in file "list.ml", line 121, characters 24-34
...
```
See …
> irmin: mark as incompatible with Odoc.2.0.{1,2}

- CHANGES.md
- bench/irmin-pack/main.ml
- bench/irmin-pack/tree.ml
- src/irmin-pack/conf.ml
- src/irmin-pack/conf.mli
- src/irmin-pack/inode.ml
- src/irmin-pack/inode_intf.ml
- src/irmin-test/store.ml
- src/irmin-tezos/irmin_tezos.ml
- test/irmin-pack/test_existing_stores.ml
- test/irmin-pack/test_hashes.ml
- test/irmin-pack/test_inode.ml
- test/irmin-pack/test_pack.ml
- test/irmin-tezos/generate.ml
Forward port of #1677.
Also adds some tests of the new behaviour, and explicitly forbids using `` `Hash_bits `` with `entries >= 2048`.
> irmin-pack: add an option to configure the index function (port from 2.10)

- README.md
- dune
- dune-project
- examples/readme.ml
- irmin.opam
Resolves https://github.com/mirage/irmin/issues/986.
- Requires Dune 2.4.0 for the `(mdx)` stanza. Dune 2.0+ locks are currently broken (soon to be fixed by https://github.com/ocaml/dune/pull/3366). This adds a fake dependency `test/irmin-unix/runtest` → `test/irmin-http/runtest` to ensure that those are serialised.
- Requires unreleased MDX support for labels in HTML comments, so marked as draft until those are released.
> Use MDX to test the README example

- CHANGES.md
- src/irmin-unix/cli.ml
Adds parameters to `irmin watch` that allow the user to specify a command that should be executed or written to for each update.
> CLI: Update watch command

- .github/workflows/coverage.yml
- .gitignore
- README.md
- bench/irmin-pack/dune
- codecov.yml
- irmin.opam
- ppx_irmin.opam
- src/irmin-chunk/dune
- src/irmin-containers/dune
- src/irmin-fs/dune
- src/irmin-git/dune
- src/irmin-graphql/dune
- src/irmin-http/dune
- src/irmin-layers/dune
- src/irmin-mirage/dune
- src/irmin-mirage/git/dune
- src/irmin-mirage/graphql/dune
- src/irmin-pack/dune
- src/irmin-pack/mem/dune
- src/irmin-test/dune
- src/irmin-tezos/dune
- src/irmin-unix/dune
- src/irmin/dune
- src/ppx_irmin/dune
... and a GitHub actions CI job that runs the tests with instrumentation and then submits the report to [Codecov](https://codecov.io/).
The workflow is as described [here](https://github.com/aantron/bisect_ppx#dune). I picked Codecov as a report viewer fairly randomly; we could also go with Coveralls with a small change. Our first coverage report is [here](https://codecov.io/gh/mirage/irmin/tree/1a8a492ff59ac63402bf4d7630a486813dec5934).
Note on authentication: Codecov provides a secret token that can be used to submit coverage reports securely, but this is not necessary when uploading from a small number of whitelisted CI providers including GitHub Actions (see [docs](https://docs.codecov.com/docs/frequently-asked-questions#where-is-the-repository-upload-token-found)). This is fortunate …
> Add `bisect_ppx` instrumentation to all libraries

- src/irmin-test/common.ml
- src/irmin-test/irmin_test.mli
- src/irmin-test/store.ml
- src/irmin-test/store.mli
This ensures that libraries that happen to link against `irmin-test` don't have their random state altered during initialisation.
Fix https://github.com/mirage/irmin/issues/1585.
> irmin-test: guard `Random.self_init` behind run

- .github/workflows/coverage.yml
This is necessary to get coverage results for the merge commits of PRs that were not fully rebased against `main` when merging (so no fast-forward merge was performed), so that Codecov has baseline coverage information to compare against when computing diffs for PRs.
> Run code coverage on pushes to the `main` branch too

- .github/workflows/coverage.yml
It seems like we should avoid running the coverage action in forks since it will fail without the upload token - on Monday I got notified of this failure on a actions that was triggered automatically: https://github.com/zshipko/irmin/runs/4756161105
> Only run code coverage action in mirage/irmin

- .ocamlformat
- bench/irmin-pack/trace_stat_summary_cb.ml
- src/irmin-git/commit.ml
- src/irmin-http/irmin_http.ml
- src/irmin-pack/checks_intf.ml
- src/irmin-pack/inode.ml
- src/irmin-test/common.ml
- src/irmin-test/layered_store.ml
- src/irmin-test/store_graph.ml
- src/irmin-test/store_watch.ml
- src/irmin/object_graph_intf.ml
- src/irmin/tree.ml
This is a preview of the not-yet-released `ocamlformat.0.20.0`, please wait until the package is published in opam to merge this PR. The output is still likely to slightly change before the package is released.
The changes are due to:
- `module-item-spacing` is now set to `compact` for the default profile
- `module-item-spacing` is now correctly applied to mutually recursive type definitions
- formatting of list elements has been improved
> Upgrade to ocamlformat.0.20.0

- CHANGES.md
- src/irmin-unix/cli.ml
Adds some flags to make working with large commit histories easier:
- `--max-count`/`-n`: limits the number of commits to print
- `--skip`: sets the number of commits to skip before printing
- `--reverse`: prints history starting from the earliest commit
> Add max-count, skip and reverse options to `irmin log` 

- bench/irmin-pack/dune
- bench/irmin-pack/trace_stat_summary_pp.ml
- irmin-bench.opam
Usage of `PrintBox_text` now uses UTF-8 box-drawing characters by default, and the previous optional `printbox.unicode` library no longer exists.
This should fix the CI, which is currently failing on `main` due to the release of `printbox.0.6`.
> irmin-bench: use the latest version of Printbox

- src/irmin/tree.ml
- test/irmin-pack/test_tree.ml
Fix https://github.com/mirage/irmin/issues/1730.
> irmin: fix support for random-order unforced tree traversal

- bench/irmin-pack/trace_collection.ml
- src/irmin-test/store.ml
- src/irmin/tree.ml
- src/irmin/tree_intf.ml
Forward port of https://github.com/mirage/irmin/pull/1676.
> irmin: better signature for Tree.length (port from 2.10)

- src/irmin-test/node.ml
- src/irmin/node.ml
- test/irmin/test.ml
These functions previously asserted that the returned child pointers were keys, then weakened those keys to hashes. This is not necessary, as we only need to return child hashes.
> irmin: fix default `Node.Portable.{find,to_list}` implementations

- src/irmin/export_for_backends.ml
- src/irmin/proof.ml
- src/irmin/reversed_list.ml
- src/irmin/reversed_list.mli
- test/irmin-pack/test_tree.ml
The segment list contained in a stream proof extender node is computed in reverse order, and previously was not being properly reversed at the end of this process.
This PR:
- modifies the existing stream proof extender node test to expose the bug;
- fixes the bug;
- introduces a tiny `Reversed_list.t` type to make it impossible to forget to reverse the list before use in future.
> [2.10] irmin: fix order of stream proof extender segments

- CHANGES.md
- src/irmin-git/irmin_git.ml
- src/irmin-pack/inode.ml
- src/irmin-pack/inode_intf.ml
- src/irmin-pack/layered/inode_layers.ml
- src/irmin/node.ml
- src/irmin/node_intf.ml
- src/irmin/proof.ml
- src/irmin/tree.ml
- test/irmin-pack/test_inode.ml
See the commits and the comments in the code for more details on that bug.
> [2.10] Fix large stable inodes in streamed proofs

- CHANGES.md
- src/irmin-pack/inode.ml
- src/irmin-pack/inode_intf.ml
- src/irmin/node.ml
- src/irmin/node_intf.ml
based on #1745
Since `portable` nodes are used during the production of streamed proofs, `with_handler` is needed in `portable` nodes.
After #1741, `head` is also used during streamed proof production, which make use of `portable` nodes
> irmin: Add `with_handler` and `head` to `Node_portable`

- CHANGES.md
- src/irmin-test/store.ml
- src/irmin/commit.ml
- src/irmin/commit_intf.ml
- src/irmin/contents.ml
- src/irmin/contents_intf.ml
- src/irmin/node.ml
- src/irmin/node_intf.ml
- test/irmin-chunk/test.ml
- test/irmin-pack/common.ml
- test/irmin-pack/common.mli
- test/irmin-pack/test_existing_stores.ml
- test/irmin-pack/test_inode.ml
- test/irmin-pack/test_pack.ml
This changes the hash for all stores that use the default contents. 
Still wip because I need to regenerate the existing stores to use the new hash.   
closes #1304
> Prefix the prehash for default contents, nodes and commits

- CHANGES.md
- examples/push.ml
- examples/sync.ml
- irmin-git.opam
- irmin-unix.opam
- src/irmin-git/dune
- src/irmin-graphql/server.ml
- src/irmin-graphql/server.mli
- src/irmin-mirage/graphql/irmin_mirage_graphql.ml
- src/irmin-unix/cli.ml
- src/irmin-unix/dune
- src/irmin-unix/resolver.ml
- src/irmin-unix/resolver.mli
- src/irmin-unix/xgit.ml
- src/irmin-unix/xgit_intf.ml
Fixes #1777 by using `Git_unix.ctx (Happy_eyeballs_lwt.create ())` when no `Mimic.ctx` is provided by the user.
There are some errors logged that I'm not sure what do with, but it works now so I think that should be addressed in another PR:
```
irmin: [ERROR] connection to 127.0.0.53:853 failed: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
irmin: [WARNING] Reference refs/heads/master not found.
irmin: [ERROR] Object 1d83f084815d11140f9b77fcb4732851bb6dec18 not found.
```
/cc @dinosaure
> irmin-unix: Update default Mimic.ctx

- CHANGES.md
- README_LIBIRMIN.md
- libirmin.opam
- src/libirmin/commit.ml
- src/libirmin/config.ml
- src/libirmin/dune
- src/libirmin/gen/dune
- src/libirmin/gen/generate.ml
- src/libirmin/info.ml
- src/libirmin/lib/dune
- src/libirmin/lib/libirmin.ml
- src/libirmin/libirmin_bindings.ml
- src/libirmin/path.ml
- src/libirmin/repo.ml
- src/libirmin/store.ml
- src/libirmin/tree.ml
- src/libirmin/type.ml
- src/libirmin/types.ml
- src/libirmin/types.mli
- src/libirmin/types_intf.ml
- src/libirmin/util.ml
- src/libirmin/value.ml
- test/libirmin/dune
- test/libirmin/greatest.h
- test/libirmin/test.c
Adds a new libirmin package that provides a C interface to the irmin API (from https://github.com/zshipko/libirmin)
Here is an example using the Python interface: https://github.com/zshipko/libirmin/blob/main/examples/json-merge.py
The Python and Rust bindings are not included - I will move them to their own repositories after this is merged.
I plan on adding some proper documentation to the tutorial since there isn't really a good place to document the C interface in this repo.
- Implementation is in `src/libirmin/*.ml` - these files use OCaml code to define the C API
- C code and header generator is in `src/libirmin/gen`
- Installable `libirmin` C library is in `src/libirmin/lib`
- Tests are in `test/libirmin/test.c`
- After running `dune build`, `irmin.h` and `libirmin.so` can be found …
> Add libirmin

- CHANGES.md
- examples/dune
- src/irmin-pack/dune
We currently link a large part of the ppx stack inside executables that depend on irmin-pack
> Remove runtime dep on the ppx stack

- CHANGES.md
- bench/irmin-pack/dune
- bench/irmin-pack/trace_replay.ml
- bench/irmin-pack/trace_replay_intf.ml
- bench/irmin-pack/tree.ml
- test/irmin-bench/replay.ml
This minimal program and its dune file can launch a trace replay
fixes #1779
```ml
open Lwt.Syntax
module Maker = Irmin_pack.Maker (Irmin_tezos.Conf)
module Store = struct
include Maker.Make (Irmin_tezos.Schema)
type store_config = unit
let create_repo ~root () =
let conf = Irmin_pack.config ~readonly:false ~fresh:true root in
let* repo = Repo.v conf in
let on_commit _ _ = Lwt.return_unit in
let on_end () = Lwt.return_unit in
Lwt.return (repo, on_commit, on_end)
end
module Replay = Irmin_traces.Trace_replay.Make (Store)
let main () =
let conf =
Irmin_traces.Trace_replay.
{
number_of_commits_to_replay = 42;
path_conversion = `None;
inode_config = (32, 256);
store_type = `Pack;
replay_trace_path = "/Users/nico/tz/data5.repr";
artefacts_path = "/tmp/irmin_trace_replay_arefacts";
keep_store = …
```
> irmin-bench: Improve public API for replay

- CHANGES.md
- bench/irmin-pack/main.ml
- src/irmin-pack/conf.ml
- src/irmin-pack/conf.mli
- src/irmin-pack/inode.ml
- src/irmin-tezos/irmin_tezos.ml
- test/irmin-pack/test_existing_stores.ml
- test/irmin-pack/test_hashes.ml
- test/irmin-pack/test_inode.ml
- test/irmin-pack/test_pack.ml
- test/irmin-pack/test_pack_version_bump.ml
- test/irmin-pack/test_tree.ml
Add this conf value to irmin-pack stores:
```ocaml
val forbid_empty_dir_persistence : bool
(** If [true], irmin-pack raises [Failure] if it is asked to save the empty
inode. This default is [false]. It should be set to [true] if the [Schema]
of the store allows a hash collision between the empty inode and this
string of length 1: ["\000"].
See https://github.com/mirage/irmin/issues/1304 *)
```
> irmin-pack: Add `forbid_empty_dir_persistence` conf

- CHANGES.md
- src/irmin-pack/dune
- src/irmin-pack/inode.ml
- src/irmin-pack/inode_intf.ml
- src/irmin-pack/mem/irmin_pack_mem.ml
- src/irmin-pack/pack_store_intf.ml
- src/irmin-pack/s.ml
- src/irmin-pack/unix/ext.ml
- src/irmin-pack/unix/inode.ml
- src/irmin-pack/unix/inode.mli
- src/irmin-pack/unix/pack_index_intf.ml
- src/irmin-pack/unix/pack_store.ml
- src/irmin-pack/unix/snapshot.ml
- src/irmin-pack/unix/snapshot.mli
- src/irmin-pack/unix/snapshot_intf.ml
- test/irmin-pack/dune
- test/irmin-pack/test_pack.ml
- test/irmin-pack/test_snapshot.ml
I added a test that shows how this is used in tezos, and also https://github.com/tarides/tezos/pull/19
> Expose a type for snapshots in inodes

- src/irmin-graphql/server.ml
- test/irmin-graphql/common.ml
- test/irmin-graphql/common.mli
- test/irmin-graphql/test.ml
- Adds a `query` type to the graphql tests:
- Makes writing queries in tests easier (see https://github.com/mirage/irmin/pull/1750/files?diff=split&w=0#diff-3131055e1ed5ebb5e09f20fe0b53836c27ac4205cde1805309c678198c2c499dR98)
- Allows for response to be parsed (almost) automatically
> Overhaul GraphQL test suite

- CHANGES.md
- bench/irmin-pack/trace_stats.ml
- bench/irmin-pack/tree.ml
- irmin-pack.opam
- irmin-test.opam
- irmin-tezos.opam
- irmin-unix.opam
- src/irmin-pack/unix/checks.ml
- src/irmin-pack/unix/checks_intf.ml
- src/irmin-test/irmin_bench.ml
- src/irmin-unix/cli.ml
- src/irmin-unix/cli.mli
- test/irmin-tezos/dune
This is a temporary fix, to remove conflicts with other packages
who started to move to cmdliner 1.1.0.
> irmin: support all versions of cmdliner

- .ocamlformat
- bench/irmin-pack/trace_stat_summary_pp.ml
- src/irmin/indexable_intf.ml
- test/irmin-graphql/common.mli
- test/irmin/test_tree.ml
This is a preview of the formatting of your project codebase with the upcoming `ocamlformat.0.21.0`. Note that this package is not yet released in opam (so the linting/formatting task of your CI won't pass), the formatting might also change slightly in the released version as we try to integrate feedback from our users.
The changes on this project are due to:
- the list of arguments of function applications break on "complex" argument, an argument being composed of a variant is not considered being "complex" anymore.
As always, we are happy to hear your feedback!  Thank you for using ocamlformat!
> Upgrade to ocamlformat.0.21.0

- test/irmin-tezos/irmin_fsck.ml
Set by default the cli of `irmin-pack` for tezos stores. This is more convenient for debugging than using the `./tezos-node storage` command.
> Enable irmin-fsck for tezos stores

- src/irmin/irmin.mli
Found a 77b6d33f19c172494be0762d6091686a4c9cd697 dangling pointer 😄
> docs: remove basics reference

- CHANGES.md
- examples/plugin/README.md
- examples/plugin/dune
- examples/plugin/plugin.ml
- examples/plugin/plugin.t
- src/irmin-unix/dune
- src/irmin-unix/resolver.ml
- src/irmin-unix/resolver.mli
Here’s one approach that allows user-defined types.
- New `--plugin` flag allows users to load a cmxs file to register additional contents, hash and store types
- Example plugin in `examples/plugin/plugin.ml`
> irmin-unix: Add ability to load contents/hash/store types from Dynlink plugin

- src/irmin/store.ml
Small cleanup. `Commits` is the module in use, so `H` gets removed.
> irmin: remove redundant/unused module

- CHANGES.md
- src/irmin-pack/unix/snapshot.ml
Snapshot export assumed that all visited keys are direct. This is assured for all children of a node, but not for the root node, just under a commit. If the root node is indexed, then the export crashes with an assert false (this is probably the cause for https://gitlab.com/tezos/tezos/-/issues/2999). 
The fix is to convert the root key to a direct one if its not the case.
> Allow snapshot export to work on indexed root nodes

- .gitignore
While working on #1839 I noticed a `_metrics` directory was created after playing with stores in `utop`. This PR adds it to git's ignore list.
> Add _metrics to gitignore

- CHANGES.md
- src/irmin-test/store.ml
- src/irmin/tree.ml
- test/irmin/test_tree.ml
On top of #1794
1. Refactors `on_node`
2. Addresses part of https://github.com/mirage/irmin/pull/1794#discussion_r830016058 by making sure that all the tree nodes exported go through `Node.export`.
3. Identifies 3 new edge cases which now result in exceptions. This led to modifications in `test/irmin/test_tree.ml | test_fold_force`.
> Refactor `Tree.export`'s `on_node`

- src/irmin-test/store.ml
- src/irmin/tree.ml
- src/irmin/tree_intf.ml
These functions check whether the node/contents are available in
memory or not (ie. if calling a function on those could incur IO
costs).
> Add `Tree.is_val` and `Tree.Contents.is_val` functions

- test/irmin-pack/common.ml
otherwise the error https://github.com/mirage/irmin/blob/gc/src/irmin-pack/unix/io.ml#L222 is returned 
based on https://github.com/mirage/irmin/pull/1866
> Tests expect parent dir to exist

- src/irmin-pack/unix/file_manager.ml
- src/irmin-pack/unix/traverse_pack_file.ml
- test/irmin-pack/test_existing_stores.ml
Fixing `existing stores 0` and `existing stores 2`.
While this fixes the test, I think we should move to using the new IO in traverse_pack_file instead of the legacy_io, as the legacy_io cannot read files in V3.
> Use decode_int63 for reading old offsets

- src/irmin-pack/unix/checks.ml
- src/irmin-pack/unix/ext.ml
This is just to advance to a working CI, but more work is needed to allow integrity checks to work on all versions of a store.
> Fix test for integrity check

- src/irmin-unix/resolver.ml
The current command line documentation for the `--options` flag is broken. This PR removes specific options from `--help` and encourages users to check `irmin options` instead.
> Fix command-line documentation for --options flag

- bench/irmin-pack/trace_replay.ml
- bench/irmin-pack/trace_replay_intf.ml
- bench/irmin-pack/tree.ml
- src/irmin-pack/unix/pack_store.ml
- test/irmin-bench/replay.ml
On top of #1922
Fixes #1844
Fixes #1920
This will have to be released as a 3.3.1 because the former code could create patterns in the store that will cause crash after GC.
@icristescu Is working on a regression test. 
A replay of 10k commits from genesis shows that the number of cache_miss stays roughly equivalent.
```
|                          |  before  |     after
| --                       | --       | --
| -- main metrics --       |          | 
| CPU time elapsed         |    1m24s |    1m24s 100%
| Wall time elapsed        |    1m34s |    1m27s  92%
| TZ-transactions per sec  |  106.083 |  106.486 100%
| TZ-operations per sec    | 1196.450 | 1200.996 100%
| Context.set per sec      | 8548.792 | 8581.276 100%
| tail latency (1)         |  3.216 s |  2.181 s  68%
| …
```
> Pack store lru on offsets

- CHANGES.md
- src/irmin/tree.ml
- src/irmin/tree_intf.ml
Closes #1257 
The implementation of `Tree.seq` already exists. This PR adds it to `Tree`'s public API.
> irmin: expose `Tree.seq`

- test/irmin-pack/test_tree.ml
The random function changed in OCaml 5 so we can't rely on
seeded random to return the same results across OCaml versions.
> irmin-pack: remove hard-coded random tests

- src/irmin-pack/unix/ext.ml
- src/irmin-pack/unix/file_manager.ml
- src/irmin-pack/unix/file_manager_intf.ml
- src/irmin-pack/unix/io.ml
- src/irmin-pack/unix/io_intf.ml
- test/irmin-pack/test_gc.ml
On top of #1950 
That's the first step of using a different mechanism to synchronise the GC process with a different mechanism (for instance, but using `Lwt_preemptive.detach` or `Lwt_domain.detach` in OCaml 5).
> Io: abstract away fork/waitpid

- bench/irmin-pack/trace_replay.ml
It's useful to keep track of how long the GC finalisers are taking.
> irmin-pack: add a timer for the trace benchmarks

- bench/irmin-pack/tree.ml
This PR makes it so `./bench/irmin-pack/tree.exe` runs successfully and is able to produce a summary.
Fixes https://github.com/mirage/irmin/issues/1965
> irmin-pack: Fix failure when computing summary in tree benchmark

- src/irmin-pack/indexing_strategy.ml
- src/irmin-pack/inode.ml
- src/irmin-pack/pack_value.ml
- src/irmin-pack/pack_value_intf.ml
- src/irmin-pack/unix/checks.ml
- src/irmin-pack/unix/gc.ml
- src/irmin-pack/unix/pack_store.ml
- src/irmin-pack/unix/snapshot.ml
- src/irmin-pack/unix/traverse_pack_file.ml
> irmin-pack: removed unused Gced kind for pack entries

- CHANGES.md
- examples/custom_graphql.ml
- irmin-graphql.opam
- src/irmin-graphql/server.ml
This PR upgrades `irmin-graphql` to use the (at time of writing) unreleased graphql schema fixpoint for constructing mutually recursive schemas. It cannot be merged until there is a release, so I've left this PR as a draft for now.
The context for this PR is that in order for `irmin-server` to use websockets, it will need the changes made in https://github.com/andreas/ocaml-graphql-server/pull/206 which means bumping to the latest version of `graphql`.
cc: @dinakajoy, @zshipko
> Use graphql schema fixpoint

- bench/irmin-pack/tree.ml
- src/irmin-pack/mem/irmin_pack_mem.ml
- src/irmin-pack/s.ml
- src/irmin-pack/unix/ext.ml
- test/irmin-bench/replay.ml
- test/irmin-pack/test_gc.ml
- test/irmin-pack/test_snapshot.ml
- test/irmin-pack/test_upgrade.ml
This PR does several things
- Moves stats tracking to the internal gc process instead of just at the high-level api boundary
- Introduces a promise for a running gc that can be used for callbacks and waiting
- Fixes an issue previously discovered with `wait` (see #1984) ~but by binding to the gc promise instead of using a polling loop~ by making it the only high-level api place that uses `finalise_exn ~wait:true`
- Fixes issue with `run` (see #1985) but by attaching a callback to the gc promise instead of using a combination of `Lwt.async` and `Lwt.pause`. (I have a local version of the tree benchmark working correctly with the changes introduced here that I will PR later)
- To ensure finalisation happens (since we have removed an explicit waiting finalisation through a mechanism like …
> irmin-pack: refactor high-level gc implementation

- CHANGES.md
- irmin.opam
- src/irmin/lru.ml
- src/irmin/lru.mli
- test/irmin/dune
- test/irmin/test.ml
- test/irmin/test_lru.ml
Because of this bug, once an LRU cache is full and cleared it cannot be filled again with any new data... so it becomes rather useless. Found while trying to debug #1993
> Fix LRU.clear

- src/irmin-pack/indexing_strategy.ml
- src/irmin-pack/indexing_strategy.mli
- src/irmin-pack/unix/pack_store.ml
In minimal indexing mode we don't need to check the index file too often
This removes a few calls to index in the benchmarks:
before:
```
+009us [DEBUG] irmin-pack.unix [pack] batch start
+012us [DEBUG] irmin-pack.unix index CoVkT31UeHdS8o4MMQtzR5jmdxZ5PHo9C1P7LLvn9sSvYub5tB3q
+040us [DEBUG] index [root] find CoVkT31UeHdS8o4MMQtzR5jmdxZ5PHo9C1P7LLvn9sSvYub5tB3q
+023us [DEBUG] irmin-pack.unix [pack] append {"Direct":["CoVkT31UeHdS8o4MMQtzR5jmdxZ5PHo9C1P7LLvn9sSvYub5tB3q",0,41]}
+028us [DEBUG] irmin.pack save depth:0
+010us [DEBUG] irmin-pack.unix index CoUr3AHPmaXCuYL2ps3bcKXwex2QmngoT9Z8LhhMWdLw8RTWZbGc
+010us [DEBUG] index [root] find CoUr3AHPmaXCuYL2ps3bcKXwex2QmngoT9Z8LhhMWdLw8RTWZbGc
+011us [DEBUG] irmin-pack.unix [dict] index "version"
+010us [DEBUG] irmin-pack.unix [pack] append …
```
> irmin-pack: remove unecessary calls to Index.find

- src/irmin-pack/unix/ext.ml
The callback and elapsed time calculation need to occur after the unlink step. Thanks @Ngoguey42 for spotting.
> irmin-pack: fix placement of gc callback

- src/irmin-pack/inode.ml
- test/irmin-pack/test_gc.ml
- test/irmin-tezos/stat.t/run.t
The irmin-tezos cli (and `./tezos-node storage`) are broken, they cannot read stores containing v2 inodes. 
We used to have tests for the cli but we removed them at some point and forgot to put them back. I add them back, but their output is truncated, not sure why. 
This bug occurs on the gc branch (and its fixed there by this PR as well), but since its unrelated to gc and the bug is already in the released versions, I don't think it should block the progress on the gc.
> Fix irmin-tezos cli

- src/irmin-pack/s.ml
- src/irmin-pack/unix/ext.ml
This PR changes the gc api so that only the high level api auto-finalizes. Closes #2011 
1. Make clearer distinction between high and low level apis; low is for more control and hence manual finalization makes sense
2. Fix tests that fail intermittently because they have been written with the low level api and expect objects to gc at certain times
> irmin-pack: only auto finalise high level gc api

- src/irmin-pack/inode.ml
A small clean up spotted while looking through inode code.
> irmin-pack: use deriving for types

- examples/gc.ml
- src/irmin-pack/s.ml
- src/irmin-pack/unix/ext.ml
This PR fixes unneeded type wrapper for stats in the `run` callback. Thanks @Ngoguey42 for spotting!
> irmin-pack: stats are not option in run callback

- src/irmin-pack/layout.ml
- src/irmin-pack/unix/dispatcher.ml
- src/irmin-pack/unix/dispatcher_intf.ml
- src/irmin-pack/unix/file_manager.ml
- src/irmin-pack/unix/file_manager_intf.ml
- src/irmin-pack/unix/gc.ml
- src/irmin-pack/unix/import.ml
- src/irmin-pack/unix/irmin_pack_unix.ml
- src/irmin-pack/unix/mapping_file.ml
- src/irmin-pack/unix/mapping_file.mli
- src/irmin-pack/unix/utils.ml
- test/irmin-pack/dune
- test/irmin-pack/test_mapping.ml
- test/irmin-pack/test_nearest_leq.ml
- test/irmin-pack/test_nearest_leq.mli
- test/irmin-pack/test_pack.ml
This commit changes the mapping file to use mmap on load. The code to
save the mapping has also changed, to take account of mmap format. In
hangzhou benchmarks, this substantially improves the time taken for the
main process to switch to the new prefix/suffix created by the GC
process. For example, the maximum switch time during the benchmark was
0.5s, for a 166MB mapping file (with gap_tolerance=0), with the load of
the mapping file itself being effectively instantaneous.
mmap files are not portable across architectures with different
endianness. Almost surely users are on little-endian machines. However,
to protect against a user copying a little-endian context to a
big-endian machine, the mapping file name has been changed to include
the endianness of the host machine.
We use binary …
> irmin-pack: use mmap for the mapping file

- bench/irmin-pack/trace_replay.ml
- bench/irmin-pack/trace_replay_intf.ml
- bench/irmin-pack/tree.ml
- examples/gc.ml
- src/irmin-pack/mem/irmin_pack_mem.ml
- src/irmin-pack/s.ml
- src/irmin-pack/unix/ext.ml
- test/irmin-bench/replay.ml
This PR adds 4 new fields in gc stats, it adds a repr deriver for it and it changes all timers to `s` from `ms` and `us`.
> irmin-pack: Add more stats in gc finalise

- test/irmin-tezos/stat.t/run.t
This is to avoid issues such as https://ci.ocamllabs.io/github/mirage/irmin/commit/f37ff1987d5a5e8a42fc4cbb45231cea62e84442/variant/debian-11-4.14+flambda_opam-2.1
> irmin-tezos: make the cram tests more robust

- src/irmin-pack/unix/append_only_file.ml
- src/irmin-pack/unix/append_only_file_intf.ml
- src/irmin-pack/unix/ext.ml
- src/irmin-pack/unix/file_manager.ml
- src/irmin-pack/unix/gc.ml
- src/irmin-pack/unix/mapping_file.ml
This PR changes the append file autoflush callback to pass `t` instead of `unit` to facilitate calls to `flush` and cleans up some code.
> irmin-pack: change append only auto flush callback to pass `t`

- bench/irmin-pack/trace_replay.ml
- bench/irmin-pack/trace_replay_intf.ml
- bench/irmin-pack/tree.ml
- examples/gc.ml
- src/irmin-pack/s.ml
- src/irmin-pack/unix/ext.ml
- test/irmin-bench/replay.ml
This PR updates the gc finished callback to allows callers to more easily use Lwt.
> irmin-pack: use Lwt in gc finished callback

- src/irmin-pack/unix/gc.ml
See https://github.com/mirage/irmin/issues/1975#issuecomment-1184311211
Also, although `gap_tolerance` seems to have some effect on this code I didn't update it in this PR.  We should remember to configure that before the release.
> Run transfer_exn in loop in GC child process

- libirmin.opam
I finally got around to running the libirmin tests on an arm64 macOS machine and it doesn't have the same issue as arm64 linux, so this PR enables libirmin for macOS.
> Enable libirmin for macos

- src/irmin-pack/inode.ml
Avoid allocating a Seq.t when this is not needed. This is an
allocation hotspot so let's manually specialise this function a bit.
> irmin-pack: special-case Inode.list

- src/irmin-pack/inode.ml
They will most probably be discarded right away as the hash are forced
during Tree.export and cache are usually cleared just after this.
> irmin-pack: do not cache when hashing inodes

- src/irmin/hash.ml
Do not allocate intermediary strings to encode and decode V1 hashes.
> irmin: optimise V1.Hash.encode/decode

- examples/dune
- irmin-http.opam
- irmin-pack.opam
Fixing https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/86edb716fb2d6c72d682d932dc577323c383fa0f
- Fix `Unbound value Lwt_main.abandon_yielded_and_paused` by changing `irmin-pack`'s Lwt version dep to `>= 5.4.0` ([5.4.0 release notes](https://github.com/ocsigen/lwt/releases/tag/5.4.0))
- Fix `Error: Library "irmin-pack.unix" not found.` for `irmin-git.3.4.0` by changing the `runtest` stanza in example's dune file to `irmin-cli`, which depends on `irmin-pack`.
- Fix `Error: Library "irmin-fs.unix" not found.` for `irmin-http.3.4.0` by adding `irmin-fs` as a test dep
> Fix opam CI issues for 3.4 release

- RELEASE.md
I ran into this with the 3.4 release. It's obvious in hindsight but easy to miss if you're just following the steps. :see_no_evil:
> docs: add missing step for release

- src/irmin-pack/unix/file_manager.ml
- src/irmin-pack/unix/gc.ml
- src/irmin-pack/unix/import.ml
- src/irmin-pack/unix/mapping_file.ml
This PR adds fsync calls to the end of the GC process for the suffix and the results file to ensure flushes are persisted to disk.
Should this code take into consideration the `use_fsync` configuration flag (it does not currently)? I am taking a perspective that the GC process is an internal/separate procedure that does not necessarily have to follow that config value and so it can choose to have safer guarantees, but I do not feel too strongly about this stance.
Related to #1971
> irmin-pack: add fsync to gc process

- CHANGES.md
- examples/custom_storage.ml
- examples/dune
- src/irmin/irmin.ml
- src/irmin/irmin.mli
- src/irmin/storage.ml
- src/irmin/storage.mli
- src/irmin/storage_intf.ml
While working through the tutorial for creating custom storage, I saw an opportunity to provide a more direct way for users to create Irmin stores from a given storage layer. This PR adds a ~`Simple_storage`~ `Storage` module and an example demonstrating its usage. You still need to have some Irmin logic in your storage, but I think it is minimal and much improved.
> irmin: add `Storage` module for creating custom storage layer backends

- src/irmin-pack/unix/file_manager.ml
- src/irmin-pack/unix/file_manager_intf.ml
IIRC, we used to reload the mapping file in the dispatcher, and for that we needed a `register_mapping_consumers`. Now the dispatcher [gets the updated mapping from the file manager at every read](https://github.com/mirage/irmin/blob/main/src/irmin-pack/unix/dispatcher.ml#L135), so there is no need for `mapping_consumers`.
Part of #2039.
> small cleanups

- src/irmin-pack/unix/ext.ml
- src/irmin-pack/unix/gc.ml
- src/irmin-pack/unix/gc.mli
- src/irmin-pack/unix/gc_intf.ml
- test/irmin-pack/test_gc.ml
This PR is a part of #2039. It moves the core GC logic out of `ext.ml` and into its own set of files, `gc.ml` and `gc_worker.ml`. It also does a few cleanups in this area of the code. I recommend reviewing commit-by-commit to see the changes more easily.
> irmin-pack: extract GC logic from ext

- src/irmin-pack/unix/errors.ml
- src/irmin-pack/unix/gc.ml
- src/irmin-pack/unix/mapping_file.ml
- src/irmin-pack/unix/mapping_file_intf.ml
From #2039: the gc worker routine raises errors instead of propagating a result. The errors are catched at the end and converted it in a result for `write_gc_output`.
> Raise errors in gc worker

- CHANGES.md
- examples/config.ml
- examples/dune
- irmin.opam
- src/irmin/unix/dune
- src/irmin/unix/irmin_unix.ml
- src/irmin/unix/irmin_unix.mli
- Removes `set_listen_dir_hook` from `Irmin_unix`
- This will be moved to `irmin-watcher`
- Removes `irmin-watcher` dependency from `irmin.unix`
> irmin.unix: Remove irmin-watcher dependency

- src/irmin-pack/unix/mapping_file.ml
I spotted this while looking at something else. It is safe currently due to the implementation of `Append_only_file` (outside of tests passing -- it uses `Buffer.add_string` -> `Bytes.(unsafe_)blit_string` which copies the string), but it is safer to use a unique ownership model in case either our implementation changes or OCaml's does.
> irmin-pack: ensure safe `Bytes.unsafe_to_string`

- src/irmin-pack/unix/dispatcher.ml
- src/irmin-pack/unix/dispatcher_intf.ml
- src/irmin-pack/unix/gc.ml
- src/irmin-pack/unix/pack_store.ml
- src/irmin-pack/unix/snapshot.ml
This is the first step necessary for my fix of #2067
It splits the dispatcher's reading process into 2 distinct phases: first make sure that `offset, length` make sense and then read.
In pack_store, this will simplify checking that keys are valid by relying on an `accessor_of_key` function (not yet implemented).
> Accessor in dispatcher

- test/irmin-pack/test_gc.ml
Regression test for https://github.com/mirage/irmin/issues/2067. The test fails at line 514 - the key for `c1_again` returned by the index is the one of `c1`, which is not longer in the pack file.
> Test for adding commits with the same hash as gced one

- src/irmin-pack/unix/ext.ml
- src/irmin-pack/unix/file_manager.ml
- src/irmin-pack/unix/file_manager_intf.ml
This PR is for https://github.com/mirage/irmin/issues/1971:
> call fsync after snapshot import;
I'm not sure if exposing an `fsync` function on `File_manager` is the best approach for ensuring an fsync at the end of snapshot import, but it is the most direct approach I could see. Feedback welcome, as always!
> irmin-pack: fsync after snapshot import

- CHANGES.md
- bench/irmin-pack/tree.ml
- src/irmin-pack/irmin_pack.ml
- src/irmin-pack/irmin_pack_intf.ml
- src/irmin-pack/mem/irmin_pack_mem.ml
- src/irmin-pack/unix/checks_intf.ml
- src/irmin-pack/unix/inode_intf.ml
- src/irmin-pack/unix/irmin_pack_unix.ml
- src/irmin-pack/unix/pack_store_intf.ml
- src/irmin-pack/unix/s.ml
- src/irmin-tezos/irmin_tezos.mli
- test/irmin-bench/replay.ml
The signatures in irmin-pack/s.ml were common to both the in memory and on disk stores, but are actually sigs only for the on disk store (their implementation in irmin_pack_mem were empty). This PR moves most of the s.ml to the unix sub package. 
The downside is the duplication of the Maker functor, since it has different `S` types for the in-memory and on disk stores.   
Part of #2039.
> irmin-pack: move sigs to unix

- src/irmin-pack/layout.ml
- test/irmin-pack/common.mli
- test/irmin-pack/test_pack.ml
New function that will be useful to unlink unexpected files in a pack store
> irmin-pack: Add Layout.classify_filename

- src/irmin-pack/unix/dispatcher.ml
- src/irmin-pack/unix/dispatcher_intf.ml
- src/irmin-pack/unix/ext.ml
- src/irmin-pack/unix/gc.ml
- src/irmin-pack/unix/snapshot.ml
- test/irmin-pack/common.ml
- test/irmin-pack/test_inode.ml
This PR adds:
- 2 accessors that uses physical offsets instead of the virtual offsets
- A generator for sequences of accessors that iterates trough all physical offsets of a pack file.
It also removes:
- The `root` filed of `Dispatcher.t`, as it is never used.
> irmin-pack: Add sequential accessors & clean dispatcher

- src/irmin-pack/unix/file_manager.ml
- src/irmin-pack/unix/file_manager_intf.ml
- src/irmin-pack/unix/gc.ml
This PR proposes moving the GC output functions from `File_manger` to `Gc`. They are only used internally to the GC process and so I think feel more appropriately placed inside the `Gc` module.
> irmin-pack: move gc output functions to Gc module

- CHANGES.md
- irmin-tezos-utils.opam
- src/irmin-pack/inode_intf.ml
- src/irmin-pack/pack_value_intf.ml
- src/irmin-tezos-utils/dune
- src/irmin-tezos-utils/files.ml
- src/irmin-tezos-utils/import.ml
- src/irmin-tezos-utils/main.ml
- src/irmin-tezos-utils/parse.ml
- src/irmin-tezos-utils/show.ml
This pull request aims to add a graphical ui tool to irmin for pack files. This tool comes into to 2 different binaries:
- The first one, `irmin-parse` iterates a first time on a pack file, parsing it and saving useful information in two `.info` and `.idx` files.
- The second one, `irmin-show`, uses those 2 files in addition to the pack file in order to provide a graphical interface allowing the user to navigate trough the entries of the said pack file.
The end goal is to make it easier to search for specific things in a pack file, for example in the long term, for corrupted information.
Because it did not have it's place in `irmin-unix`, I also created a more fitting `irmin-utils` package.
Right now, this project is an early bird and this pull request should stay as a draft until it is …
> Add a utility ui for irmin packs

- CHANGES.md
- src/irmin-pack/unix/ext.ml
- src/irmin-pack/unix/s.ml
The function already existed and just needed some exposure :) (see https://github.com/mirage/irmin/issues/2098)
... but I sneaked a [commit](https://github.com/mirage/irmin/pull/2095/commits/85b9cf89a73d12c6b509725e33ae1841cc20d4b7) in https://github.com/mirage/irmin/pull/2095 to cleanup after a GC cancellation. The existing unit test reimplements a `kill_gc` function and can be simplified once one of those PR is merged. It was also tested manually by calling it within the Tezos replay trace.
> Expose GC cancel function

- CHANGES.md
- src/irmin-graphql/server.ml
- test/irmin-graphql/test.ml
This PR adds a simple query to ask the Irmin store to return the hash of some contents supplied as an argument. This is particularly useful if you want to refer to some piece of data by its hash but are not yet ready to store the value.
> irmin-graphql: add contents_hash query to graphql API

- CHANGES.md
- src/irmin-pack/layout.ml
- src/irmin-pack/unix/async.ml
- src/irmin-pack/unix/async_intf.ml
- src/irmin-pack/unix/ext.ml
- src/irmin-pack/unix/file_manager.ml
- src/irmin-pack/unix/file_manager_intf.ml
- src/irmin-pack/unix/gc.ml
- src/irmin-pack/unix/gc_intf.ml
- src/irmin-pack/unix/io_errors.ml
- src/irmin-pack/unix/mapping_file_intf.ml
- src/irmin-pack/unix/pack_store.ml
- src/irmin-tezos-utils/parse.ml
- test/irmin-pack/test_gc.ml
- test/irmin-pack/test_gc.mli
- test/irmin-pack/test_pack.ml
This PR removes files from the store that are not needed by the current generation:
- At `open_rw`, to clean up a harshly closed store on reboot
- After a GC crash, to get rid of the failed new generation
I'm not quite sure how to unit test the GC failures but there were two issues hiding in there:
- The GC worker writes its result `Ok final_offset | Error ...` in a temporary file. The `File_manager.read_gc_output` was unable to parse the error case in general as `repr` didn't quite like the polymorphic variants union (so the json decoding was crashing deep into `repr` internals)
- `lib_context` keeps on calling `finalise ~wait:false` to know the status of the GC. On a GC crash, the error handling was not marking the GC as finished and so the next `finalise` would attempt to wakeup a …
> Cleanup residual files

- src/irmin-pack/unix/append_only_file.ml
- src/irmin-pack/unix/append_only_file_intf.ml
- src/irmin-pack/unix/control_file_intf.ml
- src/irmin-pack/unix/dict.ml
- src/irmin-pack/unix/dispatcher.ml
- src/irmin-pack/unix/dispatcher_intf.ml
- src/irmin-pack/unix/file_manager.ml
- src/irmin-pack/unix/file_manager_intf.ml
- src/irmin-pack/unix/gc.ml
- src/irmin-pack/unix/traverse_pack_file.ml
- src/irmin-tezos-utils/dune
- src/irmin-tezos-utils/files.ml
- src/irmin-tezos-utils/show.ml
This PR normalises the offset variable names given the latest vocabulary that the team has converged to.
It also changes GC's `transfer_append_exn` to take the dispatcher directly. 
```
Usage of `poff` for physical offsets:
- persisted_end_offset -> persisted_end_poff
- end_offset -> end_poff
- refresh_end_offset -> refresh_end_poff
- dict_offset_end -> dict_end_poff
- offset_of_suffix_off -> offset_of_suffix_poff 
Removal of `right` which meant "right of the commit offset":
- right_start_offset -> new_suffix_start_offset
- right_end_offset -> new_suffix_end_offset
Fix of this CF's field. It doesn't contain a global offset, it contains physical offset
- entry_offset_suffix_end -> suffix_end_poff
Some other renames:
- entry_offset_suffix_start -> suffix_start_offset
- old_end_offset -> …
```
> irmin-pack: Cleanups related to offsets

- CHANGES.md
- src/irmin-pack/unix/ext.ml
- src/irmin-pack/unix/import.ml
- src/irmin-pack/unix/pack_store.ml
- src/irmin-pack/unix/traverse_pack_file.ml
- test/irmin-pack/test_existing_stores.ml
The traverse_pack_files on v2 stores are anyway broken https://github.com/mirage/irmin/pull/1903. But even more so on gced stores: the traversal of the suffix file needs to read gced objects, without knowing their size. 
We will need to come back to this once we have the good gc.
> Traverse gced pack stores

- CHANGES.md
- irmin-pack.opam
- src/irmin-pack/unix/control_file.ml
- src/irmin-pack/unix/control_file_intf.ml
- src/irmin-pack/unix/dune
- src/irmin-pack/unix/file_manager.ml
- test/irmin-pack/dune
- test/irmin-pack/test_corrupted.ml
- test/irmin-pack/test_corrupted.mli
- test/irmin-pack/test_pack.ml
This adds a small checksum to the control file payload to verify that we are not reading a partially written file (highly unlikely!.. but decoding such a broken control file always works so it's a bit hard to tell)
I've added a dependency to `checkseum`... but the checksum can be done differently if that's not desirable!
> Checksum control file

- src/irmin-pack/unix/control_file.ml
- src/irmin-pack/unix/control_file_intf.ml
- src/irmin-pack/unix/file_manager.ml
This PR extends #2115 by adding fields to `V4` of the control file needed for a chunked suffix. This is a part of #2096.
The following fields are added:
- `chunk_start_idx` to indicate the starting index for the chunks
- `chunk_num` to indicate the number of chunks
The following field is added to the `Gced` status:
- `suffix_dead_bytes` to indicate bytes that could not be reclaimed during a GC (because of a suboptimal commit placement or during the time before an existing store has migrated to an optimally chunked suffix) but should be considered dead/unreachable in the suffix. In a future PR, the dispatcher will use this when constructing accessors. It is worth noting that the chunked suffix abstraction _can_ read these bytes still but we would like to enforce reading these bytes from …
> irmin-pack: add chunked suffix fields to control file

- CHANGES.md
- src/irmin-pack/unix/chunked_suffix.ml
- src/irmin-pack/unix/chunked_suffix_intf.ml
- src/irmin-pack/unix/dispatcher.ml
- src/irmin-pack/unix/errors.ml
- src/irmin-pack/unix/ext.ml
- src/irmin-pack/unix/file_manager.ml
- src/irmin-pack/unix/file_manager_intf.ml
- src/irmin-pack/unix/gc.ml
- src/irmin-pack/unix/io_errors.ml
- src/irmin-pack/unix/s.ml
- test/irmin-pack/test_gc.ml
- test/irmin-pack/test_gc.mli
- test/irmin-pack/test_pack.ml
Rebased on #2115.
I want to add more tests, but I will not change too much the code, apart from adapting to  #2115 and #2117.
> Add split function to create a new chunk 

- CHANGES.md
- examples/gc.ml
- src/irmin-pack/unix/chunked_suffix.ml
- src/irmin-pack/unix/chunked_suffix_intf.ml
- src/irmin-pack/unix/dispatcher.ml
- src/irmin-pack/unix/dispatcher_intf.ml
- src/irmin-pack/unix/file_manager.ml
- src/irmin-pack/unix/file_manager_intf.ml
- src/irmin-pack/unix/gc.ml
- src/irmin-pack/unix/gc_worker.ml
- src/irmin-pack/unix/gc_worker.mli
- src/irmin-pack/unix/import.ml
- test/irmin-pack/test_gc.ml
This PR is a part of #2096. It modifies the GC procedure to work with the new chunked suffix.
Chunked suffix GC is different from current (Irmin 3.4) GC in the following ways:
- The GC no longer necessarily removes bytes _on disk_ from the beginning of the suffix. Bytes are removed on disk only when chunks are strictly before the split point of the GC. 
- Even though these bytes may still exist on disk, the dispatcher continues to direct reads before the split point to the prefix. A new field, `suffix_dead_bytes`, is used by the dispatcher to properly read from the suffix.
- If you only have one chunk (that is, you never call `split`), no data will ever be removed during GC.
> irmin-pack: update GC to work with chunked suffix

- src/irmin-pack/unix/ext.ml
- src/irmin-pack/unix/file_manager.ml
- src/irmin-pack/unix/file_manager_intf.ml
- src/irmin-pack/unix/pack_index.ml
- src/irmin-pack/unix/pack_index_intf.ml
- src/irmin-tezos-utils/files.ml
- test/irmin-pack/common.ml
- test/irmin-pack/test_inode.ml
- test/irmin-pack/test_pack_version_bump.ml
This simple PR cleans the functors of the File_manager module. It removes the need of a reference to Unix in said module.
It was first part of a bigger work, to abstract the offsets. However it appeared that it would be way more complicated and annoying to do.
Therefore, in the meantime, I decided to push this first modification as a separate work
> irmin-pack: Clean file manager functors

- src/irmin-pack/unix/file_manager.ml
- test/irmin-pack/test_gc.ml
While working on https://github.com/mirage/irmin/pull/2135 I noticed a strange thing in its store directory -- there was no prefix and mapping file at the end of a run! 
It turns out that as a part of the [PR that introduced `split`](https://github.com/mirage/irmin/pull/2118), we accidentally pass the wrong `generation` value to the file manager's `cleanup` function. This code seems to have been lifted from the GC process, which needed to subtract 1 from its `generation` since it was working on the next `generation`; however, in the context of the file manager, we need to use the currently saved `generation`. This PR fixes this issue.
Aside: I wasn't sure exactly where to place the test, so I put it alongside the other GC close/kill tests in the "concurrent gc" module.
> irmin-pack: fix file manager cleanup

- CHANGES.md
- src/irmin-pack/unix/errors.ml
- src/irmin-pack/unix/ext.ml
- src/irmin-pack/unix/file_manager.ml
- src/irmin-pack/unix/file_manager_intf.ml
- src/irmin-pack/unix/gc.ml
- src/irmin-pack/unix/gc.mli
- src/irmin-pack/unix/gc_worker.ml
- src/irmin-pack/unix/gc_worker.mli
- src/irmin-pack/unix/io.ml
- src/irmin-pack/unix/io_errors.ml
- src/irmin-pack/unix/io_intf.ml
- src/irmin-pack/unix/s.ml
- test/irmin-pack/test_gc.ml
- test/irmin-pack/test_gc.mli
- test/irmin-pack/test_pack.ml
After discussions with @vect0r-vicall, I'm working on a new snapshot export that:
- calls gc on the commit for which we want to create the snapshot;
- copies the resulting prefix, mapping (and dict is needed too) to a new directory; 
- that directory is the new snapshot format 
The import:
- opens a new store from a prefix, mapping and a dict, by creating a new control file;
- add the commit to a fresh index. 
This is WIP, but I would appreciate any feedback, in case I missed something. Things that I see to improve are:
- instead of manipulating the type snap in the code, we could write to a file;
- the control file after a snapshot import looks a lot like after a gc - we could introduce an extra status to differentiate the two
- a better management for dict?
> Gc-based snapshots

- src/irmin-pack/unix/chunked_suffix.ml
- src/irmin-pack/unix/chunked_suffix_intf.ml
- src/irmin-pack/unix/control_file.ml
- src/irmin-pack/unix/control_file_intf.ml
- src/irmin-pack/unix/dispatcher.ml
- src/irmin-pack/unix/file_manager.ml
- src/irmin-tezos-utils/show.ml
This PR addresses some naming confusion while developing the new chunked suffix through renaming and cleanup.
Previously, we used `end_poff` for a couple of things:
1. To know the end offset for the suffix (synonymous with its length)
2. To keep track in the control file (`suffix_end_off`) the last known offset we flushed for consistency checks and coordination with read-only stores
With the introduction of a chunked suffix, we no longer have a single "end poff" -- we have as many as there are chunks, but we still have the above needs. To this end, this PR does two primary things (along with associated cleanup):
1. Renames `Chunked_suffix.length` to `Chunked_suffix.end_soff` to reinforce our growing usage of `soff` as a "suffix offset"
2. Renames `Chunked_suffix.end_poff` and …
> irmin-pack: rename `end_poff` for chunked suffix

- bench/irmin-pack/trace_replay.ml
- bench/irmin-pack/trace_replay_intf.ml
- bench/irmin-pack/tree.ml
- test/irmin-bench/replay.ml
This PR adds the new `split` function to the trace reply in `bench/irmin-pack`. 
We will likely want to update these benchmarks/trace replays to follow the changes that @Ngoguey42 is making to our `lib_context` replay benchmarks, but this change is needed to for the GC in the replay to continue working since `split` is needed for the new chunk-based GC to function correctly.
> bench: add split to irmin-pack trace replay

- README.md
Hi! This feature is just a typo fix on README.md from `debuggin` -> `debugging` which did not look intentional. I looked through `contributing.md` and didn't find instructions on typo fixes. Have a nice day!
> Fixed typo [debuggin] -> [debugging]

- src/irmin/store_intf.ml
Just a little extra naming in the documentation for `merge_into`. I hit this twice and because of the way LSP shows the type I always end up digging into the source code to know what I need to add. This is what it currently looks like for me:
> Clarify merge_into documentation

- src/irmin-pack/unix/errors.ml
- src/irmin-pack/unix/gc.ml
- src/irmin-pack/unix/gc_worker.ml
- src/irmin-pack/unix/io_errors.ml
This fixes two issues for the `create_one_commit_store` function: 
- report errors that appeared in the gc process 
- allow the function to work when the gc commit is indexed.
> Fix snapshots export for commits with indexed parents 

- CHANGES.md
- src/irmin-pack/unix/gc_args.ml
- src/irmin-pack/unix/gc_worker.ml
- src/irmin-pack/unix/inode.ml
- src/irmin-pack/unix/inode_intf.ml
- src/irmin-pack/unix/mapping_file.ml
- src/irmin-pack/unix/mapping_file_intf.ml
- src/irmin-pack/unix/pack_key.ml
- src/irmin-pack/unix/pack_key_intf.ml
- src/irmin-pack/unix/pack_store.ml
- src/irmin-pack/unix/pack_store_intf.ml
- test/irmin-pack/test_gc.ml
- test/irmin-pack/test_mapping.ml
I've been looking at the GC reachability traversal. I still have some ideas but I would like to avoid going down too far the wrong path because I overlooked something... The quoted numbers are from the Tezos replay trace, running the GC pretty aggressively (so real life might behave differently? by how much?)
- The GC traversal of the tree uses a hashtable to avoid revisiting the same objects again (because it's actually a DAG). However it only checks the hashtable **after** re-inserting the `(offset,length)` into the reachable file: The reachable file ends up with 28m pairs (~440Mb) that gets sorted/deduplicated in ~15s. On the Tezos replay trace, I'm seeing a lot of duplication as there are actually 14m real objects (6m contents + 8m nodes, with indistinct repetitions for both kinds). …
> GC reachability traversal in revorder

- CHANGES.md
I forgot to add `irmin-pack` as the project when I [added](https://github.com/mirage/irmin/pull/2085/commits/83984d6f35b522b3ca4224a2caa63c80b5b6173e) this entry to the changelog.
> Add project to changelog

- src/irmin-pack/unix/gc_worker.ml
- test/irmin-pack/test_snapshot.ml
Similar to https://github.com/mirage/irmin/pull/2151. It fixes the gc worker for when one of the parents of the gc commit is of type Indexed. This occurs in V3 tezos snapshots.
> Add test for indexed parent in a gc

- CHANGES.md
- irmin-cli.opam
- irmin-graphql.opam
- irmin-http.opam
- src/irmin-pack/unix/checks.ml
This PR is bringing changes that came up during the 3.5.1 release (https://github.com/mirage/irmin/pull/2162), either in testing or during the opam CI process.
> Updates from 3.5.1 release

- src/irmin-pack/inode.ml
While debugging an issue that triggered this exception, I saw an opportunity to modify it to (hopefully) help us in the future.
This PR makes two changes to improve the log message that comes from this exception:
1. Specify this is an inode key. Based on context of the issue, the initial assumption upon seeing the error in a log was that it was a commit key. Oops. I finally realized it was not when I grepped the code.
2. Include context. This code already supports specifying a context, so lets include it!
> irmin-pack: improve inode error message

- CHANGES.md
- src/irmin-pack/unix/async.ml
- test/irmin-pack/dune
- test/irmin-pack/test_async.ml
- test/irmin-pack/test_async.mli
- test/irmin-pack/test_pack.ml
This fixes a bug where unhandled exceptions for an async task were treated as a `Succes` instead of `Failure`. I discovered this while looking into #2161.
This PR addresses this issue by:
1. Change to using exit codes instead of signals to determine success or not.
2. Return a specific exit code to indicate an unhandled exception.
Previously, we used `SIGKILL` to prevent `at_exit` hooks from executing. I preserved this functionality but ~~left a comment in the code since~~ I'm not sure if we need or want to do this or not. The benefit I see is that you don't accidentally run exit hooks from the parent process, which seems beneficial when running within applications that we do not control (like octez). A drawback is that _maybe_ the logs aren't flushed, which would mean things like the …
> irmin-pack: treat unhandled exception in async task as a failure

- irmin-pack.opam
This PR raises the lower bound for `irmin-pack`. https://github.com/mirage/irmin/pull/2163 introduced `Unix._exit`, which is only available since 4.12.
The lower bounds for OCaml versions in Irmin packages tends to be very conservative, but I think it is okay to bump `irmin-pack`, especially since we are considering going to `>= 5.0` at some point.
> irmin-pack: change ocaml to >= 4.12.0

- src/irmin-pack/version.ml
- src/irmin-pack/version.mli
While gathering information about various versions used in `irmin-pack`, I noticed that `Version.latest` hadn't been updated when adding `V4`. This value being out of sync does not cause any issues since it is not used in the code base, thankfully, but should be fixed regardless. I also added a small doc comment for `V4` to the header, in the spirit of prior comments.
> irmin-pack: update latest version and add doc

- test/irmin-pack/dune
- test/irmin-pack/test_indexing_strategy.ml
- test/irmin-pack/test_indexing_strategy.mli
- test/irmin-pack/test_pack.ml
This PR demonstrates that switching to minimal indexing will write new data even if it already exists in the index.
I couldn't find any existing tests that test this behavior but thought it would be good to have verification of this for upcoming migrations of archive nodes.
> irmin-pack: test indexing strategy switch

- CHANGES.md
- src/irmin-pack/conf.ml
- src/irmin-pack/conf.mli
- src/irmin-pack/irmin_pack_intf.ml
- src/irmin-pack/unix/control_file_intf.ml
- src/irmin-pack/unix/errors.ml
- src/irmin-pack/unix/file_manager.ml
- src/irmin-pack/unix/file_manager_intf.ml
- src/irmin-pack/unix/io.ml
- src/irmin-pack/unix/io_errors.ml
- src/irmin-pack/unix/io_intf.ml
- src/irmin-pack/unix/mapping_file.ml
- src/irmin-pack/unix/mapping_file_intf.ml
- src/irmin-pack/unix/store.ml
- test/irmin-pack/common.ml
- test/irmin-pack/common.mli
- test/irmin-pack/test_gc.ml
- test/irmin-pack/test_upgrade.ml
This PR adds the config key for the upcoming lower layer, with validation during `Repo.v`.
I didn't want to add a new error message just for an invalid `lower_root` value, and I also wanted good log message if the error occurs. To accomplish both, I am reusing `No_such_file_or_directory` and have added a string value for the file path. I think this also improves this error generally.
> irmin-pack: add lower_root config for lower layer

- CHANGES.md
- src/irmin-pack/unix/checks.ml
- src/irmin-pack/unix/checks_intf.ml
- src/irmin-pack/unix/utils.ml
This is a fix for https://github.com/mirage/irmin/issues/2170.
The user can ask for silent integrity checks by not providing a `ppf` argument. But there was a bug, the progress bars in integrity checks were not using the same ppf as the one set by the user. 
Manually tested this using  `dune exec -- ./test/irmin-tezos/irmin_fsck.exe integrity-check ...`.
> irmin-pack: fix silent mode for integrity checks

- src/irmin-pack/unix/control_file.ml
- src/irmin-pack/unix/control_file_intf.ml
- src/irmin-pack/unix/dispatcher.ml
- src/irmin-pack/unix/file_manager.ml
- src/irmin-pack/unix/file_manager_intf.ml
- src/irmin-pack/unix/gc_worker.ml
- src/irmin-pack/unix/gc_worker.mli
This PR refactors control file to support more than one type of control file and adds the initial version of a volume control file. 
I left TODOs for things that we will need to address before release, but I'll re-iterate them here with some added thoughts/context:
- update volume to V5 when we bump the pack store version
- make a more specific error for `Corrupted_control_file` so that we can know _which_ control file is at fault. This can likely be as simple as giving a string that we put a message into.
- add specific error for when the length is longer than a page size. Currently, this is also `Corrupted_control_file` but it seems better to be specific with this error. Also, we should add path information to the error.
- add an error for V1|V2 instead of assert false. This isn't …
> irmin-pack: introduce volume control file

- src/irmin-pack/layout.ml
- src/irmin-pack/unix/control_file.ml
- src/irmin-pack/unix/control_file_intf.ml
- src/irmin-pack/unix/errors.ml
- src/irmin-pack/unix/io_errors.ml
- src/irmin-pack/unix/irmin_pack_unix.ml
- src/irmin-pack/unix/irmin_pack_unix.mli
- src/irmin-pack/unix/lower.ml
- src/irmin-pack/unix/lower.mli
- src/irmin-pack/unix/lower_intf.ml
- test/irmin-pack/dune
- test/irmin-pack/test_lower.ml
- test/irmin-pack/test_lower.mli
- test/irmin-pack/test_pack.ml
This is the first PR for the new lower layer. It builds on the introduction of the volume control file in #2180 by introducing a minimal lower layer module that enables:
- loading volumes contained in a root path
- adding new empty volumes
- finding a volume that can address a global offset
I tried not to make too many assumptions about how we want to integrate this since I expect subsequent PRs that add specific functionality to shape the `Lower` and `Volume` modules quite a bit.
> irmin-pack: introduce lower layer + volumes

- CHANGES.md
- src/irmin-pack/unix/control_file.ml
- src/irmin-pack/unix/control_file_intf.ml
- src/irmin-pack/unix/file_manager.ml
- src/irmin-pack/version.ml
- src/irmin-pack/version.mli
- test/irmin-pack/test_pack_version_bump.ml
This PR makes changes for the upper control file needed for the lower layer and bumps the irmin-pack version to V5.
- Add `volume_num` to upper control file.
- Change version of volume control file to V5. 
- Refactor checksum code to model valid and invalid payloads and allow checking checksums when upgrading.
I ran into one small issue where I wanted to use `Version.t option` as a type in the control file (for tracking upgrades) but ran into an error in the tests that seems to be coming out of repr (or maybe the `version.ml` code -- my brief investigation didn't shed light on what was going on). To get around this, I changed the type to `int option` and am using `Version.to_int V4` when setting the value during an upgrade. It's not the most ideal but not the worst thing either. If …
> irmin-pack: add V5 version

- CHANGES.md
- src/irmin-fs/irmin_fs.mli
- src/irmin-fs/unix/irmin_fs_unix.mli
- src/irmin-git/irmin_git.ml
- src/irmin/irmin.ml
- src/irmin/irmin.mli
- src/irmin/store_intf.ml
That allows to re-use the same info function in various store - in practice backend are either using Irmin.Info.default or Imin_unix.info so it's a bit odd to hide that equality.
> irmin: expose info type equality

- src/irmin-tezos-utils/show.ml
- Adds information about the parent commit of objects, notifying the user when the target entry has been added by the same commit that added the current entry (or if the target entry was added by the current commit when checking a commit).
- Adds buttons to directly jump to said parent commit.
- Modify format of integers for a better reading of long values.
> irmin-tezos-utils: Add informations on parent commits

- CHANGES.md
- src/irmin-pack/unix/errors.ml
- src/irmin-pack/unix/file_manager.ml
- src/irmin-pack/unix/file_manager_intf.ml
- src/irmin-pack/unix/io_errors.ml
- src/irmin-pack/unix/lower_intf.ml
- src/irmin-pack/unix/store.ml
- src/irmin-pack/unix/store_intf.ml
- test/irmin-pack/common.ml
- test/irmin-pack/common.mli
- test/irmin-pack/test_lower.ml
- test/irmin-pack/test_lower.mli
- test/irmin-pack/test_pack.ml
This PR does a few things to integrate the lower module into the higher level store code:
- creates the lower root path if needed
- loads the lower when opening/creating a store, if a lower is configured
- creates an empty volume when creating a store, if a lower is configured
- adds an `add_volume` function to the store api
- adds a few tests to exercise the above
There are some TODOs for subsequent PRs:
~~(Note: this PR is based on #2184 so skip the first couple of commits if reviewing before it is merged)~~
> irmin-pack: initial integration of lower into store api

- src/irmin-pack/unix/dispatcher.ml
- src/irmin-pack/unix/dispatcher_intf.ml
- src/irmin-pack/unix/file_manager.ml
- src/irmin-pack/unix/gc_worker.ml
- src/irmin-pack/unix/sparse_file.ml
- src/irmin-pack/unix/sparse_file_intf.ml
- test/irmin-pack/test_mapping.ml
To allow updating the lower volumes :)
(This was a good opportunity to refactor the GC to use the new append functionality, and hence test that it works!)
> irmin-pack: appending into the sparse file

- src/irmin-pack/unix/errors.ml
- src/irmin-pack/unix/file_manager.ml
- src/irmin-pack/unix/io_errors.ml
- test/irmin-pack/test_lower.ml
Follow up from #2188 to return an error when calling `add_volume` and there is no lower configured.
> irmin-pack: adding a volume w/o lower is an error

- src/irmin-pack/unix/checks.ml
- src/irmin-pack/unix/dispatcher.ml
- src/irmin-pack/unix/dispatcher_intf.ml
- src/irmin-pack/unix/errors.ml
- src/irmin-pack/unix/file_manager.ml
- src/irmin-pack/unix/io_errors.ml
- src/irmin-pack/unix/lower.ml
- src/irmin-pack/unix/lower_intf.ml
- src/irmin-pack/unix/pack_key.ml
- src/irmin-pack/unix/pack_key_intf.ml
- src/irmin-pack/unix/pack_store.ml
- src/irmin-pack/unix/snapshot.ml
- src/irmin-pack/unix/sparse_file.ml
- src/irmin-pack/unix/store.ml
- src/irmin-pack/unix/traverse_pack_file.ml
- src/irmin-tezos-utils/files.ml
- test/irmin-pack/test_dispatcher.ml
- test/irmin-pack/test_indexing_strategy.ml
- test/irmin-pack/test_lower.ml
- test/irmin-pack/test_upgrade.ml
This PR:
- adds a `read_exn` function to `Lower`
- limits "open" volumes to one at a time for a simple management of open file descriptors
- adds `volume_identifier` to direct keys to allow tracking the context of a read so that subsequent reads can skip looking in the upper
- handles dangling parent commits by not propagating the volume identifier to them, thereby forcing a fresh lookup
> irmin-pack: implement reading from lower

- src/irmin-pack/layout.ml
- src/irmin-pack/unix/file_manager.ml
- test/irmin-pack/test_pack.ml
As pointed out in #2197, we need classification for volumes. So this PR does that. :sunglasses:
> irmin-pack: add classification for volume files

- CHANGES.md
- src/irmin-pack/unix/file_manager.ml
- src/irmin-pack/unix/file_manager_intf.ml
- src/irmin-pack/unix/gc.ml
- src/irmin-pack/unix/pack_store.ml
- test/irmin-pack/test_gc.ml
Currently, when a RO instance calls `reload`, the LRU is not cleared. We have seen some issues in octez that we _think_ is caused by this behavior. See #2171. 
When opening that issue, I originally made the assumption we did not have what we needed to "smartly" clear the LRU for RO instances, but I had an idea upon second consideration. During `reload`, we only reopen the prefix if the generation changes so we can use that as our signal to clear the LRU. With some refactoring, that is what this PR does.
In order to clear the LRU when `reload` is called, this is a general refactor to move clearing of the LRU to happen when the prefix is reopened. This covers both a swap after a GC and when reload is called for a RO instance.
I added some new tests to verify the LRU has cleared for both a …
> irmin-pack: clear LRU when reloading RO

- src/irmin-pack-tools/tezos_explorer/files.ml
- src/irmin-pack/unix/dispatcher.ml
- src/irmin-pack/unix/dispatcher_intf.ml
- src/irmin-pack/unix/lower.ml
- src/irmin-pack/unix/lower_intf.ml
- src/irmin-pack/unix/pack_store.ml
- src/irmin-pack/unix/sparse_file.ml
- src/irmin-pack/unix/traverse_pack_file.ml
- src/irmin-pack/unix/utils.ml
I ran into this edge-case when testing the fast migration to a lower volume. The children objects' headers are read with `read_range_exn` which only supported reading from the upper store. (cc @Firobe as this should also be useful for #2202)
> irmin-pack: fix read object headers from lower volumes

- CHANGES.md
- src/irmin-pack/unix/control_file_intf.ml
- src/irmin-pack/unix/errors.ml
- src/irmin-pack/unix/file_manager.ml
- src/irmin-pack/unix/file_manager_intf.ml
- src/irmin-pack/unix/io_errors.ml
- src/irmin-pack/unix/lower.ml
- src/irmin-pack/unix/lower_intf.ml
- src/irmin-pack/unix/sparse_file.ml
- src/irmin-pack/unix/sparse_file_intf.ml
- test/irmin-pack/test_lower.ml
(builds on top of #2204)
A draft for the fast migration when enabling lower volumes from an existing store (which only had an upper suffix file, never garbage collected or chunk splitted). I went with a file copy rather than a move when initializing the lower volume to avoid any surprise if the operation fails midway... it should be as efficient as a rename when happening on the same hard drive anyway :) But the code is still missing some way of recovering and cleaning up the drive if the migration fails!
> irmin-pack: fast migration to lower by copy

- CHANGES.md
This PR adds the [3.5.2 release](https://github.com/mirage/irmin/pull/2203) to the changelog and adds some missing dates to recent releases.
> Add 3.5.2 and missing dates to changelog

- src/irmin-pack/unix/chunked_suffix.ml
- src/irmin-pack/unix/chunked_suffix_intf.ml
- src/irmin-pack/unix/dispatcher.ml
- src/irmin-pack/unix/dispatcher_intf.ml
- src/irmin-pack/unix/lower.ml
- src/irmin-pack/unix/lower_intf.ml
- src/irmin-pack/unix/pack_store.ml
- src/irmin-pack/unix/sparse_file.ml
- src/irmin-pack/unix/sparse_file_intf.ml
- src/irmin-pack/unix/traverse_pack_file.ml
- test/irmin-pack/test_lower.ml
After a migration, the GC might have to read live data from the lower volume to construct the prefix (with `Dispatcher.read_seq_exn` which only supported reading from the upper store).
> irmin-pack: fix GC creation of prefix from lower volume data after migration

- src/irmin-pack/layout.ml
- src/irmin-pack/unix/control_file.ml
- src/irmin-pack/unix/control_file_intf.ml
- src/irmin-pack/unix/errors.ml
- src/irmin-pack/unix/file_manager.ml
- src/irmin-pack/unix/file_manager_intf.ml
- src/irmin-pack/unix/io_errors.ml
- src/irmin-pack/unix/lower.ml
- test/irmin-pack/test_lower.ml
- test/irmin-pack/test_pack.ml
This PR changes the writing of control files: They were currently updated while making the assumption that the file itself being smaller than a page, the writing would be atomic. However it was deemed dubious that we could use such an assumption.
This is why this PR:
- Adds the usage of temporary control file when writing a new payload (path of the cf + `.tmp`).
- Moves the temporary file in stead of the old control file.
- Then updates the `Io` file stored in the `Control_file.t` with the new
- On the RO instances side, it simply re-opens a new Io file, as the old file descriptor might point to the inode of a file replaced by the RW instance.
- Updates the errors of the related functions.
This leaves however one question in the case of RO instances:
Because we open a new `Io` each time …
> irmin-pack: Use temp control files upon writing

- src/irmin-pack/unix/file_manager.ml
- src/irmin-pack/unix/file_manager_intf.ml
- src/irmin-pack/unix/gc.ml
- src/irmin-pack/unix/pack_store.ml
- test/irmin-pack/test_gc.ml
This is a forward port of https://github.com/mirage/irmin/pull/2200. It is already released in 3.6.1, so no need to mention in changes.
Closes #2171
> irmin-pack: clear LRU when reloading RO (forward port to main)

- src/irmin-pack/unix/lower.ml
- src/irmin-pack/unix/pack_key.ml
- src/irmin-pack/unix/pack_key_intf.ml
- src/irmin-pack/unix/pack_store.ml
- src/irmin-pack/unix/sparse_file.ml
- test/irmin-pack/test_lower.ml
This PR adds a test to confirm the reading a commit and its data in a volume only reads data from that volume.
I discovered that commit keys did not have a volume identifier after read, so this PR also fixes that. The previous behavior didn't break anything, but it's nice to be able to inspect a commit after you read it to know which volume (if any) it came from.
> irmin-pack: test data locality for volumes

- src/irmin-pack/unix/gc.ml
- src/irmin-pack/unix/io.ml
- src/irmin-pack/unix/io_intf.ml
First try to tackle #2220.
This adds `Io.unlink_async` which calls `Lwt_unix.unlink`.
Lwt maintains a pool of system threads where the unlinks will be called, thus not blocking the main application thread.
I'm not sure if this will provide any real benefits as Gc is still waited on by `Async.await`.
> irmin-pack.unix: Use asynchronous unlink when cleaning up chunks in Gc.

- CHANGES.md
- src/irmin-pack/unix/errors.ml
- src/irmin-pack/unix/gc_stats.ml
- src/irmin-pack/unix/gc_stats.mli
- src/irmin-pack/unix/gc_worker.ml
- src/irmin-pack/unix/io_errors.ml
- src/irmin-pack/unix/lower.ml
- src/irmin-pack/unix/lower_intf.ml
- test/irmin-pack/test_gc.ml
Update the GC step "copy deleted data to lower volume" to not include the (orphaned) unreachable commits (and their tree).
> irmin-pack: archive only reachable objects

- src/irmin-pack/unix/file_manager.ml
- src/irmin-pack/unix/store.ml
- test/irmin-pack/test_lower.ml
I don't think the field `latest_gc_target_offset` is very useful atm, but at least we should make it easier to detect that a migration to the lower didn't have a GC commit.
> irmin-pack: migration to lower has unknown GC target

- CHANGES.md
- src/irmin/store.ml
- src/irmin/store_intf.ml
- src/irmin/tree.ml
- test/irmin/test_tree.ml
Expose the `clear` flag threaded through to `Tree.export`.
With this, using`S.set_tree_exn ~clear:fase` in https://gitlab.com/tezos/tezos/-/merge_requests/8169 seems to fix the issue.
It's also unclear what the default should be - There's an explicit `Tree.clear` for those who really want to clear the caches, so maybe by default, we should have `clear=false`?
> irmin: allow to keep tree caches after a commit

- src/irmin-pack/unix/checks.ml
- src/irmin-pack/unix/checks_intf.ml
Fix integrity check command to use supplied ppf when printing successful results. Errors are still printed to stderr.
Closes #2211
> irmin-pack: use supplied ppf for integrity check

- test/irmin-pack/test_gc.ml
This fixes flakey test failures introduced by #2221 caused by files still existing that are being unlinked asynchronously (see https://github.com/mirage/irmin/pull/2227#issuecomment-1486707570).
The introduced `check_asyn_unlinked` function takes a timeout argument and checks if the file has been unlinked within the specified timeout period.
Tested locally:
I've run the tests multiple times and can not reproduce the conditions observed in the CI. Still, I believe this should fix the issue.
> irmin-tezos (test_gc): Add `check_async_unlinked` that checks if a file has been unlinked asynchronously.

- bench/irmin-pack/trace_replay.ml
- bench/irmin-pack/trace_replay_intf.ml
- bench/irmin-pack/tree.ml
- test/irmin-bench/replay.ml
This PR updates the `bench/irmin-pack/tree.ml` and related files to support a lower layer and adding volumes during replay.
One flag is added to the tree exec, `add-volume-every`. It defaults to 0. Setting it to a number greater than 0 will create a lower layer and add a new volume every N GCs.
> bench: update tree replay to support lower layer

- CHANGES.md
- src/irmin-pack/unix/control_file.ml
- src/irmin-pack/unix/control_file_intf.ml
- src/irmin-pack/unix/file_manager.ml
- src/irmin-pack/unix/file_manager_intf.ml
- src/irmin-pack/unix/gc.ml
- src/irmin-pack/unix/gc.mli
- src/irmin-pack/unix/gc_worker.ml
- src/irmin-pack/unix/gc_worker.mli
- src/irmin-pack/unix/lower.ml
- src/irmin-pack/unix/sparse_file.ml
- src/irmin-pack/unix/sparse_file_intf.ml
- src/irmin-pack/unix/store.ml
- test/irmin-pack/test_mapping.ml
Since the mapping file is read-only, we can simulate the mmap in userland by lazily reading chunks on demand (and avoid the [file descriptor leak](https://github.com/mirage/irmin/pull/2196) from mmaped bigarrays..) There are a bunch of optimizations that we could try here, but I'm curious how the benchmarks are impacted by this change before going too deep into this rabbit hole :)
(also added the expected `mapping_size` in the control file as a consistency check to detect a partially written mapping, after a gc or a snapshot)
> irmin-pack: no mmap syscall

- CHANGES.md
- src/irmin-pack/unix/file_manager.ml
- test/irmin-pack/test_lower.ml
Previously we did not take the dead header of the dict into account when performing a lower layer migration for older stores. This commit fixes this issue by removing the dead header from the dict during the migration.
I also added some tests for v3 stores and updated migration tests to ensuring reading contents after a migration works. These tests all passed anyway, but thought it didn't hurt for completeness against potential future changes.
> irmin-pack: fix v2 lower migration

- src/irmin-pack/unix/gc_worker.ml
- src/irmin-pack/unix/irmin_pack_unix.ml
- src/irmin-pack/unix/irmin_pack_unix.mli
- src/irmin-pack/unix/ranges.ml
- src/irmin-pack/unix/ranges.mli
- test/irmin-pack/dune
- test/irmin-pack/test_pack.ml
- test/irmin-pack/test_ranges.ml
Legacy archive node can contain "out of order" objects, caused by a buggy tree export, where parent nodes can have a smaller offset than their children... This then trigger an issue when the sparse `prefix` file is created, as it detects the out-of-order live range.
Since we don't expect a lot of out-of-order ranges (compared to in-order ranges), this PR handle them in a separate list that is merged at the end with the bulk of in-order ranges.
> irmin-pack: support out-of-order objects in GC reachability analysis

- CHANGES.md
- src/irmin-cli/resolver.ml
- src/irmin-cli/resolver.mli
- test/irmin-cli/test_command_line.t
The information in the Irmin website uses "fs" where-as the irmin-cli Resolver uses "irf". Changed command line and module sig to use fs and also updated cram tests.
**NOTE previous use of "irf" will now error, I wasn't sure whether backwards compatibility was expected?**
As an example, looking at the cli `--help` segment:
before
```
-s VAL, --store=VAL
The storage backend (one of git, git-mem, irf, mem, mem-http,
git-http, pack or tezos). Default is `git'.
```
after
```
-s VAL, --store=VAL
The storage backend (one of git, git-mem, fs, mem, mem-http,
git-http, pack or tezos). Default is `git'.
```
> irmin-cli: change --store irf to --store fs

- CHANGES.md
- src/irmin/conf.ml
- src/irmin/conf.mli
- test/irmin/test_conf.ml
This bit me while working on the memory-bounded LRU (no, I obviously did not copy-pasta an existing key 🫣).
I don't think there is a valid use case for calling `key` twice with the same name but different types, and it can result in annoying to debug runtime behavior since it will silently return the default value for the overwritten key.
> irmin: raise exception on duplicate Conf key name

- src/irmin-pack/unix/store.ml
- src/irmin-pack/unix/store_intf.ml
This is useful for traversing the store with external tooling.
Exposing this migh reduce the number of functors that need to be manually created in tools such as the [tezos-explorer](https://github.com/mirage/irmin/tree/main/src/irmin-pack-tools). cc @clecat
> irmin-pack.unix: Expose dispatcher in the `Internal` module.

- irmin-mirage-git.opam
- src/irmin-mirage/git/irmin_mirage_git.ml
- src/irmin-mirage/git/irmin_mirage_git_intf.ml
This PR updates `irmin-mirage-git` for the latest `mirage-kv` (~~5.0.0+~~ 6.0.0+).
Closes #2083
> irmin-mirage-git: update for latest versions of `mirage-kv`

- src/irmin/tree.ml
- test/irmin-pack/test_tree.ml
Rebase of #2253 for the upcoming release :)
See description in #2253
> Optimize Tree.length for irmin 3.7

- CHANGES.md
- src/irmin-pack/unix/gc.ml
- src/irmin-pack/unix/gc.mli
- src/irmin-pack/unix/store.ml
- test/irmin-pack/test_gc.ml
GC-based snapshot export did not work if called with a commit that is older than the latest GC commit.
> irmin-pack: fix snapshot export

- CHANGES.md
- Add missing entry
- Fix formatting inconsistencies
> Tidying CHANGES

- CHANGES.md
- src/irmin-pack/conf.ml
- src/irmin-pack/conf.mli
- src/irmin-pack/import.ml
- src/irmin-pack/inode.ml
- src/irmin-pack/irmin_pack_intf.ml
- src/irmin-pack/pack_value.ml
- src/irmin-pack/pack_value_intf.ml
- src/irmin-pack/unix/gc_args.ml
- src/irmin-pack/unix/gc_worker.ml
- src/irmin-pack/unix/inode_intf.ml
- src/irmin-pack/unix/irmin_pack_unix.ml
- src/irmin-pack/unix/irmin_pack_unix.mli
- src/irmin-pack/unix/lru.ml
- src/irmin-pack/unix/lru.mli
- src/irmin-pack/unix/pack_store.ml
- src/irmin-pack/unix/pack_store_intf.ml
- src/irmin-pack/unix/store.ml
- src/irmin/lru.ml
- src/irmin/lru.mli
- test/irmin-pack/common.ml
- test/irmin-pack/test_inode.ml
- test/irmin/test_lru.ml
At a high-level, this PR:
1. Unifies the previous 3 LRUs in `irmin-pack` into one
2. Adds a configuration option to bound the LRU by memory used instead of entry count
3. Maintains previous cap of "large" contents objects for both entry-based cap and memory-based cap
When deciding how to count the memory usage of objects in the LRU, two paths were evaluated: using `Obj.reachable_words` or using `repr`'s size function. The former was too slow in replay benchmarks, so that latter is used. The size is used as-is for commits and contents, and a correction factor, based on benchmark observations, is applied to inode sizes.
The definition of "large" for contents objects is 20kB. This seems like a reasonable value based on [previous analysis of object …
> irmin-pack: unify LRUs and add max memory config

- CHANGES.md
- examples/irmin-pack/gc.ml
- examples/irmin-pack/kv.ml
- src/irmin-pack-tools/tezos_explorer/files.ml
- src/irmin-pack-tools/tezos_explorer/show.ml
- src/irmin-pack/conf.ml
- src/irmin-pack/conf.mli
- src/irmin-pack/irmin_pack_intf.ml
- src/irmin-pack/unix/append_only_file.ml
- src/irmin-pack/unix/append_only_file_intf.ml
- src/irmin-pack/unix/chunked_suffix.ml
- src/irmin-pack/unix/chunked_suffix_intf.ml
- src/irmin-pack/unix/dict.ml
- src/irmin-pack/unix/dict_intf.ml
- src/irmin-pack/unix/file_manager.ml
- src/irmin-pack/unix/file_manager_intf.ml
- src/irmin-pack/unix/gc_args.ml
- src/irmin-pack/unix/gc_worker.ml
- src/irmin-pack/unix/pack_store.ml
- src/irmin-pack/unix/pack_store_intf.ml
- src/irmin-pack/unix/sparse_file.ml
- src/irmin-pack/unix/store.ml
- test/irmin-pack/common.ml
- test/irmin-pack/test_flush_reload.ml
- test/irmin-pack/test_inode.ml
I was trying to simplify the logic to update the control file in the file manager. The `Append_only_file` was using an external callback to signify the need to flush when its buffer was full, which would in turn update the control file (to make that portion of the file visible)... but then we could end up with a visible partially written commit, which isn't an issue in itself, but isn't how we think about the control file payload. As the flush threshold was fairly high, I don't think this "partial flush" was really stress tested either (?)
Anyway it's gone, as it should be fine to just write to the append-only files when their memory buffer is full, we only need to update the control file at the end to publish the writes.
While testing I discovered that I broke the `Dict` flushing its …
> irmin-pack: remove append-only external flush callback

- irmin-pack-tools.opam
- src/irmin-pack-tools/README.md
- src/irmin-pack-tools/ppidx/dune
- src/irmin-pack-tools/ppidx/ppidx.ml
Adds the dump of the hashes in base58 alongside the base64 as asked by @art-w
> irmin-pack-tools: Add base58 support for ppidx

- src/irmin-pack/unix/async.ml
Lwt's latest update [5.7.0](https://github.com/ocsigen/lwt/releases/tag/5.7.0) deprecated the function `Lwt_main.abandon_yielded_and_paused` in favor of `Lwt.abandon_paused`
(see this [commit](https://github.com/ocsigen/lwt/commit/322cc45db73aaf1f77041db91e53d9ab78d773d2)).
This PR fixes that issue.
> irmin-pack: Update deprecated call

- CHANGES.md
- src/irmin/store.ml
- src/irmin/store_intf.ml
This PR is a follow up to #1836, with reduced scope to focus only on `irmin` and usage of built-in pretty-printing based on typereprs.
It adds pretty-printers for:
- Commit
- Branch
- Info
- Status
- Tree
An example output for a commit:
```sh
- : Store.commit =
{"key":"2703f0cf876e1859c79ae0cc28969810788eedb9","value":{"node":"db1d46bb4f8479641a796b638651485520b3ec01","info":{"date":1652198144,"author":"me","message":"update2"}}}
```
Closes #408
> irmin: add pretty-printers to high-level Store that work with `utop`

- CHANGES.md
- examples/merkle_proofs.md
- src/irmin-test/store.ml
- src/irmin/proof.ml
- src/irmin/proof_intf.ml
- src/irmin/store_intf.ml
- src/irmin/tree.ml
- src/irmin/tree_intf.ml
- test/irmin-pack/test_tree.ml
They are hard to maintain and nobdy use those anymore.
Note: probably more code could be simplified, I've done the "easy" bits first.
> Remove Stream Proofs

- CHANGES.md
- examples/server/config.ml
- irmin-git.opam
- src/irmin-git/contents.ml
This code previously assumed that it could read to the end of the buffer, but this is not always the case. This issue was discovered while testing the new batch API in `irmin-client`.
This PR updates `irmin-git` to use `ocaml-git` 3.14.0 or newer. This release of `ocaml-git` fixes the discovered bug and also exposes a function (`length_with_header`) that can be used to know the length of buffer read. I also updated the client/server example to use an in-memory git store, which can be used to manually verify this fix.
> irmin-git: fix decoding contents in the middle of a buffer

- CHANGES.md
- src/irmin-client/client.ml
This is (1) not needed to work properly as clone doesn't need to hold any special state in the connection; and (2) this is opening another file descriptor that is usually never closed.
> irmin-client: do not duplicate connections on clone

- .github/dependabot.yml
- .github/workflows/changelog-check.yml
- .github/workflows/coverage.yml
- .github/workflows/git.yml
- CHANGES.md
- irmin-client.opam
- src/libirmin/lib/dune
- src/libirmin/util.ml
- test/irmin-client/dune
- test/irmin-graphql/dune
https://github.com/smorimoto/irmin/actions/runs/10027617242
> Update GitHub Actions

- README.md
Please let me know if you need any changes.
> Line Editing for Irmin README

- CHANGES.md
- examples/dune
- examples/sync.ml
As reported by @kentookura and @jonsterling in https://github.com/mirage/irmin/issues/2319 , on some platforms it is necessary to initialize the mirage crypto rng before using irmin-git Sync.
> irmin-git: fix sync example, initialize mirage-crypto-rng

- CHANGES.md
- src/irmin-cli/cli.ml
- src/irmin-cli/resolver.ml
- src/irmin-git/conf.ml
- src/irmin-test/common.ml
- src/irmin/conf.ml
- src/irmin/conf.mli
- test/irmin/test_conf.ml
This PR addresses an issue with the repository root path in an `Irmin-git` repo that follows a preceding `Irmin-git` repo. Additionally, it eliminates the potential for duplicate root entries in an Irmin config.
The issue arose when trying to create two `Irmin-git` repos one after the other:
```ocaml
let users_cfg = Irmin_git.config ~bare:true "./db/users"
let pipeline_cfg = Irmin_git.config ~bare:true "./db/pipeline"
...
let* users = UserStore.Repo.v users_cfg
let* pipeline = PipelineStore.Repo.v pipeline_cfg
```
After creating `pipeline_cfg`, the `users` repository is unable to find its root, as when `Irmin-git` creates a "fresh root key", it overrides the `Univ` function that was able to decode the root directory string for `users` from the config's `Univ` map.
This results in a new …
> Fix root path issue with `Irmin-git`, and remove `allow_duplicate` for root spec key

- irmin-client.opam
- test/irmin-client/dune
- test/irmin-client/util.ml
With mirage-crypto 1.1.0, it seems that it's initialization has broken the CI, this PR aims to fix it
> Mirage crypto initialization

- .ocamlformat
- CHANGES.md
- src/irmin-git/irmin_git.ml
- src/irmin-git/irmin_git_intf.ml
As reported in #2328 the Irmin_git `Content_addressable` functor is unusable since its type `t` is private. An alternative to this PR would be to hide the CA module, since it's unused, and its presence encourages users to write code that doesn't work with git remote sync...
> irmin-git: expose Content_addressable type

- RELEASE.md
Relatively minor edits / formatting, some syntax tightening.
> Edits & formatting to Release.md

- README_PPX.md
Minor formatting / grammar changes
> Line edits for README_PPX.md

- README_LIBIRMIN.md
> Formatting README_LIBIRMING

- CODE_OF_CONDUCT.md
Small change to format the contact list, as they were all appearing one after the other instead of in a bullet list.
> Format bullet list

- examples/sync.ml
- irmin-client.opam
- test/irmin-client/dune
- test/irmin-client/util.ml
cf: https://github.com/mirage/mirage-crypto/pull/256
Installing Irmin, currently, leads to a depreciation alert on `rng` initialization.
> Upgrade to `mirage-crypto-rng` and relay on `use_default`

- irmin-bench.opam
- irmin-chunk.opam
- irmin-cli.opam
- irmin-client.opam
- irmin-containers.opam
- irmin-fs.opam
- irmin-git.opam
- irmin-graphql.opam
- irmin-mirage-git.opam
- irmin-mirage-graphql.opam
- irmin-mirage.opam
- irmin-pack-tools.opam
- irmin-pack.opam
- irmin-server.opam
- irmin-test.opam
- irmin-tezos.opam
- irmin.opam
- libirmin.opam
- ppx_irmin.opam
> Add x-maintenance-intent to opam files

- doc/irmin-pack/design/layered_store.md
Although this file may no longer be relevant with the Tezos usage, it was in the repo, so I edited it along with the rest. 
In several instances, the "pack file" is referred to rather than `irmin-pack` file. Should this be `irmin-pack` each time? Perhaps would `pack` file be more accurate or is just > pack file < correct?
> Line editing layered_store
